package lnyswz.jxc.bean;
// Generated 2013-8-14 10:42:53 by Hibernate Tools 4.0.0


/**
 * SpBgy generated by hbm2java
 */
public class SpBgy{

	private int id;
	private String depId;
	private String depName;
	private String ckId;
	private String ckmc;
	private int bgyId;
	private String bgyName;
	private String spbh;
	private String spmc;
	private String spcd;
	private String sppp;
	private String spbz;
	
	private String search;
	
	private String spbhs;
	private String spbhsSel;
	private int page;
	private int rows;

	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getDepId() {
		return depId;
	}
	public void setDepId(String depId) {
		this.depId = depId;
	}
	public String getDepName() {
		return depName;
	}
	public void setDepName(String depName) {
		this.depName = depName;
	}
	public String getCkId() {
		return ckId;
	}
	public void setCkId(String ckId) {
		this.ckId = ckId;
	}
	public String getCkmc() {
		return ckmc;
	}
	public void setCkmc(String ckmc) {
		this.ckmc = ckmc;
	}
	public int getBgyId() {
		return bgyId;
	}
	public void setBgyId(int bgyId) {
		this.bgyId = bgyId;
	}
	public String getBgyName() {
		return bgyName;
	}
	public void setBgyName(String bgyName) {
		this.bgyName = bgyName;
	}
	public String getSpbh() {
		return spbh;
	}
	public void setSpbh(String spbh) {
		this.spbh = spbh;
	}
	public String getSpmc() {
		return spmc;
	}
	public void setSpmc(String spmc) {
		this.spmc = spmc;
	}
	public String getSpcd() {
		return spcd;
	}
	public void setSpcd(String spcd) {
		this.spcd = spcd;
	}
	public String getSppp() {
		return sppp;
	}
	public void setSppp(String sppp) {
		this.sppp = sppp;
	}
	public String getSpbz() {
		return spbz;
	}
	public void setSpbz(String spbz) {
		this.spbz = spbz;
	}
	public String getSearch() {
		return search;
	}
	public void setSearch(String search) {
		this.search = search;
	}
	public String getSpbhs() {
		return spbhs;
	}
	public void setSpbhs(String spbhs) {
		this.spbhs = spbhs;
	}
	public String getSpbhsSel() {
		return spbhsSel;
	}
	public void setSpbhsSel(String spbhsSel) {
		this.spbhsSel = spbhsSel;
	}
	public int getPage() {
		return page;
	}
	public void setPage(int page) {
		this.page = page;
	}
	public int getRows() {
		return rows;
	}
	public void setRows(int rows) {
		this.rows = rows;
	}
}
