package lnyswz.jxc.bean;

import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;
import java.math.BigDecimal;

/**
 * Yfzz generated by hbm2java
 */
public class Yfzz {

	private int id;
	private String bmbh;
	private String bmmc;
	private String gysbh;
	private String gysmc;
	private BigDecimal qcje;
	private BigDecimal rkje;
	private BigDecimal fkje;
	private String jzsj;


		public int getId() {
			return id;
		}

		public void setId(int id) {
			this.id = id;
		}

		public String getBmbh() {
			return bmbh;
		}

		public void setBmbh(String bmbh) {
			this.bmbh = bmbh;
		}

		public String getBmmc() {
			return bmmc;
		}

		public void setBmmc(String bmmc) {
			this.bmmc = bmmc;
		}

		public String getGysbh() {
			return gysbh;
		}

		public void setGysbh(String gysbh) {
			this.gysbh = gysbh;
		}

		public String getGysmc() {
			return gysmc;
		}

		public void setGysmc(String gysmc) {
			this.gysmc = gysmc;
		}

		public BigDecimal getQcje() {
			return qcje;
		}

		public void setQcje(BigDecimal qcje) {
			this.qcje = qcje;
		}

		public BigDecimal getRkje() {
			return rkje;
		}

		public void setRkje(BigDecimal rkje) {
			this.rkje = rkje;
		}

		public BigDecimal getFkje() {
			return fkje;
		}

		public void setFkje(BigDecimal fkje) {
			this.fkje = fkje;
		}

		public String getJzsj() {
			return jzsj;
		}

		public void setJzsj(String jzsj) {
			this.jzsj = jzsj;
		}
}
