package lnyswz.jxc.bean;

import java.math.BigDecimal;

/**
 * YwpdDet generated by hbm2java
 */
public class YwpdDet implements java.io.Serializable {

	private int id;
	private String ywpdlsh;
	private String spbh;
	private String spmc;
	private String spcd;
	private String sppp;
	private String spbz;
	private String zjldwId;
	private String zjldwmc;
	private String cjldwId;
	private String cjldwmc;
	private BigDecimal zhxs;
	private BigDecimal zdwsl;
	private BigDecimal cdwsl;
	private BigDecimal zdwdj;
	private BigDecimal cdwdj;
	private BigDecimal spje;
	private BigDecimal qdwcb;
	private BigDecimal dwcb;
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getYwpdlsh() {
		return ywpdlsh;
	}
	public void setYwpdlsh(String ywpdlsh) {
		this.ywpdlsh = ywpdlsh;
	}
	public String getSpbh() {
		return spbh;
	}
	public void setSpbh(String spbh) {
		this.spbh = spbh;
	}
	public String getSpmc() {
		return spmc;
	}
	public void setSpmc(String spmc) {
		this.spmc = spmc;
	}
	public String getSpcd() {
		return spcd;
	}
	public void setSpcd(String spcd) {
		this.spcd = spcd;
	}
	public String getSppp() {
		return sppp;
	}
	public void setSppp(String sppp) {
		this.sppp = sppp;
	}
	public String getSpbz() {
		return spbz;
	}
	public void setSpbz(String spbz) {
		this.spbz = spbz;
	}
	public String getZjldwId() {
		return zjldwId;
	}
	public void setZjldwId(String zjldwId) {
		this.zjldwId = zjldwId;
	}
	public String getZjldwmc() {
		return zjldwmc;
	}
	public void setZjldwmc(String zjldwmc) {
		this.zjldwmc = zjldwmc;
	}
	public String getCjldwId() {
		return cjldwId;
	}
	public void setCjldwId(String cjldwId) {
		this.cjldwId = cjldwId;
	}
	public String getCjldwmc() {
		return cjldwmc;
	}
	public void setCjldwmc(String cjldwmc) {
		this.cjldwmc = cjldwmc;
	}
	public BigDecimal getZhxs() {
		return zhxs;
	}
	public void setZhxs(BigDecimal zhxs) {
		this.zhxs = zhxs;
	}
	public BigDecimal getZdwsl() {
		return zdwsl;
	}
	public void setZdwsl(BigDecimal zdwsl) {
		this.zdwsl = zdwsl;
	}
	public BigDecimal getCdwsl() {
		return cdwsl;
	}
	public void setCdwsl(BigDecimal cdwsl) {
		this.cdwsl = cdwsl;
	}
	public BigDecimal getZdwdj() {
		return zdwdj;
	}
	public void setZdwdj(BigDecimal zdwdj) {
		this.zdwdj = zdwdj;
	}
	public BigDecimal getCdwdj() {
		return cdwdj;
	}
	public void setCdwdj(BigDecimal cdwdj) {
		this.cdwdj = cdwdj;
	}
	public BigDecimal getSpje() {
		return spje;
	}
	public void setSpje(BigDecimal spje) {
		this.spje = spje;
	}
	public BigDecimal getQdwcb() {
		return qdwcb;
	}
	public void setQdwcb(BigDecimal qdwcb) {
		this.qdwcb = qdwcb;
	}
	public BigDecimal getDwcb() {
		return dwcb;
	}
	public void setDwcb(BigDecimal dwcb) {
		this.dwcb = dwcb;
	}

}
