package lnyswz.jxc.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * TAuditSet generated by hbm2java
 */
@Entity
@Table(name = "t_audit_set")
public class TAuditSet implements java.io.Serializable {

	private int id;
	private String bmbh;
	private TAudit TAudit;
	private String auditLevel;

	public TAuditSet() {
	}

	public TAuditSet(int id, String bmbh, TAudit TAudit, String auditLevel) {
		this.id = id;
		this.bmbh = bmbh;
		this.TAudit = TAudit;
		this.auditLevel = auditLevel;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "bmbh", nullable = false, length = 2)
	public String getBmbh() {
		return this.bmbh;
	}

	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}

	@ManyToOne(cascade = CascadeType.PERSIST, optional = false, fetch = FetchType.LAZY)
	public TAudit getTAudit() {
		return TAudit;
	}

	public void setTAudit(TAudit tAudit) {
		TAudit = tAudit;
	}

	@Column(name = "auditLevel", nullable = false, length = 1)
	public String getAuditLevel() {
		return this.auditLevel;
	}

	public void setAuditLevel(String auditLevel) {
		this.auditLevel = auditLevel;
	}

}
