package lnyswz.jxc.model;

import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TKfck generated by hbm2java
 */
@Entity
@Table(name = "t_bgck")
@DynamicUpdate(true)
public class TBgck implements java.io.Serializable {

	private String bgcklsh;
	private Date createTime;
	private int createId;
	private String createName;
	private String bmbh;
	private String bmmc;
	private String khbh;
	private String khmc;
	private String bz;
	private String lsh;
	private String cjBgcklsh;
	private String isCj;
	private Date cjTime;
	private Integer cjId;
	private String cjName;
	private Set<TBgckDet> TBgckDets = new HashSet<TBgckDet>(0);

	public TBgck() {
	}

	public TBgck(String bgcklsh, Date createTime, int createId, String createName, String bmbh, String bmmc, String khbh, String khmc,
                 String bz, String lsh, String cjBgcklsh, String isCj, Date cjTime, Integer cjId, String cjName, Set<TBgckDet> TBgckDets) {
		this.bgcklsh = bgcklsh;
		this.createTime = createTime;
		this.createId = createId;
		this.createName = createName;
		this.bmbh = bmbh;
		this.bmmc = bmmc;
		this.khbh = khbh;
		this.khmc = khmc;
		this.bz = bz;
		this.lsh = lsh;
		this.cjBgcklsh = cjBgcklsh;
		this.isCj = isCj;
		this.cjTime = cjTime;
		this.cjId = cjId;
		this.cjName = cjName;
		this.TBgckDets = TBgckDets;
	}

	@Id
	@Column(name = "bgcklsh", unique = true, nullable = false, length = 12)
	public String getBgcklsh() {
		return this.bgcklsh;
	}

	public void setBgcklsh(String bgcklsh) {
		this.bgcklsh = bgcklsh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 23)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createId", nullable = false)
	public int getCreateId() {
		return this.createId;
	}

	public void setCreateId(int createId) {
		this.createId = createId;
	}

	@Column(name = "createName", nullable = false, length = 20)
	public String getCreateName() {
		return createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	@Column(name = "bmbh", nullable = false, length = 2)
	public String getBmbh() {
		return this.bmbh;
	}

	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}

	@Column(name = "bmmc", nullable = false, length = 20)
	public String getBmmc() {
		return bmmc;
	}

	public void setBmmc(String bmmc) {
		this.bmmc = bmmc;
	}

	@Column(name = "khbh", length = 8)
	public String getKhbh() {
		return khbh;
	}

	public void setKhbh(String khbh) {
		this.khbh = khbh;
	}

	@Column(name = "khmc", length = 100)
	public String getKhmc() {
		return khmc;
	}

	public void setKhmc(String khmc) {
		this.khmc = khmc;
	}

	@Column(name = "bz", length = 100)
	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	@Column(name = "lsh", length = 12)
	public String getLsh() {
		return lsh;
	}

	public void setLsh(String lsh) {
		this.lsh = lsh;
	}

	@Column(name = "cjBgcklsh", length = 12)
	public String getCjBgcklsh() {
		return cjBgcklsh;
	}

	public void setCjBgcklsh(String cjBgcklsh) {
		this.cjBgcklsh = cjBgcklsh;
	}

	@Column(name = "isCj", nullable = false, length = 1)
	public String getIsCj() {
		return this.isCj;
	}

	public void setIsCj(String isCj) {
		this.isCj = isCj;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cjTime", length = 23)
	public Date getCjTime() {
		return this.cjTime;
	}

	public void setCjTime(Date cjTime) {
		this.cjTime = cjTime;
	}

	@Column(name = "cjId")
	public Integer getCjId() {
		return this.cjId;
	}

	public void setCjId(Integer cjId) {
		this.cjId = cjId;
	}

	@Column(name = "cjName", length = 20)
	public String getCjName() {
		return cjName;
	}

	public void setCjName(String cjName) {
		this.cjName = cjName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TBgck", cascade=CascadeType.ALL)
	public Set<TBgckDet> getTBgckDets() {
		return this.TBgckDets;
	}

	public void setTBgckDets(Set<TBgckDet> TBgckDets) {
		this.TBgckDets = TBgckDets;
	}
}
