package lnyswz.jxc.model;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * TCk generated by hbm2java
 */
@Entity
@Table(name = "t_car")
public class TCar implements java.io.Serializable {

	private int id;
	private String carNum;
	private String driver;
	private String bmbh;

	public TCar() {
	}

	public TCar(int id, String carNum, String driver, String bmbh) {
		this.carNum = carNum;
		this.driver = driver;
		this.bmbh = bmbh;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}


	@Column(name = "carNum", nullable = false, length = 20)
	public String getCarNum() {
		return this.carNum;
	}

	public void setCarNum(String carNum) {
		this.carNum = carNum;
	}

	@Column(name = "driver", nullable = false, length = 20)
	public String getDriver() {
		return this.driver;
	}

	public void setDriver(String driver) {
		this.driver = driver;
	}

	@Column(name = "bmbh", nullable = false, length = 2)
	public String getBmbh() {
		return bmbh;
	}

	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}
}
