package lnyswz.jxc.model;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * TCk generated by hbm2java
 */
@Entity
@Table(name = "t_car")
public class TCar implements java.io.Serializable {

	private String carNum;
	private String driver;

	public TCar() {
	}

	public TCar(String carNum, String driver) {
		this.carNum = carNum;
		this.driver = driver;
	}

	@Id
	@Column(name = "carNum", unique = true, nullable = false, length = 14)
	public String getCarNum() {
		return this.carNum;
	}

	public void setCarNum(String carNum) {
		this.carNum = carNum;
	}

	@Column(name = "driver", nullable = false, length = 20)
	public String getDriver() {
		return this.driver;
	}

	public void setDriver(String driver) {
		this.driver = driver;
	}
}
