package lnyswz.jxc.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TCgjhDet generated by hbm2java
 */
@Entity
@Table(name = "t_cgjh_det")
public class TCgjhDet implements java.io.Serializable {

	private int id;
	private TCgjh TCgjh;
	private String spbh;
	private String spmc;
	private String spcd;
	private String sppp;
	private String spbz;
	private String spdj;
	private String zjldwId;
	private String zjldwmc;
	private String cjldwId;
	private String cjldwmc;
	private BigDecimal zhxs;
	private BigDecimal zdwsl;
	private BigDecimal cdwsl;
	private BigDecimal zdwdj;
	private BigDecimal cdwdj;
	private BigDecimal spje;
	private String shdz;
	private String lxr;
	private Date dhsj;
	private String isLock;
	private String isBack;
	
	private Set<TKfrk> TKfrks = new HashSet<TKfrk>(0);
	private Set<TYwrk> TYwrks = new HashSet<TYwrk>(0);

	public TCgjhDet() {
	}

	public TCgjhDet(int id, TCgjh TCgjh, String spbh, String spmc, String spcd, String sppp, 
			String spbz, String spdj, String zjldwId, String zjldwmc, String cjldwId, String cjldwmc,
			BigDecimal zhxs, BigDecimal zdwsl, BigDecimal cdwsl, BigDecimal zdwdj, BigDecimal cdwdj,
			BigDecimal spje, String shdz, String lxr, Date dhsj, String isLock, String isBack, 
			Set<TKfrk> TKfrks, Set<TYwrk> TYwrks) {
		this.id = id;
		this.TCgjh = TCgjh;
		this.spbh = spbh;
		this.spmc = spmc;
		this.spcd = spcd;
		this.sppp = sppp;
		this.spbz = spbz;
		this.spdj = spdj;
		this.zjldwId = zjldwId;
		this.zjldwmc = zjldwmc;
		this.cjldwId = cjldwId;
		this.cjldwmc = cjldwmc;
		this.zhxs = zhxs;
		this.zdwsl = zdwsl;
		this.cdwsl = cdwsl;
		this.zdwdj = zdwdj;
		this.cdwdj = cdwdj;
		this.spje = spje;
		this.shdz = shdz;
		this.lxr = lxr;
		this.dhsj = dhsj;
		this.isLock = isLock;
		this.isBack = isBack;
		this.TKfrks = TKfrks;
		this.TYwrks = TYwrks;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cgjhlsh")
	public TCgjh getTCgjh() {
		return this.TCgjh;
	}

	public void setTCgjh(TCgjh TCgjh) {
		this.TCgjh = TCgjh;
	}

	@Column(name = "spbh", nullable = false, length = 7)
	public String getSpbh() {
		return spbh;
	}

	public void setSpbh(String spbh) {
		this.spbh = spbh;
	}

	@Column(name = "spmc", nullable = false, length = 100)
	public String getSpmc() {
		return spmc;
	}

	public void setSpmc(String spmc) {
		this.spmc = spmc;
	}

	@Column(name = "spcd", nullable = false, length = 20)
	public String getSpcd() {
		return spcd;
	}

	public void setSpcd(String spcd) {
		this.spcd = spcd;
	}

	@Column(name = "sppp", length = 20)
	public String getSppp() {
		return sppp;
	}

	public void setSppp(String sppp) {
		this.sppp = sppp;
	}

	@Column(name = "spbz", length = 20)
	public String getSpbz() {
		return spbz;
	}

	public void setSpbz(String spbz) {
		this.spbz = spbz;
	}
	
	@Column(name = "spdj", length = 20)
	public String getSpdj() {
		return spdj;
	}
	
	public void setSpdj(String spdj) {
		this.spdj = spdj;
	}

	@Column(name = "zjldwId", nullable = false, length = 2)
	public String getZjldwId() {
		return zjldwId;
	}

	public void setZjldwId(String zjldwId) {
		this.zjldwId = zjldwId;
	}

	@Column(name = "zjldwmc", nullable = false, length = 20)
	public String getZjldwmc() {
		return zjldwmc;
	}

	public void setZjldwmc(String zjldwmc) {
		this.zjldwmc = zjldwmc;
	}

	@Column(name = "cjldwId", length = 2)
	public String getCjldwId() {
		return cjldwId;
	}

	public void setCjldwId(String cjldwId) {
		this.cjldwId = cjldwId;
	}

	@Column(name = "cjldwmc", length = 20)
	public String getCjldwmc() {
		return cjldwmc;
	}

	public void setCjldwmc(String cjldwmc) {
		this.cjldwmc = cjldwmc;
	}

	@Column(name = "zhxs", nullable = false, precision = 18, scale = 3)
	public BigDecimal getZhxs() {
		return zhxs;
	}

	public void setZhxs(BigDecimal zhxs) {
		this.zhxs = zhxs;
	}

	@Column(name = "zdwsl", precision = 18, scale = 3)
	public BigDecimal getZdwsl() {
		return this.zdwsl;
	}

	public void setZdwsl(BigDecimal zdwsl) {
		this.zdwsl = zdwsl;
	}

	@Column(name = "cdwsl", precision = 18, scale = 3)
	public BigDecimal getCdwsl() {
		return this.cdwsl;
	}

	public void setCdwsl(BigDecimal cdwsl) {
		this.cdwsl = cdwsl;
	}

	@Column(name = "zdwdj", precision = 18, scale = 3)
	public BigDecimal getZdwdj() {
		return this.zdwdj;
	}

	public void setZdwdj(BigDecimal zdwdj) {
		this.zdwdj = zdwdj;
	}

	@Column(name = "cdwdj", precision = 18, scale = 3)
	public BigDecimal getCdwdj() {
		return this.cdwdj;
	}

	public void setCdwdj(BigDecimal cdwdj) {
		this.cdwdj = cdwdj;
	}

	@Column(name = "spje", precision = 18, scale = 6)
	public BigDecimal getSpje() {
		return this.spje;
	}

	public void setSpje(BigDecimal spje) {
		this.spje = spje;
	}
	
	@Column(name = "shdz", length = 100)
	public String getShdz() {
		return this.shdz;
	}

	public void setShdz(String shdz) {
		this.shdz = shdz;
	}
	
	@Column(name = "lxr", length = 50)
	public String getLxr() {
		return this.lxr;
	}
	
	public void setLxr(String lxr) {
		this.lxr = lxr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dhsj", length = 23)
	public Date getDhsj() {
		return this.dhsj;
	}

	public void setDhsj(Date dhsj) {
		this.dhsj = dhsj;
	}
	
	@Column(name = "isLock", nullable = false, length = 1)
	public String getIsLock() {
		return isLock;
	}

	public void setIsLock(String isLock) {
		this.isLock = isLock;
	}

	@Column(name = "isBack", nullable = false, length = 1)
	public String getIsBack() {
		return isBack;
	}

	public void setIsBack(String isBack) {
		this.isBack = isBack;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TCgjhs")
	public Set<TKfrk> getTKfrks() {
		return this.TKfrks;
	}

	public void setTKfrks(Set<TKfrk> TKfrks) {
		this.TKfrks = TKfrks;
	}
	
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TCgjhs")
	public Set<TYwrk> getTYwrks() {
		return this.TYwrks;
	}

	public void setTYwrks(Set<TYwrk> TYwrks) {
		this.TYwrks = TYwrks;
	}

}
