package lnyswz.jxc.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TCgxqDet generated by hbm2java
 */
@Entity
@Table(name = "t_cgxq_det")
public class TCgxqDet implements java.io.Serializable {

	private int id;
	private TCgxq TCgxq;
	private String spbh;
	private String spmc;
	private String spcd;
	private String sppp;
	private String spbz;
	private String zjldwId;
	private String zjldwmc;
	private String cjldwId;
	private String cjldwmc;
	private BigDecimal zhxs;
	private BigDecimal zdwsl;
	private BigDecimal cdwsl;
	private BigDecimal zdwdj;
	private BigDecimal cdwdj;
	private BigDecimal zdwxsdj;
	private BigDecimal cdwxsdj;
	private BigDecimal spje;
	private String isCancel;
	private Integer cancelId;
	private Date cancelTime;
	private String cancelName;
	private String isRefuse;
	private Integer refuseId;
	private Date refuseTime;
	private String refuseName;
	private String isComplete;
	private TCgjh TCgjh;

	public TCgxqDet() {
	}

	public TCgxqDet(int id, TCgxq TCgxq, String spbh, String spmc, String spcd, String sppp, 
			String spbz, String zjldwId, String zjldwmc, String cjldwId, String cjldwmc, BigDecimal zhxs,
			BigDecimal zdwsl, BigDecimal cdwsl, BigDecimal zdwdj, BigDecimal cdwdj,	BigDecimal zdwxsdj,
			BigDecimal cdwxsdj, BigDecimal spje, String isCancel, Integer cancelId, Date cancelTime,
			String cancelName, String isRefuse, Integer refuseId, Date refuseTime, String refuseName, String isComplete,
			TCgjh TCgjh) {
		this.id = id;
		this.TCgxq = TCgxq;
		this.spbh = spbh;
		this.spmc = spmc;
		this.spcd = spcd;
		this.sppp = sppp;
		this.spbz = spbz;
		this.zjldwId = zjldwId;
		this.zjldwmc = zjldwmc;
		this.cjldwId = cjldwId;
		this.cjldwmc = cjldwmc;
		this.zhxs = zhxs;
		this.zdwsl = zdwsl;
		this.cdwsl = cdwsl;
		this.zdwdj = zdwdj;
		this.cdwdj = cdwdj;
		this.zdwxsdj = zdwxsdj;
		this.cdwxsdj = cdwxsdj;
		this.spje = spje;
		this.isCancel = isCancel;
		this.cancelId = cancelId;
		this.cancelTime = cancelTime;
		this.cancelName = cancelName;
		this.isRefuse = isRefuse;
		this.refuseId = refuseId;
		this.refuseTime = refuseTime;
		this.refuseName = refuseName;
		this.isComplete = isComplete;
		this.TCgjh = TCgjh;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cgxqlsh", nullable = false)
	public TCgxq getTCgxq() {
		return this.TCgxq;
	}

	public void setTCgxq(TCgxq TCgxq) {
		this.TCgxq = TCgxq;
	}

	@Column(name = "spbh", nullable = false, length = 7)
	public String getSpbh() {
		return spbh;
	}

	public void setSpbh(String spbh) {
		this.spbh = spbh;
	}

	@Column(name = "spmc", nullable = false, length = 100)
	public String getSpmc() {
		return spmc;
	}

	public void setSpmc(String spmc) {
		this.spmc = spmc;
	}

	@Column(name = "spcd", nullable = false, length = 20)
	public String getSpcd() {
		return spcd;
	}

	public void setSpcd(String spcd) {
		this.spcd = spcd;
	}

	@Column(name = "sppp", length = 20)
	public String getSppp() {
		return sppp;
	}

	public void setSppp(String sppp) {
		this.sppp = sppp;
	}

	@Column(name = "spbz", length = 20)
	public String getSpbz() {
		return spbz;
	}

	public void setSpbz(String spbz) {
		this.spbz = spbz;
	}

	@Column(name = "zjldwId", nullable = false, length = 2)
	public String getZjldwId() {
		return zjldwId;
	}

	public void setZjldwId(String zjldwId) {
		this.zjldwId = zjldwId;
	}

	@Column(name = "zjldwmc", nullable = false, length = 20)
	public String getZjldwmc() {
		return zjldwmc;
	}

	public void setZjldwmc(String zjldwmc) {
		this.zjldwmc = zjldwmc;
	}

	@Column(name = "cjldwId", length = 2)
	public String getCjldwId() {
		return cjldwId;
	}

	public void setCjldwId(String cjldwId) {
		this.cjldwId = cjldwId;
	}

	@Column(name = "cjldwmc", length = 20)
	public String getCjldwmc() {
		return cjldwmc;
	}

	public void setCjldwmc(String cjldwmc) {
		this.cjldwmc = cjldwmc;
	}

	@Column(name = "zhxs", nullable = false, precision = 18, scale = 3)
	public BigDecimal getZhxs() {
		return zhxs;
	}

	public void setZhxs(BigDecimal zhxs) {
		this.zhxs = zhxs;
	}
	
	@Column(name = "zdwsl", nullable = true, precision = 18, scale = 3)
	public BigDecimal getZdwsl() {
		return this.zdwsl;
	}

	public void setZdwsl(BigDecimal zdwsl) {
		this.zdwsl = zdwsl;
	}

	@Column(name = "cdwsl", precision = 18, scale = 3)
	public BigDecimal getCdwsl() {
		return this.cdwsl;
	}

	public void setCdwsl(BigDecimal cdwsl) {
		this.cdwsl = cdwsl;
	}

	@Column(name = "zdwdj", nullable = true, precision = 18, scale = 4)
	public BigDecimal getZdwdj() {
		return this.zdwdj;
	}

	public void setZdwdj(BigDecimal zdwdj) {
		this.zdwdj = zdwdj;
	}

	@Column(name = "cdwdj", precision = 18, scale = 4)
	public BigDecimal getCdwdj() {
		return this.cdwdj;
	}

	public void setCdwdj(BigDecimal cdwdj) {
		this.cdwdj = cdwdj;
	}

	@Column(name = "zdwxsdj", precision = 18, scale = 4)
	public BigDecimal getZdwxsdj() {
		return zdwxsdj;
	}

	public void setZdwxsdj(BigDecimal zdwxsdj) {
		this.zdwxsdj = zdwxsdj;
	}

	@Column(name = "cdwxsdj", precision = 18, scale = 4)
	public BigDecimal getCdwxsdj() {
		return cdwxsdj;
	}

	public void setCdwxsdj(BigDecimal cdwxsdj) {
		this.cdwxsdj = cdwxsdj;
	}

	@Column(name = "spje", nullable = true, precision = 18, scale = 4)
	public BigDecimal getSpje() {
		return this.spje;
	}

	public void setSpje(BigDecimal spje) {
		this.spje = spje;
	}
	
	@Column(name = "isCancel", nullable = false, length = 1)
	public String getIsCancel() {
		return isCancel;
	}

	public void setIsCancel(String isCancel) {
		this.isCancel = isCancel;
	}

	@Column(name = "cancelName", length = 20)
	public String getCancelName() {
		return cancelName;
	}
	
	public void setCancelName(String cancelName) {
		this.cancelName = cancelName;
	}
	
	@Column(name = "cancelId")
	public Integer getCancelId() {
		return cancelId;
	}
	
	public void setCancelId(Integer cancelId) {
		this.cancelId = cancelId;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cancelTime", nullable = true, length = 23)
	public Date getCancelTime() {
		return cancelTime;
	}
	
	public void setCancelTime(Date cancelTime) {
		this.cancelTime = cancelTime;
	}
	
	@Column(name = "isRefuse", nullable = false, length = 1)
	public String getIsRefuse() {
		return isRefuse;
	}
	
	public void setIsRefuse(String isRefuse) {
		this.isRefuse = isRefuse;
	}
	
	@Column(name = "refuseName", length = 20)
	public String getRefuseName() {
		return refuseName;
	}
	
	public void setRefuseName(String refuseName) {
		this.refuseName = refuseName;
	}
	
	@Column(name = "refuseId")
	public Integer getRefuseId() {
		return refuseId;
	}
	
	public void setRefuseId(Integer refuseId) {
		this.refuseId = refuseId;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "refuseTime", nullable = true, length = 23)
	public Date getRefuseTime() {
		return refuseTime;
	}
	
	public void setRefuseTime(Date refuseTime) {
		this.refuseTime = refuseTime;
	}
	
	@Column(name = "isComplete", nullable = false, length = 1)
	public String getIsComplete() {
		return isComplete;
	}
	
	public void setIsComplete(String isComplete) {
		this.isComplete = isComplete;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cgjhlsh")
	public TCgjh getTCgjh() {
		return this.TCgjh;
	}

	public void setTCgjh(TCgjh TCgjh) {
		this.TCgjh = TCgjh;
	}

}
