package lnyswz.jxc.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TCk generated by hbm2java
 */
@Entity
@Table(name = "t_ck")
public class TCk implements java.io.Serializable {

	private String id;
	private String ckmc;
	private TDepartment TDepartment;
	private Set<THw> THws = new HashSet<THw>(0);

	public TCk() {
	}

	public TCk(String id, String ckmc) {
		this.id = id;
		this.ckmc = ckmc;
	}

	public TCk(String id, String ckmc, TDepartment TDepartment, Set<THw> THws) {
		this.id = id;
		this.ckmc = ckmc;
		this.TDepartment = TDepartment;
		this.THws = THws;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 2)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "ckmc", nullable = false, length = 50)
	public String getCkmc() {
		return this.ckmc;
	}

	public void setCkmc(String ckmc) {
		this.ckmc = ckmc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "depId", nullable = false)
	public TDepartment getTDepartment() {
		return TDepartment;
	}

	public void setTDepartment(TDepartment tDepartment) {
		TDepartment = tDepartment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCk")
	public Set<THw> getTHws() {
		return this.THws;
	}

	public void setTHws(Set<THw> THws) {
		this.THws = THws;
	}

}
