package lnyswz.jxc.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TDict generated by hbm2java
 */
@Entity
@Table(name = "t_dict")
public class TDict implements java.io.Serializable {

	private String id;
	private String ename;
	private String cname;
	private String tname;
	private String genre;
	private String display;
	private String specials;
	private int orderNum;
	private String frozen;
	private String specialValues;
	private String show;
	private String tree;
	private String orderBy;
	private String isHj;
	private String sqlWhere;
	private String outGroupBy;
	private String inGroupBy;
	private String isDepName;
	private String orderByTree;
	private String isShow;
	public TDict() {
	}

	public TDict(String id, String ename, String cname) {
		this.id = id;
		this.ename = ename;
		this.cname = cname;
	}
	public TDict(String id,String ename,String cname,String tname,String genre,String display,String description,int orderNum,String frozen,String specialValues,String show,String tree,String orderBy,
				String isHj,String sqlWhere,String outGroupBy,String inGroupBy,String isDepName,String orderByTree,String isShow){
		this.id=id;
		this.ename=ename;
		this.cname=cname;
		this.tname=tname;
		this.genre=genre;
		this.display=display;
		this.specials=specials;
		this.orderNum=orderNum;
		this.frozen=frozen;
		this.specialValues=specialValues;
		this.show=show;
		this.tree=tree;
		this.orderBy=orderBy;
		this.isHj=isHj;
		this.sqlWhere=sqlWhere;
		this.outGroupBy=outGroupBy;
		this.inGroupBy=inGroupBy;
		this.isDepName=isDepName;
		this.orderByTree=orderByTree;
		this.isShow=isShow;
	}
	@Id
	@Column(name = "id", unique = true, nullable = false, length = 36) 
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}
	@Column(name = "orderNum", nullable = true)
	public int getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(int orderNum) {
		this.orderNum = orderNum;
	}
	@Column(name = "ename", nullable = false, length = 50)
	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	@Column(name = "cname", nullable = false, length = 100)
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}
	@Column(name = "tname", nullable = true, length = 100)
	public String getTname() {
		return this.tname;
	}

	public void setTname(String tname) {
		this.tname = tname;
	}
	
	@Column(name = "frozen", nullable = true, length = 100)
	public String getFrozen() {
		return this.frozen;
	}

	public void setFrozen(String frozen) {
		this.frozen = frozen;
	}
	
	@Column(name = "genre", nullable = true, length = 100)
	public String getGenre() {
		return this.genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	@Column(name = "display", nullable = true, length = 100)
	public String getDisplay() {
		return this.display;
	}

	public void setDisplay(String display) {
		this.display = display;
	}
	@Column(name = "specials", nullable = true, length = 100)
	public String getSpecials() {
		return this.specials;
	}

	public void setSpecials(String specials) {
		this.specials = specials;
	}
	@Column(name = "show", nullable = true, length = 100)
	public String getShow() {
		return this.show;
	}

	public void setShow(String show) {
		this.show = show;
	}
	@Column(name = "specialValues", nullable = true, length = 500)
	public String getSpecialValues() {
		return this.specialValues;
	}

	public void setSpecialValues(String specialValues) {
		this.specialValues = specialValues;
	}
	@Column(name = "tree", nullable = true, length = 500)
	public String getTree() {
		return this.tree;
	}

	public void setTree(String tree) {
		this.tree = tree;
	}
	@Column(name = "orderBy", nullable = true, length = 500)
	public String getOrderBy() {
		return this.orderBy;
	}

	public void setOrderBy(String orderBy) {
		this.orderBy = orderBy;
	}
	@Column(name = "isHj", nullable = true, length = 500)
	public String getIsHj() {
		return this.isHj;
	}

	public void setIsHj(String isHj) {
		this.isHj = isHj;
	}
	@Column(name = "sqlWhere", nullable = true, length = 500)
	public String getSqlWhere() {
		return this.sqlWhere;
	}

	public void setSqlWhere(String sqlWhere) {
		this.sqlWhere = sqlWhere;
	}
	@Column(name = "outGroupBy", nullable = true, length = 500)
	public String getOutGroupBy() {
		return this.outGroupBy;
	}

	public void setOutGroupBy(String outGroupBy) {
		this.outGroupBy = outGroupBy;
	}
	@Column(name = "inGroupBy", nullable = true, length = 500)
	public String getInGroupBy() {
		return this.inGroupBy;
	}

	public void setInGroupBy(String inGroupBy) {
		this.inGroupBy = inGroupBy;
	}
	@Column(name = "isDepName", nullable = true, length = 500)
	public String getIsDepName() {
		return this.isDepName;
	}

	public void setIsDepName(String isDepName) {
		this.isDepName = isDepName;
	}
	@Column(name = "orderByTree", nullable = true, length = 500)
	public String getOrderByTree() {
		return this.orderByTree;
	}

	public void setOrderByTree(String orderByTree) {
		this.orderByTree = orderByTree;
	}
	@Column(name = "isShow", nullable = true, length = 1)
	public String getIsShow() {
		return this.isShow;
	}
	
	public void setIsShow(String isShow) {
		this.isShow = isShow;
	}
}
