package lnyswz.jxc.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TDict generated by hbm2java
 */
@Entity
@Table(name = "t_dict")
public class TDict implements java.io.Serializable {

	private String id;
	private String ename;
	private String cname;
	private String tname;
	private String genre;
	private String display;
	private String specials;
	private int orderNum;
	private String frozen;
	private String specialValues;
	private String show;
	private String tree;
	private String orderBy;
	public TDict() {
	}

	public TDict(String id, String ename, String cname) {
		this.id = id;
		this.ename = ename;
		this.cname = cname;
	}
	public TDict(String id,String ename,String cname,String tname,String genre,String display,String description,int orderNum,String frozen,String specialValues,String show,String tree,String orderBy){
		this.id=id;
		this.ename=ename;
		this.cname=cname;
		this.tname=tname;
		this.genre=genre;
		this.display=display;
		this.specials=specials;
		this.orderNum=orderNum;
		this.frozen=frozen;
		this.specialValues=specialValues;
		this.show=show;
		this.tree=tree;
		this.orderBy=orderBy;
	}
	@Id
	@Column(name = "id", unique = true, nullable = false, length = 36) 
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}
	@Column(name = "orderNum", nullable = true)
	public int getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(int orderNum) {
		this.orderNum = orderNum;
	}
	@Column(name = "ename", nullable = false, length = 50)
	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	@Column(name = "cname", nullable = false, length = 100)
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}
	@Column(name = "tname", nullable = true, length = 100)
	public String getTname() {
		return this.tname;
	}

	public void setTname(String tname) {
		this.tname = tname;
	}
	
	@Column(name = "frozen", nullable = true, length = 100)
	public String getFrozen() {
		return this.frozen;
	}

	public void setFrozen(String frozen) {
		this.frozen = frozen;
	}
	
	@Column(name = "genre", nullable = true, length = 100)
	public String getGenre() {
		return this.genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	@Column(name = "display", nullable = true, length = 100)
	public String getDisplay() {
		return this.display;
	}

	public void setDisplay(String display) {
		this.display = display;
	}
	@Column(name = "specials", nullable = true, length = 100)
	public String getSpecials() {
		return this.specials;
	}

	public void setSpecials(String specials) {
		this.specials = specials;
	}
	@Column(name = "show", nullable = true, length = 100)
	public String getShow() {
		return this.show;
	}

	public void setShow(String show) {
		this.show = show;
	}
	@Column(name = "specialValues", nullable = true, length = 500)
	public String getSpecialValues() {
		return this.specialValues;
	}

	public void setSpecialValues(String specialValues) {
		this.specialValues = specialValues;
	}
	@Column(name = "tree", nullable = true, length = 500)
	public String getTree() {
		return this.tree;
	}

	public void setTree(String tree) {
		this.tree = tree;
	}
	@Column(name = "orderBy", nullable = true, length = 500)
	public String getOrderBy() {
		return this.orderBy;
	}

	public void setOrderBy(String orderBy) {
		this.orderBy = orderBy;
	}
}
