package lnyswz.jxc.model;

import javax.persistence.*;
import java.util.Date;

/**
 * TEdited generated by wwy
 */
@Entity
@Table(name = "t_edited")
public class TEdited implements java.io.Serializable {

	private int id;
	private int createId;
	private String createName;
	private Date createTime;
	private String lsh;
	private String fieldName;
	private String oldValue;
	private String newValue;

	public TEdited() {
	}

	public TEdited(int id,  int createId, String createName, Date createTime, String lsh, String fieldName,
			String oldValue, String newValue) {
		this.id = id;
		this.createId = createId;
		this.createName = createName;
		this.createTime = createTime;
		this.lsh = lsh;
		this.fieldName = fieldName;
		this.oldValue = oldValue;
		this.newValue = newValue;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "createId", nullable = false)
	public int getCreateId() {
		return createId;
	}

	public void setCreateId(int createId) {
		this.createId = createId;
	}

	@Column(name = "createName", nullable = false, length = 20)
	public String getCreateName() {
		return createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 23)
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "lsh", nullable = false, length = 12)
	public String getLsh() {
		return lsh;
	}

	public void setLsh(String lsh) {
		this.lsh = lsh;
	}

	@Column(name = "fieldName", nullable = false)
	public String getFieldName() {
		return fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	@Column(name = "oldValue")
	public String getOldValue() {
		return oldValue;
	}

	public void setOldValue(String oldValue) {
		this.oldValue = oldValue;
	}

	@Column(name = "newValue", nullable = false)
	public String getNewValue() {
		return newValue;
	}

	public void setNewValue(String newValue) {
		this.newValue = newValue;
	}
}
