package lnyswz.jxc.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TFh generated by hbm2java
 */
@Entity
@Table(name = "t_fh")
public class TFh implements java.io.Serializable {

	private String id;
	private String fhmc;
	private TDepartment TDepartment;

	public TFh() {
	}

	public TFh(String id, String fhmc, TDepartment TDepartment) {
		this.id = id;
		this.fhmc = fhmc;
		this.TDepartment = TDepartment;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 2)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "fhmc", nullable = false, length = 50)
	public String getFhmc() {
		return this.fhmc;
	}

	public void setFhmc(String fhmc) {
		this.fhmc = fhmc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "depId", nullable = false)
	public TDepartment getTDepartment() {
		return TDepartment;
	}

	public void setTDepartment(TDepartment tDepartment) {
		TDepartment = tDepartment;
	}

}
