package lnyswz.jxc.model;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TFhzz generated by hbm2java
 */
@Entity
@Table(name = "t_fhzz")
public class TFhzz implements java.io.Serializable {

	private int id;
	private String bmbh;
	private String bmmc;
	private String fhId;
	private String fhmc;
	private String spbh;
	private String spmc;
	private String spcd;
	private String sppp;
	private String spbz;
	private String zjldwId;
	private String zjldwmc;
	private String cjldwId;
	private String cjldwmc;
	private BigDecimal zhxs;
	private BigDecimal qcsl;
	private BigDecimal rksl;
	private BigDecimal cksl;
	private String jzsj;

	public TFhzz() {
	}

	public TFhzz(int id, String bmbh, String bmmc, String fhId, String fhmc,
			String spbh, String spmc, String spcd, String sppp, String spbz,
			String zjldwId, String zjldwmc, String cjldwId, String cjldwmc,
			BigDecimal zhxs, BigDecimal qcsl, BigDecimal rksl, BigDecimal cksl,
			String jzsj) {
		this.id = id;
		this.bmbh = bmbh;
		this.bmmc = bmmc;
		this.fhId = fhId;
		this.fhmc = fhmc;
		this.spbh = spbh;
		this.spmc = spmc;
		this.spcd = spcd;
		this.sppp = sppp;
		this.spbz = spbz;
		this.zjldwId = zjldwId;
		this.zjldwmc = zjldwmc;
		this.cjldwId = cjldwId;
		this.cjldwmc = cjldwmc;
		this.zhxs = zhxs;
		this.qcsl = qcsl;
		this.rksl = rksl;
		this.cksl = cksl;
		this.jzsj = jzsj;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "bmbh", nullable = false, length = 2)
	public String getBmbh() {
		return this.bmbh;
	}
	
	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}
	
	@Column(name = "bmmc", nullable = false, length = 20)
	public String getBmmc() {
		return this.bmmc;
	}
	
	public void setBmmc(String bmmc) {
		this.bmmc = bmmc;
	}

	@Column(name = "fhId", length = 2)
	public String getFhId() {
		return fhId;
	}

	public void setFhId(String fhId) {
		this.fhId = fhId;
	}
	
	@Column(name = "fhmc", length = 20)
	public String getFhmc() {
		return this.fhmc;
	}
	
	public void setFhmc(String fhmc) {
		this.fhmc = fhmc;
	}
	
	@Column(name = "spbh", nullable = false, length = 7)
	public String getSpbh() {
		return this.spbh;
	}
	
	public void setSpbh(String spbh) {
		this.spbh = spbh;
	}
	
	@Column(name = "spmc", nullable = false, length = 100)
	public String getSpmc() {
		return this.spmc;
	}
	
	public void setSpmc(String spmc) {
		this.spmc = spmc;
	}
	
	@Column(name = "spcd", length = 20)
	public String getSpcd() {
		return this.spcd;
	}
	
	public void setSpcd(String spcd) {
		this.spcd = spcd;
	}
	
	@Column(name = "sppp", length = 20)
	public String getSppp() {
		return this.sppp;
	}
	
	public void setSppp(String sppp) {
		this.sppp = sppp;
	}
	
	@Column(name = "spbz", length = 20)
	public String getSpbz() {
		return this.spbz;
	}
	
	public void setSpbz(String spbz) {
		this.spbz = spbz;
	}
	
	@Column(name = "zjldwId", nullable = false, length = 2)
	public String getZjldwId() {
		return this.zjldwId;
	}
	
	public void setZjldwId(String zjldwId) {
		this.zjldwId = zjldwId;
	}
	
	@Column(name = "zjldwmc", nullable = false, length = 10)
	public String getZjldwmc() {
		return this.zjldwmc;
	}
	
	public void setZjldwmc(String zjldwmc) {
		this.zjldwmc = zjldwmc;
	}
	
	@Column(name = "cjldwId", length = 2)
	public String getCjldwId() {
		return this.cjldwId;
	}
	
	public void setCjldwId(String cjldwId) {
		this.cjldwId = cjldwId;
	}
	
	@Column(name = "cjldwmc", length = 10)
	public String getCjldwmc() {
		return this.cjldwmc;
	}
	
	public void setCjldwmc(String cjldwmc) {
		this.cjldwmc = cjldwmc;
	}

	@Column(name = "zhxs", precision = 18, scale = 2)
	public BigDecimal getZhxs() {
		return this.zhxs;
	}
	
	public void setZhxs(BigDecimal zhxs) {
		this.zhxs = zhxs;
	}
	
	@Column(name = "qcsl", precision = 18, scale = 3)
	public BigDecimal getQcsl() {
		return this.qcsl;
	}

	public void setQcsl(BigDecimal qcsl) {
		this.qcsl = qcsl;
	}

	@Column(name = "rksl", precision = 18, scale = 3)
	public BigDecimal getRksl() {
		return this.rksl;
	}

	public void setRksl(BigDecimal rksl) {
		this.rksl = rksl;
	}

	@Column(name = "cksl", precision = 18, scale = 3)
	public BigDecimal getCksl() {
		return cksl;
	}

	public void setCksl(BigDecimal cksl) {
		this.cksl = cksl;
	}

	@Column(name = "jzsj", length = 6)
	public String getJzsj() {
		return this.jzsj;
	}

	public void setJzsj(String jzsj) {
		this.jzsj = jzsj;
	}

}
