package lnyswz.jxc.model;

import javax.persistence.*;
import java.math.BigDecimal;

/**
 * TFkRk generated by hbm2java
 */
@Entity
@Table(name = "t_rkfk_ywrk")
public class TFkRk implements java.io.Serializable {
	private int id;
	private String ywrklsh;
	private long ywrkId;
	private BigDecimal fkje;
	private String isYf;
	private Integer deleted;
	private String rkfklsh;

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ywrklsh", nullable = false, length = 12)
	public String getYwrklsh() {
		return this.ywrklsh;
	}

	public void setYwrklsh(String ywrklsh) {
		this.ywrklsh = ywrklsh;
	}

	public long getYwrkId() {
		return ywrkId;
	}

	@Column(name = "ywrkId", nullable = false)
	public void setYwrkId(long ywrkId) {
		this.ywrkId = ywrkId;
	}

	@Column(name = "fkje", precision = 18, scale = 2)
	public BigDecimal getFkje() {
		return this.fkje;
	}

	public void setFkje(BigDecimal fkje) {
		this.fkje = fkje;
	}

	@Column(name = "isYf", nullable = false, length = 1)
	public String getIsYf() {
		return this.isYf;
	}

	public void setIsYf(String isYf) {
		this.isYf = isYf;
	}

	@Column(name = "deleted", nullable = false)
	public Integer getDeleted() {
		return deleted;
	}

	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}

	@Column(name = "rkfklsh", nullable = false, length = 12)
	public String getRkfklsh() {
		return rkfklsh;
	}

	public void setRkfklsh(String rkfklsh) {
		this.rkfklsh = rkfklsh;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "rkfklsh", nullable = false)
//	public TRkfk getTRkfk() {
//		return this.TRkfk;
//	}
//
//	public void setTRkfk(TRkfk TRkfk) {
//		this.TRkfk = TRkfk;
//	}
}
