package lnyswz.jxc.model;

import javax.persistence.*;
import java.math.BigDecimal;

/**
 * TFkRk generated by hbm2java
 */
@Entity
@Table(name = "t_rkfk_ywrk")
public class TFkRk implements java.io.Serializable {
	private int id;
	private String ywrklsh;
	private BigDecimal fkje;
	private String isYf;
	private TRkfk TRkfk;
	
	public TFkRk() {
	}

	public TFkRk(int id, String ywrklsh, BigDecimal fkje, String isYf, TRkfk TRkfk) {
		this.id = id;
		this.ywrklsh = ywrklsh;
		this.fkje = fkje;
		this.isYf = isYf;
		this.TRkfk = TRkfk;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ywrklsh", nullable = false, length = 12)
	public String getYwrklsh() {
		return this.ywrklsh;
	}

	public void setYwrklsh(String ywrklsh) {
		this.ywrklsh = ywrklsh;
	}

	@Column(name = "fkje", precision = 18, scale = 2)
	public BigDecimal getFkje() {
		return this.fkje;
	}

	public void setFkje(BigDecimal fkje) {
		this.fkje = fkje;
	}

	@Column(name = "isYf", nullable = false, length = 1)
	public String getIsYf() {
		return this.isYf;
	}

	public void setIsYf(String isYf) {
		this.isYf = isYf;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rkfklsh", nullable = false)
	public TRkfk getTRkfk() {
		return this.TRkfk;
	}

	public void setTRkfk(TRkfk TRkfk) {
		this.TRkfk = TRkfk;
	}
}
