package lnyswz.jxc.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TFplx generated by hbm2java
 */
@Entity
@Table(name = "t_fplx")
public class TFplx implements java.io.Serializable {

	private String id;
	private String fplxmc;

	public TFplx() {
	}

	public TFplx(String id) {
		this.id = id;
	}

	public TFplx(String id, String fplxmc) {
		this.id = id;
		this.fplxmc = fplxmc;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 2)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "fplxmc", unique = true, length = 50)
	public String getFplxmc() {
		return this.fplxmc;
	}

	public void setFplxmc(String fplxmc) {
		this.fplxmc = fplxmc;
	}

}
