package lnyswz.jxc.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * TFyd generated by hbm2java
 */
@Entity
@Table(name = "t_fyd")
public class TFyd implements java.io.Serializable {

	private String fydlsh;
	private String bmbh;
	private Date createTime;
	private String status;
	private String publisher;
	private String publishercn;
	private String checkCode;
	private String tzdbh;
	private String cbsydsno;
	private String bsno;
	private String bname;
	private String isbn;
	private Date tzrq;
	private String yc;
	private BigDecimal price;
	private int tzdys;
	private int yangshu;
	private int zongym;
	private int cbzs;
	private String kbgg;
	private String cpgg;
	private BigDecimal dwyz;
	private String zdr;
	private String zdfs;
	private String zzfs;
	private String sended;
	private int sendId;
	private String sendName;
	private Date sendTime;
	private Set<TFydDet> TFydDets = new HashSet<TFydDet>(0);
	
	public TFyd() {
	}

	public TFyd(String fydlsh, String bmbh, Date createTime,	String status, String publisher, String publishercn, String checkCode, String tzdbh, String cbsydsno, String bsno, String bname, String isbn,
			Date tzrq, String yc, BigDecimal price, int tzdys, int yangshu, int zongym, int cbzs, String kbgg, String cpgg, BigDecimal dwyz, String zdr,
			String zdfs, String zzfs, String sended, int sendId, String sendName, Date sendTime, Set<TFydDet> TFydDets) {
		this.fydlsh = fydlsh;
		this.bmbh = bmbh;
		this.createTime = createTime;
		this.status = status;
		this.publisher = publisher;
		this.publishercn = publishercn;
		this.checkCode = checkCode;
		this.tzdbh = tzdbh;
		this.cbsydsno = cbsydsno;
		this.bsno = bsno;
		this.bname = bname;
		this.isbn = isbn;
		this.tzrq = tzrq;
		this.yc = yc;
		this.price = price;
		this.tzdys = tzdys;
		this.yangshu = yangshu;
		this.zongym = zongym;
		this.cbzs = cbzs;
		this.kbgg = kbgg;
		this.cpgg = cpgg;
		this.dwyz = dwyz;
		this.zdr = zdr;
		this.zdfs = zdfs;
		this.zzfs = zzfs;
		this.sended = sended;
		this.sendId = sendId;
		this.sendName = sendName;
		this.sendTime = sendTime;
		this.TFydDets = TFydDets;
	}


	@Id
	@Column(name = "fydlsh", unique = true, nullable = false, length = 12)
	public String getFydlsh() {
		return fydlsh;
	}

	public void setFydlsh(String fydlsh) {
		this.fydlsh = fydlsh;
	}
	
	@Column(name = "bmbh", nullable = false, length = 2)
	public String getBmbh() {
		return bmbh;
	}

	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 23)
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}


	@Column(name = "publisher", nullable = false, length = 4)
	public String getPublisher() {
		return publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	@Column(name = "publishercn", nullable = false, length = 20)
	public String getPublishercn() {
		return publishercn;
	}

	public void setPublishercn(String publishercn) {
		this.publishercn = publishercn;
	}

	@Column(name = "checkCode", nullable = true, length = 20)
	public String getCheckCode() {
		return checkCode;
	}

	public void setCheckCode(String checkCode) {
		this.checkCode = checkCode;
	}

	@Column(name = "tzdbh", nullable = false, length = 20)
	public String getTzdbh() {
		return tzdbh;
	}

	public void setTzdbh(String tzdbh) {
		this.tzdbh = tzdbh;
	}

	@Column(name = "cbsydsno", nullable = true, length = 20)
	public String getCbsydsno() {
		return cbsydsno;
	}

	public void setCbsydsno(String cbsydsno) {
		this.cbsydsno = cbsydsno;
	}

	@Column(name = "bsno", nullable = true, length = 20)
	public String getBsno() {
		return bsno;
	}

	public void setBsno(String bsno) {
		this.bsno = bsno;
	}

	@Column(name = "bname", nullable = true, length = 100)
	public String getBname() {
		return bname;
	}

	public void setBname(String bname) {
		this.bname = bname;
	}

	@Column(name = "isbn", nullable = true, length = 20)
	public String getIsbn() {
		return isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tzrq", nullable = true, length = 23)
	public Date getTzrq() {
		return tzrq;
	}

	public void setTzrq(Date tzrq) {
		this.tzrq = tzrq;
	}

	@Column(name = "yc", nullable = true, length = 20)
	public String getYc() {
		return yc;
	}

	public void setYc(String yc) {
		this.yc = yc;
	}

	@Column(name = "price", precision = 18, scale = 2)
	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "tzdys", nullable = true)
	public int getTzdys() {
		return tzdys;
	}

	public void setTzdys(int tzdys) {
		this.tzdys = tzdys;
	}

	@Column(name = "yangshu", nullable = true)
	public int getYangshu() {
		return yangshu;
	}

	public void setYangshu(int yangshu) {
		this.yangshu = yangshu;
	}

	@Column(name = "zongym", nullable = true)
	public int getZongym() {
		return zongym;
	}

	public void setZongym(int zongym) {
		this.zongym = zongym;
	}

	@Column(name = "cbzs", nullable = true)
	public int getCbzs() {
		return cbzs;
	}

	public void setCbzs(int cbzs) {
		this.cbzs = cbzs;
	}

	@Column(name = "kbgg", nullable = true, length = 20)
	public String getKbgg() {
		return kbgg;
	}

	public void setKbgg(String kbgg) {
		this.kbgg = kbgg;
	}

	@Column(name = "cpgg", nullable = true, length = 20)
	public String getCpgg() {
		return cpgg;
	}

	public void setCpgg(String cpgg) {
		this.cpgg = cpgg;
	}
	
	@Column(name = "dwyz", nullable = true)
	public BigDecimal getDwyz() {
		return dwyz;
	}

	public void setDwyz(BigDecimal dwyz) {
		this.dwyz = dwyz;
	}

	@Column(name = "zdr", nullable = true, length = 20)
	public String getZdr() {
		return zdr;
	}

	public void setZdr(String zdr) {
		this.zdr = zdr;
	}

	@Column(name = "zdfs", nullable = true, length = 20)
	public String getZdfs() {
		return zdfs;
	}

	public void setZdfs(String zdfs) {
		this.zdfs = zdfs;
	}

	@Column(name = "zzfs", nullable = true, length = 20)
	public String getZzfs() {
		return zzfs;
	}

	public void setZzfs(String zzfs) {
		this.zzfs = zzfs;
	}

	public String getSended() {
		return sended;
	}

	@Column(name = "sended", nullable = false, length = 1)
	public void setSended(String sended) {
		this.sended = sended;
	}

	public int getSendId() {
		return sendId;
	}

	@Column(name = "sendId")
	public void setSendId(int sendId) {
		this.sendId = sendId;
	}

	@Column(name = "sendName", length = 20)
	public String getSendName() {
		return sendName;
	}

	public void setSendName(String sendName) {
		this.sendName = sendName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sendTime", length = 23)
	public Date getSendTime() {
		return sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TFyd", cascade=CascadeType.ALL)
	public Set<TFydDet> getTFydDets() {
		return this.TFydDets;
	}

	public void setTFydDets(Set<TFydDet> TFydDets) {
		this.TFydDets = TFydDets;
	}
	
}
