package lnyswz.jxc.model;

import java.math.BigDecimal;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;

import javax.persistence.Table;

/**
 * TFydDet generated by hbm2java
 */
@Entity
@Table(name = "t_fyd_det")
public class TFydDet implements java.io.Serializable {

	private int id;
	private TFyd TFyd;
	private String tzdbh;
	private String cbsydsno;
	private int sno;
	private String xmdm;
	private String xmmc;
	private int xmys;
	private int amount;
	private int zzks;
	private int jsyz;
	private int seshu;
	private int seshu2;
	private String ysfs;
	private String pname;
	private String clbz;
	private String clkq;
	private String cldm;
	private String zzmc;
	private String zzgg;
	private String cllb;
	private String clweight;
	private String danjiadw;
	private BigDecimal sjyzl;
	private int jfl;
	private BigDecimal jfyzl;
	private int tiaojfs;
	private BigDecimal zzhjl;
	private BigDecimal danjia;
	private BigDecimal gongj;
	private int czl;
	private BigDecimal clton;

	public TFydDet() {
	}

	public TFydDet(int id, TFyd TFyd, String tzdbh, String cbsydsno, int sno, String xmdm, String xmmc, int xmys, int amount, int zzks, int jsyz,
			int seshu, int seshu2, String ysfs, String pname, String clbz, String clkq, String cldm, String zzmc, String zzgg, String cllb,
			String clweight, String danjiadw, BigDecimal sjyzl, int jfl, BigDecimal jfyzl, int tiaojfs, BigDecimal zzhjl, BigDecimal danjia, BigDecimal gongj, 
			int czl, BigDecimal clton) {
		this.id = id;
		this.TFyd = TFyd;
		this.tzdbh = tzdbh;
		this.cbsydsno = cbsydsno;
		this.sno = sno;
		this.xmdm = xmdm;
		this.xmmc = xmmc;
		this.xmys = xmys;
		this.amount = amount;
		this.zzks = zzks;
		this.jsyz = jsyz;
		this.seshu = seshu;
		this.seshu2 = seshu2;
		this.ysfs = ysfs;
		this.pname = pname;
		this.clbz = clbz;
		this.clkq = clkq;
		this.cldm = cldm;
		this.zzmc = zzmc;
		this.zzgg = zzgg;
		this.cllb = cllb;
		this.clweight = clweight;
		this.danjiadw = danjiadw;
		this.sjyzl = sjyzl;
		this.jfl = jfl;
		this.jfyzl = jfyzl;
		this.tiaojfs = tiaojfs;
		this.zzhjl = zzhjl;
		this.danjia = danjia;
		this.gongj = gongj;
		this.czl = czl;
		this.clton = clton;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fydlsh")
	public TFyd getTFyd() {
		return this.TFyd;
	}

	public void setTFyd(TFyd TFyd) {
		this.TFyd = TFyd;
	}

	@Column(name = "tzdbh", nullable = false, length = 20)
	public String getTzdbh() {
		return tzdbh;
	}

	public void setTzdbh(String tzdbh) {
		this.tzdbh = tzdbh;
	}

	@Column(name = "cbsydsno", nullable = false, length = 20)
	public String getCbsydsno() {
		return cbsydsno;
	}

	public void setCbsydsno(String cbsydsno) {
		this.cbsydsno = cbsydsno;
	}

	@Column(name = "sno", nullable = false)
	public int getSno() {
		return sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "xmdm", nullable = false, length = 20)
	public String getXmdm() {
		return xmdm;
	}

	public void setXmdm(String xmdm) {
		this.xmdm = xmdm;
	}

	@Column(name = "xmmc", nullable = false, length = 20)
	public String getXmmc() {
		return xmmc;
	}

	public void setXmmc(String xmmc) {
		this.xmmc = xmmc;
	}

	@Column(name = "xmys", nullable = false)
	public int getXmys() {
		return xmys;
	}

	public void setXmys(int xmys) {
		this.xmys = xmys;
	}

	@Column(name = "amount", nullable = false)
	public int getAmount() {
		return amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	@Column(name = "zzks", nullable = false)
	public int getZzks() {
		return zzks;
	}

	public void setZzks(int zzks) {
		this.zzks = zzks;
	}

	@Column(name = "jsyz", nullable = false)
	public int getJsyz() {
		return jsyz;
	}

	public void setJsyz(int jsyz) {
		this.jsyz = jsyz;
	}

	@Column(name = "seshu", nullable = false)
	public int getSeshu() {
		return seshu;
	}

	public void setSeshu(int seshu) {
		this.seshu = seshu;
	}

	@Column(name = "seshu2", nullable = false)
	public int getSeshu2() {
		return seshu2;
	}

	public void setSeshu2(int seshu2) {
		this.seshu2 = seshu2;
	}

	@Column(name = "ysfs", nullable = false, length = 20)
	public String getYsfs() {
		return ysfs;
	}

	public void setYsfs(String ysfs) {
		this.ysfs = ysfs;
	}

	@Column(name = "pname", nullable = false, length = 50)
	public String getPname() {
		return pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	@Column(name = "clbz", nullable = false, length = 20)
	public String getClbz() {
		return clbz;
	}

	public void setClbz(String clbz) {
		this.clbz = clbz;
	}

	@Column(name = "clkq", nullable = false, length = 20)
	public String getClkq() {
		return clkq;
	}

	public void setClkq(String clkq) {
		this.clkq = clkq;
	}

	@Column(name = "cldm", nullable = false, length = 20)
	public String getCldm() {
		return cldm;
	}

	public void setCldm(String cldm) {
		this.cldm = cldm;
	}

	@Column(name = "zzmc", nullable = false, length = 50)
	public String getZzmc() {
		return zzmc;
	}

	public void setZzmc(String zzmc) {
		this.zzmc = zzmc;
	}

	@Column(name = "zzgg", nullable = false, length = 20)
	public String getZzgg() {
		return zzgg;
	}

	public void setZzgg(String zzgg) {
		this.zzgg = zzgg;
	}

	@Column(name = "cllb", nullable = false, length = 20)
	public String getCllb() {
		return cllb;
	}

	public void setCllb(String cllb) {
		this.cllb = cllb;
	}

	@Column(name = "clweight", nullable = false, length = 20)
	public String getClweight() {
		return clweight;
	}

	public void setClweight(String clweight) {
		this.clweight = clweight;
	}

	@Column(name = "danjiadw", nullable = false, length = 20)
	public String getDanjiadw() {
		return danjiadw;
	}

	public void setDanjiadw(String danjiadw) {
		this.danjiadw = danjiadw;
	}

	@Column(name = "sjyzl", precision = 18, scale = 3)
	public BigDecimal getSjyzl() {
		return sjyzl;
	}

	public void setSjyzl(BigDecimal sjyzl) {
		this.sjyzl = sjyzl;
	}

	@Column(name = "jfl", nullable = false)
	public int getJfl() {
		return jfl;
	}

	public void setJfl(int jfl) {
		this.jfl = jfl;
	}

	@Column(name = "jfyzl", precision = 18, scale = 3)
	public BigDecimal getJfyzl() {
		return jfyzl;
	}

	public void setJfyzl(BigDecimal jfyzl) {
		this.jfyzl = jfyzl;
	}

	@Column(name = "tiaojfs", nullable = false)
	public int getTiaojfs() {
		return tiaojfs;
	}

	public void setTiaojfs(int tiaojfs) {
		this.tiaojfs = tiaojfs;
	}

	@Column(name = "zzhjl", precision = 18, scale = 0)
	public BigDecimal getZzhjl() {
		return zzhjl;
	}

	public void setZzhjl(BigDecimal zzhjl) {
		this.zzhjl = zzhjl;
	}
	
	@Column(name = "danjia", precision = 18, scale = 2)
	public BigDecimal getDanjia() {
		return danjia;
	}

	public void setDanjia(BigDecimal danjia) {
		this.danjia = danjia;
	}

	@Column(name = "gongj", precision = 18, scale = 2)
	public BigDecimal getGongj() {
		return gongj;
	}

	public void setGongj(BigDecimal gongj) {
		this.gongj = gongj;
	}

	@Column(name = "czl", nullable = false)
	public int getCzl() {
		return czl;
	}

	public void setCzl(int czl) {
		this.czl = czl;
	}

	@Column(name = "clton", precision = 18, scale = 0)
	public BigDecimal getClton() {
		return clton;
	}

	public void setClton(BigDecimal clton) {
		this.clton = clton;
	}
}
