package lnyswz.jxc.model;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TGysDet generated by hbm2java
 */
@Entity
@Table(name = "t_gys_det")
public class TGysDet implements java.io.Serializable {

	private String id;
	private TGys TGys;
	private TDepartment TDepartment;
	private String lxr;
	private Integer sxzq;
	private BigDecimal sxje;

	public TGysDet() {
	}

	public TGysDet(String id, TGys TGys, TDepartment TDepartment) {
		this.id = id;
		this.TGys = TGys;
		this.TDepartment = TDepartment;
	}

	public TGysDet(String id, TGys TGys, TDepartment TDepartment, String lxr,
			Integer sxzq, BigDecimal sxje) {
		this.id = id;
		this.TGys = TGys;
		this.TDepartment = TDepartment;
		this.lxr = lxr;
		this.sxzq = sxzq;
		this.sxje = sxje;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gysbh", nullable = false)
	public TGys getTGys() {
		return this.TGys;
	}

	public void setTGys(TGys TGys) {
		this.TGys = TGys;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "depId", nullable = false)
	public TDepartment getTDepartment() {
		return TDepartment;
	}

	public void setTDepartment(TDepartment tDepartment) {
		TDepartment = tDepartment;
	}

	@Column(name = "lxr", length = 50)
	public String getLxr() {
		return this.lxr;
	}

	public void setLxr(String lxr) {
		this.lxr = lxr;
	}

	@Column(name = "sxzq")
	public Integer getSxzq() {
		return this.sxzq;
	}

	public void setSxzq(Integer sxzq) {
		this.sxzq = sxzq;
	}

	@Column(name = "sxje")
	public BigDecimal getSxje() {
		return this.sxje;
	}

	public void setSxje(BigDecimal sxje) {
		this.sxje = sxje;
	}

}
