package lnyswz.jxc.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * TGys generated by hbm2java
 */
@Entity
@Table(name = "t_gys")
public class TGys implements java.io.Serializable {

	private String gysbh;
	private String gysmc;
	private String dzdh;
	private String khh;
	private String sh;
	private String fr;
	private Set<TGysDet> TGysDets = new HashSet<TGysDet>(0);

	public TGys() {
	}

	public TGys(String gysbh, String gysmc, String dzdh, String khh, String sh,
			String fr, Set<TGysDet> TGysDets) {
		this.gysbh = gysbh;
		this.gysmc = gysmc;
		this.dzdh = dzdh;
		this.khh = khh;
		this.sh = sh;
		this.fr = fr;
		this.TGysDets = TGysDets;
	}

	@Id
	@Column(name = "gysbh", unique = true, nullable = false, length = 8)
	public String getGysbh() {
		return this.gysbh;
	}

	public void setGysbh(String gysbh) {
		this.gysbh = gysbh;
	}

	@Column(name = "gysmc", nullable = false, length = 100)
	public String getGysmc() {
		return this.gysmc;
	}

	public void setGysmc(String gysmc) {
		this.gysmc = gysmc;
	}

	@Column(name = "dzdh", length = 200)
	public String getDzdh() {
		return this.dzdh;
	}

	public void setDzdh(String dzdh) {
		this.dzdh = dzdh;
	}

	@Column(name = "khh", length = 200)
	public String getKhh() {
		return this.khh;
	}

	public void setKhh(String khh) {
		this.khh = khh;
	}

	@Column(name = "sh", length = 15)
	public String getSh() {
		return this.sh;
	}

	public void setSh(String sh) {
		this.sh = sh;
	}

	@Column(name = "fr", length = 20)
	public String getFr() {
		return this.fr;
	}

	public void setFr(String fr) {
		this.fr = fr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGys",cascade=CascadeType.ALL)
	public Set<TGysDet> getTGysDets() {
		return this.TGysDets;
	}

	public void setTGysDets(Set<TGysDet> TGysDets) {
		this.TGysDets = TGysDets;
	}
	
}
