package lnyswz.jxc.model;

import java.math.BigDecimal;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * THkKp generated by hbm2java
 */
@Entity
@Table(name = "t_xshk_xskp")
public class THkKp implements java.io.Serializable {
	private int id;
	private String xskplsh;
	private BigDecimal hkje;
	private String isYf;
	private TXshk TXshk;
	
	public THkKp() {
	}

	public THkKp(int id, String xskplsh, BigDecimal hkje, String isYf, TXshk TXshk) {
		this.id = id;
		this.xskplsh = xskplsh;
		this.hkje = hkje;
		this.isYf = isYf;
		this.TXshk = TXshk;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "xskplsh", nullable = false, length = 12)
	public String getXskplsh() {
		return this.xskplsh;
	}

	public void setXskplsh(String xskplsh) {
		this.xskplsh = xskplsh;
	}

	@Column(name = "hkje", precision = 18, scale = 4)
	public BigDecimal getHkje() {
		return this.hkje;
	}

	public void setHkje(BigDecimal hkje) {
		this.hkje = hkje;
	}

	@Column(name = "isYf", nullable = false, length = 1)
	public String getIsYf() {
		return this.isYf;
	}

	public void setIsYf(String isYf) {
		this.isYf = isYf;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "xshklsh", nullable = false)
	public TXshk getTXshk() {
		return this.TXshk;
	}

	public void setTXshk(TXshk TXshk) {
		this.TXshk = TXshk;
	}
}
