package lnyswz.jxc.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * THw generated by hbm2java
 */
@Entity
@Table(name = "t_hw")
public class THw implements java.io.Serializable {

	private String id;
	private TCk TCk;
	private String hwmc;

	public THw() {
	}

	public THw(String id) {
		this.id = id;
	}

	public THw(String id, TCk TCk, String hwmc) {
		this.id = id;
		this.TCk = TCk;
		this.hwmc = hwmc;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 2)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ckId")
	public TCk getTCk() {
		return this.TCk;
	}

	public void setTCk(TCk TCk) {
		this.TCk = TCk;
	}

	@Column(name = "hwmc", unique = true, length = 50)
	public String getHwmc() {
		return this.hwmc;
	}

	public void setHwmc(String hwmc) {
		this.hwmc = hwmc;
	}

}
