package lnyswz.jxc.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TJldw generated by hbm2java
 */
@Entity
@Table(name = "t_jldw")
public class TJldw implements java.io.Serializable {

	private String id;
	private String jldwmc;

	public TJldw() {
	}

	public TJldw(String id) {
		this.id = id;
	}

	public TJldw(String id, String jldwmc) {
		this.id = id;
		this.jldwmc = jldwmc;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 2)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "jldwmc", unique = true, length = 50)
	public String getJldwmc() {
		return this.jldwmc;
	}

	public void setJldwmc(String jldwmc) {
		this.jldwmc = jldwmc;
	}

}
