package lnyswz.jxc.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TJsfs generated by hbm2java
 */
@Entity
@Table(name = "t_jsfs")
public class TJsfs implements java.io.Serializable {

	private String id;
	private String jsmc;

	public TJsfs() {
	}

	public TJsfs(String id) {
		this.id = id;
	}

	public TJsfs(String id, String jsmc) {
		this.id = id;
		this.jsmc = jsmc;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 2)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "jsmc", unique = true, length = 50)
	public String getJsmc() {
		return this.jsmc;
	}

	public void setJsmc(String jsmc) {
		this.jsmc = jsmc;
	}

}
