package lnyswz.jxc.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * TSp generated by hbm2java
 */
@Entity
@Table(name = "t_kfbg_sp_mx")
public class TKfbgSp implements java.io.Serializable {

	private int id;
	private String spbh;
	private String spmc;
	private String spcd;
	private String sppp;
	private String spbz;
	private String sppc;
	private String zdwmc;
	private String cdwmc;
	private String fdwmc;
	private BigDecimal zrksl;
	private BigDecimal zcksl;
	private BigDecimal frksl;
	private BigDecimal fcksl;
	private Date createTime;
	private String type;
	private String khmc;
	private String lsh;
	private String bmmc;
	private String bmbh;
	

	


	public TKfbgSp() {
	}


	public TKfbgSp(int id,String spbh, String spmc, String spcd, String sppp, String spbz,String sppc,
			String zdwmc,String cdwmc,String fdwmc,BigDecimal zrksl,BigDecimal zcksl,BigDecimal frksl,BigDecimal fcksl,
			Date createTime,String type,String khmc,String lsh,String bmmc,String bmbh) {
		this.id = id;
		this.spbh = spbh;
		this.spmc = spmc;
		this.spcd = spcd;
		this.sppp = sppp;
		this.spbz = spbz;
		this.sppc = sppc;
		this.zdwmc = zdwmc;
		this.cdwmc = cdwmc;
		this.fdwmc = fdwmc;
		this.zrksl = zrksl;
		this.zcksl = zcksl;
		this.frksl = frksl;
		this.fcksl = fcksl;
		this.createTime = createTime;
		this.type = type;
		this.khmc = khmc;
		this.lsh = lsh;
		this.bmmc = bmmc;
		this.bmbh = bmbh;
		
		
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return id;
	}


	public void setId(int id) {
		this.id = id;
	}
	

	@Column(name = "spbh", nullable = false, length = 100)
	public String getSpbh() {
		return this.spbh;
	}
	
	public void setSpbh(String spbh) {
		this.spbh = spbh;
	}
	
	@Column(name = "spmc", nullable = false, length = 100)
	public String getSpmc() {
		return spmc;
	}


	public void setSpmc(String spmc) {
		this.spmc = spmc;
	}

	@Column(name = "spcd", nullable = true, length = 100)
	public String getSpcd() {
		return spcd;
	}


	public void setSpcd(String spcd) {
		this.spcd = spcd;
	}

	@Column(name = "sppp", nullable = true, length = 100)
	public String getSppp() {
		return sppp;
	}


	public void setSppp(String sppp) {
		this.sppp = sppp;
	}


	@Column(name = "spbz", nullable = true, length = 100)
	public String getSpbz() {
		return spbz;
	}


	public void setSpbz(String spbz) {
		this.spbz = spbz;
	}

	@Column(name = "sppc", nullable = true, length = 100)
	public String getSppc() {
		return sppc;
	}


	public void setSppc(String sppc) {
		this.sppc = sppc;
	}


	@Column(name = "zdwmc", nullable = true, length = 100)
	public String getZdwmc() {
		return zdwmc;
	}


	public void setZdwmc(String zdwmc) {
		this.zdwmc = zdwmc;
	}


	@Column(name = "cdwmc", nullable = true, length = 100)
	public String getCdwmc() {
		return cdwmc;
	}


	public void setCdwmc(String cdwmc) {
		this.cdwmc = cdwmc;
	}
	
	@Column(name = "fdwmc", nullable = true, length = 100)
	public String getFdwmc() {
		return fdwmc;
	}


	public void setFdwmc(String fdwmc) {
		this.fdwmc = fdwmc;
	}

	@Column(name = "zrksl", nullable = false, precision = 18, scale = 6)
	public BigDecimal getZrksl() {
		return zrksl;
	}


	public void setZrksl(BigDecimal zrksl) {
		this.zrksl = zrksl;
	}


	@Column(name = "zcksl", nullable = false, precision = 18, scale = 6)
	public BigDecimal getZcksl() {
		return zcksl;
	}


	public void setZcksl(BigDecimal zcksl) {
		this.zcksl = zcksl;
	}
	
	@Column(name = "frksl", nullable = false, precision = 18, scale = 6)
	public BigDecimal getFrksl() {
		return frksl;
	}


	public void setFrksl(BigDecimal frksl) {
		this.frksl = frksl;
	}

	@Column(name = "fcksl", nullable = false, precision = 18, scale = 6)
	public BigDecimal getFcksl() {
		return fcksl;
	}


	public void setFcksl(BigDecimal fcksl) {
		this.fcksl = fcksl;
	}


	@Column(name = "createTime", nullable = true, length = 100)
	public Date getCreateTime() {
		return createTime;
	}


	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "type", nullable = true, length = 100)
	public String getType() {
		return type;
	}


	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "khmc", nullable = true, length = 100)
	public String getKhmc() {
		return khmc;
	}


	public void setKhmc(String khmc) {
		this.khmc = khmc;
	}

	@Column(name = "lsh", nullable = true, length = 12)
	public String getLsh() {
		return lsh;
	}


	public void setLsh(String lsh) {
		this.lsh = lsh;
	}

	@Column(name = "bmmc", nullable = true, length = 10)
	public String getBmmc() {
		return bmmc;
	}


	public void setBmmc(String bmmc) {
		this.bmmc = bmmc;
	}

	@Column(name = "bmbh", nullable = true, length = 2)

	public String getBmbh() {
		return bmbh;
	}


	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}

	

	
}
