package lnyswz.jxc.model;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * TSp generated by hbm2java
 */
@Entity
@Table(name = "t_kfbg_sp_zz")
public class TKfbgSpZz implements java.io.Serializable {

	private int	id;
	private String spbh;
	private String spmc;
	private String spcd;
	private String sppp;
	private String spbz;
	private String sppc;
	private String zdwmc;
	private String cdwmc;
	private String fdwmc;
	private BigDecimal zrksl;
	private BigDecimal zcksl;
	private BigDecimal frksl;
	private BigDecimal fcksl;
	private BigDecimal zqcsl;
	private BigDecimal fqcsl;
	private BigDecimal zhxs;
	private BigDecimal zwdzy;
	private BigDecimal zjc;
	private BigDecimal fwdzy;
	private BigDecimal fjc;
	private BigDecimal zNoBm;
	private BigDecimal fNoBm;
	

	


	public TKfbgSpZz() {
	}


	public TKfbgSpZz(int id,String spbh, String spmc, String spcd, String sppp, String spbz,String sppc,
			String zdwmc,String cdwmc,String fdwmc,BigDecimal zrksl,BigDecimal zcksl,BigDecimal frksl,BigDecimal fcksl,BigDecimal zqcsl,BigDecimal fqcsl,BigDecimal zhxs,
			BigDecimal zwdzy,BigDecimal zjc,BigDecimal fwdzy,BigDecimal fjc,BigDecimal zNoBm, BigDecimal fNoBm) {
		this.id = id;
		this.spbh = spbh;
		this.spmc = spmc;
		this.spcd = spcd;
		this.sppp = sppp;
		this.spbz = spbz;
		this.sppc = sppc;
		this.zdwmc = zdwmc;
		this.cdwmc = cdwmc;
		this.fdwmc = fdwmc;
		this.zrksl = zrksl;
		this.zcksl = zcksl;
		this.frksl = frksl;
		this.fcksl = fcksl;
		this.zqcsl = zqcsl;
		this.fqcsl = fqcsl;
		this.zhxs = zhxs;
		this.zwdzy = zwdzy;
		this.zjc = zjc;
		this.fwdzy = fwdzy;
		this.fjc = fjc;
		this.zNoBm = zNoBm;
		this.fNoBm = fNoBm;
		
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return id;
	}


	public void setId(int id) {
		this.id = id;
	}

	
	@Column(name = "spbh", nullable = false, length = 100)
	public String getSpbh() {
		return this.spbh;
	}

	public void setSpbh(String spbh) {
		this.spbh = spbh;
	}
	
	@Column(name = "spmc", nullable = false, length = 100)
	public String getSpmc() {
		return spmc;
	}


	public void setSpmc(String spmc) {
		this.spmc = spmc;
	}

	@Column(name = "spcd", nullable = true, length = 100)
	public String getSpcd() {
		return spcd;
	}


	public void setSpcd(String spcd) {
		this.spcd = spcd;
	}

	@Column(name = "sppp", nullable = true, length = 100)
	public String getSppp() {
		return sppp;
	}


	public void setSppp(String sppp) {
		this.sppp = sppp;
	}

	@Column(name = "spbz", nullable = true, length = 100)
	public String getSpbz() {
		return spbz;
	}


	public void setSpbz(String spbz) {
		this.spbz = spbz;
	}

	@Column(name = "sppc", nullable = true, length = 100)
	public String getSppc() {
		return sppc;
	}


	public void setSppc(String sppc) {
		this.sppc = sppc;
	}

	@Column(name = "zdwmc", nullable = true, length = 100)
	public String getZdwmc() {
		return zdwmc;
	}


	public void setZdwmc(String zdwmc) {
		this.zdwmc = zdwmc;
	}

	@Column(name = "cdwmc", nullable = true, length = 100)
	public String getCdwmc() {
		return cdwmc;
	}


	public void setCdwmc(String cdwmc) {
		this.cdwmc = cdwmc;
	}


	@Column(name = "fdwmc", nullable = true, length = 100)
	public String getFdwmc() {
		return fdwmc;
	}

	public void setFdwmc(String fdwmc) {
		this.fdwmc = fdwmc;
	}
	
	@Column(name = "zrksl", nullable = false, precision = 18, scale = 6)
	public BigDecimal getZrksl() {
		return zrksl;
	}


	public void setZrksl(BigDecimal zrksl) {
		this.zrksl = zrksl;
	}

	@Column(name = "zcksl", nullable = false, precision = 18, scale = 6)
	public BigDecimal getZcksl() {
		return zcksl;
	}


	public void setZcksl(BigDecimal zcksl) {
		this.zcksl = zcksl;
	}

	@Column(name = "frksl", nullable = false, precision = 18, scale = 6)
	public BigDecimal getFrksl() {
		return frksl;
	}


	public void setFrksl(BigDecimal frksl) {
		this.frksl = frksl;
	}

	@Column(name = "fcksl", nullable = false, precision = 18, scale = 6)
	public BigDecimal getFcksl() {
		return fcksl;
	}


	public void setFcksl(BigDecimal fcksl) {
		this.fcksl = fcksl;
	}

	@Column(name = "zqcsl", nullable = false, precision = 18, scale = 6)
	public BigDecimal getZqcsl() {
		return zqcsl;
	}


	public void setZqcsl(BigDecimal zqcsl) {
		this.zqcsl = zqcsl;
	}

	@Column(name = "fqcsl", nullable = false, precision = 18, scale = 6)
	public BigDecimal getFqcsl() {
		return fqcsl;
	}


	public void setFqcsl(BigDecimal fqcsl) {
		this.fqcsl = fqcsl;
	}

	@Column(name = "zhxs", nullable = false, precision = 18, scale = 6)
	public BigDecimal getZhxs() {
		return zhxs;
	}


	public void setZhxs(BigDecimal zhxs) {
		this.zhxs = zhxs;
	}

	@Column(name = "zwdzy", nullable = true, precision = 18, scale = 6)
	public BigDecimal getZwdzy() {
		return zwdzy;
	}


	public void setZwdzy(BigDecimal zwdzy) {
		this.zwdzy = zwdzy;
	}


	@Column(name = "zjc", nullable = true, precision = 18, scale = 6)
	public BigDecimal getZjc() {
		return zjc;
	}


	public void setZjc(BigDecimal zjc) {
		this.zjc = zjc;
	}


	@Column(name = "fwdzy", nullable = true, precision = 18, scale = 6)
	public BigDecimal getFwdzy() {
		return fwdzy;
	}


	public void setFwdzy(BigDecimal fwdzy) {
		this.fwdzy = fwdzy;
	}

	@Column(name = "fjc", nullable = true, precision = 18, scale = 6)
	public BigDecimal getFjc() {
		return fjc;
	}


	public void setFjc(BigDecimal fjc) {
		this.fjc = fjc;
	}

	@Column(name = "zNoBm", nullable = true, precision = 18, scale = 6)
	public BigDecimal getZNoBm() {
		return zNoBm;
	}


	public void setZNoBm(BigDecimal zNoBm) {
		this.zNoBm = zNoBm;
	}

	@Column(name = "fNoBm", nullable = true, precision = 18, scale = 6)
	public BigDecimal getFNoBm() {
		return fNoBm;
	}


	public void setFNoBm(BigDecimal fNoBm) {
		this.fNoBm = fNoBm;
	}

	
	
//	@Column(name = "zhxs", nullable = true, precision = 18, scale = 6)
//	public BigDecimal getZhxs() {
//		return zhxs;
//	}
//
//
//	public void setZhxs(BigDecimal zhxs) {
//		this.zhxs = zhxs;
//	}



	

	
}
