package lnyswz.jxc.model;

import javax.persistence.*;
import java.math.BigDecimal;

/**
 * TKfdbDet generated by hbm2java
 */
@Entity
@Table(name = "t_kfdb_det")
public class TKfdbDet implements java.io.Serializable {

	private int id;
	private String spbh;
	private String spmc;
	private String spcd;
	private String sppp;
	private String spbz;
	private String zjldwId;
	private String zjldwmc;
	private String cjldwId;
	private String cjldwmc;
	private BigDecimal zhxs;
	private TKfdb TKfdb;
	private String sppc;
	private BigDecimal zdwsl;
	private BigDecimal cdwsl;

	public TKfdbDet() {
	}

	public TKfdbDet(int id, String spbh, String spmc, String spcd, String sppp, String spbz, String zjldwId, String zjldwmc,
                    String cjldwId, String cjldwmc, BigDecimal zhxs, TKfdb TKfdb, String sppc, BigDecimal zdwsl,
                    BigDecimal cdwsl) {
		this.id = id;
		this.spbh = spbh;
		this.spmc = spmc;
		this.spcd = spcd;
		this.sppp = sppp;
		this.spbz = spbz;
		this.zjldwId = zjldwId;
		this.zjldwmc = zjldwmc;
		this.cjldwId = cjldwId;
		this.cjldwmc = cjldwmc;
		this.zhxs = zhxs;
		this.TKfdb = TKfdb;
		this.sppc = sppc;
		this.zdwsl = zdwsl;
		this.cdwsl = cdwsl;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "spbh", nullable = false, length = 7)
	public String getSpbh() {
		return spbh;
	}

	public void setSpbh(String spbh) {
		this.spbh = spbh;
	}

	@Column(name = "spmc", nullable = false, length = 100)
	public String getSpmc() {
		return spmc;
	}

	public void setSpmc(String spmc) {
		this.spmc = spmc;
	}

	@Column(name = "spcd", nullable = false, length = 20)
	public String getSpcd() {
		return spcd;
	}

	public void setSpcd(String spcd) {
		this.spcd = spcd;
	}

	@Column(name = "sppp", length = 20)
	public String getSppp() {
		return sppp;
	}

	public void setSppp(String sppp) {
		this.sppp = sppp;
	}

	@Column(name = "spbz", length = 20)
	public String getSpbz() {
		return spbz;
	}

	public void setSpbz(String spbz) {
		this.spbz = spbz;
	}

	@Column(name = "zjldwId", nullable = false, length = 2)
	public String getZjldwId() {
		return zjldwId;
	}

	public void setZjldwId(String zjldwId) {
		this.zjldwId = zjldwId;
	}

	@Column(name = "zjldwmc", nullable = false, length = 20)
	public String getZjldwmc() {
		return zjldwmc;
	}

	public void setZjldwmc(String zjldwmc) {
		this.zjldwmc = zjldwmc;
	}

	@Column(name = "cjldwId", length = 2)
	public String getCjldwId() {
		return cjldwId;
	}

	public void setCjldwId(String cjldwId) {
		this.cjldwId = cjldwId;
	}

	@Column(name = "cjldwmc", length = 20)
	public String getCjldwmc() {
		return cjldwmc;
	}

	public void setCjldwmc(String cjldwmc) {
		this.cjldwmc = cjldwmc;
	}

	@Column(name = "zhxs", nullable = false, precision = 18, scale = 3)
	public BigDecimal getZhxs() {
		return zhxs;
	}

	public void setZhxs(BigDecimal zhxs) {
		this.zhxs = zhxs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "kfdblsh")
	public TKfdb getTKfdb() {
		return this.TKfdb;
	}

	public void setTKfdb(TKfdb TKfdb) {
		this.TKfdb = TKfdb;
	}

	@Column(name = "sppc", nullable = false, length = 10)
	public String getSppc() {
		return sppc;
	}

	public void setSppc(String sppc) {
		this.sppc = sppc;
	}

	@Column(name = "zdwsl", precision = 18, scale = 3)
	public BigDecimal getZdwsl() {
		return this.zdwsl;
	}

	public void setZdwsl(BigDecimal zdwsl) {
		this.zdwsl = zdwsl;
	}

	@Column(name = "cdwsl", precision = 18, scale = 3)
	public BigDecimal getCdwsl() {
		return this.cdwsl;
	}

	public void setCdwsl(BigDecimal cdwsl) {
		this.cdwsl = cdwsl;
	}
	
}
