package lnyswz.jxc.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * TKfpd generated by hbm2java
 */
@Entity
@Table(name = "t_kfpd")
public class TKfpd implements java.io.Serializable {

	private String kfpdlsh;
	private Date createTime;
	private int createId;
	private String createName;
	private String bmbh;
	private String bmmc;
	private String pdlxId;
	private String pdlxmc;
	private String ckId;
	private String ckmc;
	private String mc;
	private String bz;
	private String cjKfpdlsh;
	private String isCj;
	private Date cjTime;
	private Integer cjId;
	private String cjName;
	private Set<TKfpdDet> TKfpdDets = new HashSet<TKfpdDet>(0);
	
	private TYwpd TYwpd;
	
	public TKfpd() {
	}

	public TKfpd(String kfpdlsh, int createId, Date createTime,  String createName, String bmbh, String bmmc,
			String mc, String pdlxId, String pdlxmc, String ckId, String ckmc, String bz,
			String isCj, Date cjTime, Integer cjId, String cjName, Set<TKfpdDet> TKfpdDets, TYwpd TYwpd) {
		this.kfpdlsh = kfpdlsh;
		this.createTime = createTime;
		this.createId = createId;
		this.createName = createName;
		this.bmbh = bmbh;
		this.bmmc = bmmc;
		this.pdlxId = pdlxId;
		this.pdlxmc = pdlxmc;
		this.ckId = ckId;
		this.ckmc = ckmc;
		this.mc = mc;
		this.bz = bz;
		this.isCj = isCj;
		this.cjId = cjId;
		this.cjTime = cjTime;
		this.cjName = cjName;
		this.TKfpdDets = TKfpdDets;
		this.TYwpd = TYwpd;
	}

	@Id
	@Column(name = "kfpdlsh", unique = true, nullable = false, length = 12)
	public String getKfpdlsh() {
		return this.kfpdlsh;
	}

	public void setKfpdlsh(String kfpdlsh) {
		this.kfpdlsh = kfpdlsh;
	}

	@Column(name = "createId", nullable = false)
	public int getCreateId() {
		return this.createId;
	}
	
	public void setCreateId(int createId) {
		this.createId = createId;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 23)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createName", nullable = false, length = 20)
	public String getCreateName() {
		return createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	@Column(name = "bmbh", nullable = false, length = 2)
	public String getBmbh() {
		return this.bmbh;
	}

	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}

	@Column(name = "bmmc", nullable = false, length = 20)
	public String getBmmc() {
		return bmmc;
	}

	public void setBmmc(String bmmc) {
		this.bmmc = bmmc;
	}

	@Column(name = "mc", nullable = false, length = 100)
	public String getMc() {
		return mc;
	}

	public void setMc(String mc) {
		this.mc = mc;
	}

	@Column(name = "pdlxId", nullable = false, length = 2)
	public String getPdlxId() {
		return this.pdlxId;
	}

	public void setPdlxId(String pdlxId) {
		this.pdlxId = pdlxId;
	}

	@Column(name = "pdlxmc", nullable = false, length = 20)
	public String getPdlxmc() {
		return pdlxmc;
	}

	public void setPdlxmc(String pdlxmc) {
		this.pdlxmc = pdlxmc;
	}

	@Column(name = "ckId", nullable = false, length = 2)
	public String getCkId() {
		return ckId;
	}

	public void setCkId(String ckId) {
		this.ckId = ckId;
	}

	@Column(name = "ckmc", nullable = false, length = 20)
	public String getCkmc() {
		return ckmc;
	}

	public void setCkmc(String ckmc) {
		this.ckmc = ckmc;
	}

	@Column(name = "bz", length = 100)
	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	@Column(name = "cjKfpdlsh", length = 12)
	public String getCjKfpdlsh() {
		return cjKfpdlsh;
	}

	public void setCjKfpdlsh(String cjKfpdlsh) {
		this.cjKfpdlsh = cjKfpdlsh;
	}

	@Column(name = "isCj", nullable = false, length = 1)
	public String getIsCj() {
		return this.isCj;
	}

	public void setIsCj(String isCj) {
		this.isCj = isCj;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cjTime", length = 23)
	public Date getCjTime() {
		return this.cjTime;
	}

	public void setCjTime(Date cjTime) {
		this.cjTime = cjTime;
	}

	@Column(name = "cjName", length = 20)
	public String getCjName() {
		return cjName;
	}

	public void setCjName(String cjName) {
		this.cjName = cjName;
	}

	@Column(name = "cjId")
	public Integer getCjId() {
		return this.cjId;
	}

	public void setCjId(Integer cjId) {
		this.cjId = cjId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TKfpd", cascade=CascadeType.ALL)
	public Set<TKfpdDet> getTKfpdDets() {
		return this.TKfpdDets;
	}

	public void setTKfpdDets(Set<TKfpdDet> TKfpdDets) {
		this.TKfpdDets = TKfpdDets;
	}

	@OneToOne(mappedBy="TKfpd", fetch = FetchType.LAZY)
	@Fetch(FetchMode.JOIN)
	public TYwpd getTYwpd() {
		return TYwpd;
	}

	public void setTYwpd(TYwpd tYwpd) {
		TYwpd = tYwpd;
	}
	
}
