package lnyswz.jxc.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TKfrk generated by hbm2java
 */
@Entity
@Table(name = "t_kfrk")
public class TKfrk implements java.io.Serializable {

	private String kfrklsh;
	private Date createTime;
	private int createId;
	private String createName;
	private String bmbh;
	private String bmmc;
	private String gysbh;
	private String gysmc;
	private String ckId;
	private String ckmc;
	private String shry;
	private String ch;
	private String zjh;
	private String bz;
	private String cjKfrklsh;
	private String isCj;
	private Date cjTime;
	private Integer cjId;
	private String cjName;
	
	private Set<TKfrkDet> TKfrkDets = new HashSet<TKfrkDet>(0);
	private Set<TCgjhDet> TCgjhs = new HashSet<TCgjhDet>(0);
	private TYwrk TYwrk;
	
	public TKfrk() {
	}

	public TKfrk(String kfrklsh, Date createTime, int createId, String createName, String bmbh, String bmmc, String gysbh, String gysmc,
			String ckId, String ckmc, String shry, String ch, String zjh, String bz, String cjKfrklsh, String isCj, Date cjTime, Integer cjId, String cjName,
			Set<TKfrkDet> TKfrkDets, Set<TCgjhDet> TCgjhs, TYwrk TYwrk) {
		this.kfrklsh = kfrklsh;
		this.createTime = createTime;
		this.createId = createId;
		this.createName = createName;
		this.bmbh = bmbh;
		this.bmmc = bmmc;
		this.gysbh = gysbh;
		this.gysmc = gysmc;
		this.ckId = ckId;
		this.ckmc = ckmc;
		this.shry = shry;
		this.ch = ch;
		this.zjh = zjh;
		this.bz = bz;
		this.cjKfrklsh = cjKfrklsh;
		this.isCj = isCj;
		this.cjTime = cjTime;
		this.cjId = cjId;
		this.cjName = cjName;
		this.TKfrkDets = TKfrkDets;
		this.TCgjhs = TCgjhs;
		this.TYwrk = TYwrk;
	}

	@Id
	@Column(name = "kfrklsh", unique = true, nullable = false, length = 12)
	public String getKfrklsh() {
		return this.kfrklsh;
	}

	public void setKfrklsh(String kfrklsh) {
		this.kfrklsh = kfrklsh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 23)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createId", nullable = false)
	public int getCreateId() {
		return this.createId;
	}

	public void setCreateId(int createId) {
		this.createId = createId;
	}

	@Column(name = "createName", nullable = false, length = 20)
	public String getCreateName() {
		return createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	@Column(name = "bmbh", nullable = false, length = 2)
	public String getBmbh() {
		return this.bmbh;
	}

	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}

	@Column(name = "bmmc", nullable = false, length = 20)
	public String getBmmc() {
		return bmmc;
	}

	public void setBmmc(String bmmc) {
		this.bmmc = bmmc;
	}

	@Column(name = "gysbh", nullable = false, length = 8)
	public String getGysbh() {
		return gysbh;
	}

	public void setGysbh(String gysbh) {
		this.gysbh = gysbh;
	}

	@Column(name = "gysmc", nullable = false, length = 100)
	public String getGysmc() {
		return gysmc;
	}

	public void setGysmc(String gysmc) {
		this.gysmc = gysmc;
	}

	@Column(name = "ckId", nullable = false, length = 2)
	public String getCkId() {
		return ckId;
	}

	public void setCkId(String ckId) {
		this.ckId = ckId;
	}

	@Column(name = "ckmc", nullable = false, length = 20)
	public String getCkmc() {
		return ckmc;
	}

	public void setCkmc(String ckmc) {
		this.ckmc = ckmc;
	}

	@Column(name = "shry", length = 20)
	public String getShry() {
		return shry;
	}

	public void setShry(String shry) {
		this.shry = shry;
	}

	@Column(name = "ch", length = 20)
	public String getCh() {
		return ch;
	}

	public void setCh(String ch) {
		this.ch = ch;
	}

	@Column(name = "zjh", length = 20)
	public String getZjh() {
		return zjh;
	}

	public void setZjh(String zjh) {
		this.zjh = zjh;
	}

	@Column(name = "bz", length = 50)
	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	@Column(name = "cjKfrklsh", nullable = true, length = 12)
	public String getCjKfrklsh() {
		return cjKfrklsh;
	}

	public void setCjKfrklsh(String cjKfrklsh) {
		this.cjKfrklsh = cjKfrklsh;
	}

	@Column(name = "isCj", length = 1)
	public String getIsCj() {
		return this.isCj;
	}

	public void setIsCj(String isCj) {
		this.isCj = isCj;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cjTime", length = 23)
	public Date getCjTime() {
		return this.cjTime;
	}

	public void setCjTime(Date cjTime) {
		this.cjTime = cjTime;
	}

	@Column(name = "cjId")
	public Integer getCjId() {
		return this.cjId;
	}

	public void setCjId(Integer cjId) {
		this.cjId = cjId;
	}

	@Column(name = "cjName", length = 20)
	public String getCjName() {
		return cjName;
	}

	public void setCjName(String cjName) {
		this.cjName = cjName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TKfrk", cascade=CascadeType.ALL)
	public Set<TKfrkDet> getTKfrkDets() {
		return this.TKfrkDets;
	}

	public void setTKfrkDets(Set<TKfrkDet> TKfrkDets) {
		this.TKfrkDets = TKfrkDets;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_cgjh_kfrk", joinColumns = { @JoinColumn(name = "kfrklsh", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "cgjhdetId", nullable = false, updatable = false) })
	public Set<TCgjhDet> getTCgjhs() {
		return this.TCgjhs;
	}

	public void setTCgjhs(Set<TCgjhDet> TCgjhs) {
		this.TCgjhs = TCgjhs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ywrklsh")
	public TYwrk getTYwrk() {
		return TYwrk;
	}

	public void setTYwrk(TYwrk tYwrk) {
		TYwrk = tYwrk;
	}

}
