package lnyswz.jxc.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TKh generated by hbm2java
 */
@Entity
@Table(name = "t_kh")
public class TKh implements java.io.Serializable {

	private String khbh;
	private String khmc;
	private String dzdh;
	private String khh;
	private String sh;
	private String fr;
	private String address;
	private String dist;
	private String isNsr;
	private Set<TKhDet> TKhDets = new HashSet<TKhDet>(0);

	public TKh() {
	}

	public TKh(String khbh, String khmc, String dzdh, String khh,
			String sh, String fr, String address, String dist, String isNsr, Set<TKhDet> TKhDets) {
		this.khbh = khbh;
		this.khmc = khmc;
		this.dzdh = dzdh;
		this.khh = khh;
		this.sh = sh;
		this.fr = fr;
		this.address = address;
		this.dist = dist;
		this.isNsr = isNsr;
		this.TKhDets = TKhDets;
	}

	@Id
	@Column(name = "khbh", unique = true, nullable = false, length = 8)
	public String getKhbh() {
		return this.khbh;
	}

	public void setKhbh(String khbh) {
		this.khbh = khbh;
	}

	@Column(name = "khmc", nullable = false, length = 100)
	public String getKhmc() {
		return this.khmc;
	}

	public void setKhmc(String khmc) {
		this.khmc = khmc;
	}

	@Column(name = "dzdh", length = 200)
	public String getDzdh() {
		return this.dzdh;
	}

	public void setDzdh(String dzdh) {
		this.dzdh = dzdh;
	}

	@Column(name = "khh", length = 200)
	public String getKhh() {
		return this.khh;
	}

	public void setKhh(String khh) {
		this.khh = khh;
	}

	@Column(name = "sh", length = 20)
	public String getSh() {
		return this.sh;
	}

	public void setSh(String sh) {
		this.sh = sh;
	}

	@Column(name = "fr", length = 20)
	public String getFr() {
		return this.fr;
	}

	public void setFr(String fr) {
		this.fr = fr;
	}

	@Column(name = "address", length = 50)
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "dist", length = 20)
	public String getDist() {
		return dist;
	}

	public void setDist(String dist) {
		this.dist = dist;
	}

	@Column(name = "isNsr", length = 1)
	public String getIsNsr() {
		return isNsr;
	}

	public void setIsNsr(String isNsr) {
		this.isNsr = isNsr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TKh",cascade=CascadeType.ALL)
	public Set<TKhDet> getTKhDets() {
		return this.TKhDets;
	}

	public void setTKhDets(Set<TKhDet> TKhDets) {
		this.TKhDets = TKhDets;
	}

}
