package lnyswz.jxc.model;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TKhDet generated by hbm2java
 */
@Entity
@Table(name = "t_kh_det")
public class TKhDet implements java.io.Serializable {

	private String id;
	private TKh TKh;
	private TDepartment TDepartment;
	private Integer ywyId;
	private String isSx;
	private String lxr;
	private Integer sxzq;
	private BigDecimal sxje;
	private BigDecimal yfje;
	

	public TKhDet() {
	}

	public TKhDet(String id, TKh TKh, TDepartment TDepartment, String lxr,
			Integer ywyId, String isSx, Integer sxzq, BigDecimal sxje, BigDecimal yfje) {
		this.id = id;
		this.TKh = TKh;
		this.TDepartment = TDepartment;
		this.lxr = lxr;
		this.ywyId = ywyId;
		this.isSx = isSx;
		this.sxzq = sxzq;
		this.sxje = sxje;
		this.yfje = yfje;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "khbh", nullable = false)
	public TKh getTKh() {
		return this.TKh;
	}

	public void setTKh(TKh TKh) {
		this.TKh = TKh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "depId", nullable = false)
	public TDepartment getTDepartment() {
		return TDepartment;
	}

	public void setTDepartment(TDepartment tDepartment) {
		TDepartment = tDepartment;
	}

	@Column(name = "ywyId")
	public Integer getYwyId() {
		return ywyId;
	}

	public void setYwyId(Integer ywyId) {
		this.ywyId = ywyId;
	}

	@Column(name = "isSx", length = 1)
	public String getIsSx() {
		return isSx;
	}

	public void setIsSx(String isSx) {
		this.isSx = isSx;
	}

	@Column(name = "lxr", length = 50)
	public String getLxr() {
		return this.lxr;
	}

	public void setLxr(String lxr) {
		this.lxr = lxr;
	}

	@Column(name = "sxzq")
	public Integer getSxzq() {
		return this.sxzq;
	}

	public void setSxzq(Integer sxzq) {
		this.sxzq = sxzq;
	}

	@Column(name = "sxje")
	public BigDecimal getSxje() {
		return this.sxje;
	}

	public void setSxje(BigDecimal sxje) {
		this.sxje = sxje;
	}

	@Column(name = "yfje")
	public BigDecimal getYfje() {
		return yfje;
	}

	public void setYfje(BigDecimal yfje) {
		this.yfje = yfje;
	}

}
