package lnyswz.jxc.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TRklx generated by hbm2java
 */
@Entity
@Table(name = "t_khlx")
public class TKhlx implements java.io.Serializable {

	private String id;
	private String khlxmc;

	public TKhlx() {
	}

	public TKhlx(String id) {
		this.id = id;
	}

	public TKhlx(String id, String khlxmc) {
		this.id = id;
		this.khlxmc = khlxmc;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 2)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "khlxmc", unique = true, length = 50)
	public String getKhlxmc() {
		return this.khlxmc;
	}

	public void setKhlxmc(String khlxmc) {
		this.khlxmc = khlxmc;
	}

}
