package lnyswz.jxc.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TKsd generated by hbm2java
 */
@Entity
@Table(name = "t_ksd")
public class TKsd implements java.io.Serializable {

	private String ksdlsh;
	private String bmbh;
	private String bmmc;
	private Date createTime;
	private Integer createId;
	private String createName;
	private String khbh;
	private String khmc;
	private String yc;
	private String lxbm;
	private String lxr;
	private String zw;
	private String dh;
	private String gysbh;
	private String gysmc;
	private String zzlx;
	private String kslx;
	private String ksyy;
	private String jbr;
	private Date jbTime;
	private String xcjg;
	private String xcjbr;
	private Date xcTime;
	private String gysyj;
	private String gysjbr;
	private Date gysTime;
	private String cljg;
	private Date clTime;
	private String status;
	private Integer yclId;
	private String yclName;
	private Date yclTime;
	private Integer hxId;
	private String hxName;
	private Date hxTime;
	
	private Set<TKsdDet> TKsdDets = new HashSet<TKsdDet>(0);
	
	

	public TKsd() {
	}

	public TKsd(String ksdlsh, String bmbh, String bmmc, Date createTime, Integer createId, String createName, String khbh, String khmc,
			String yc, String lxbm, String lxr, String zw, String dh, String gysbh, String gysmc, String zzlx, String kslx, String ksyy,
			String jbr, Date jbTime, String xcjg, String xcjbr, Date xcTime, String gysyj, String gysjbr, Date gysTime, String cljg,
			Date clTime, String status, Integer yclId, String yclName, Date yclTime, Integer hxId, String hxName, Date hxTime, Set<TKsdDet> TKsdDets) {
		this.ksdlsh = ksdlsh;
		this.bmbh = bmbh;
		this.bmmc = bmmc;
		this.createTime = createTime;
		this.createId = createId;
		this.createName = createName;
		this.khbh = khbh;
		this.khmc = khmc;
		this.yc = yc;
		this.lxbm = lxbm;
		this.lxr = lxr;
		this.zw = zw;
		this.dh = dh;
		this.gysbh = gysbh;
		this.gysmc = gysmc;
		this.zzlx = zzlx;
		this.kslx = kslx;
		this.ksyy = ksyy;
		this.jbr = jbr;
		this.jbTime = jbTime;
		this.xcjg = xcjg;
		this.xcjbr = xcjbr;
		this.xcTime = xcTime;
		this.gysyj = gysyj;
		this.gysjbr = gysjbr;
		this.gysTime = gysTime;
		this.cljg = cljg;
		this.clTime = clTime;
		this.status = status;
		this.yclId = yclId;
		this.yclName = yclName;
		this.yclTime = yclTime;
		this.hxId = hxId;
		this.hxName = hxName;
		this.hxTime = hxTime;
		
		this.TKsdDets = TKsdDets;
	}

	@Id
	@Column(name = "ksdlsh", unique = true, nullable = false, length = 12)
	public String getKsdlsh() {
		return this.ksdlsh;
	}

	public void setKsdlsh(String ksdlsh) {
		this.ksdlsh = ksdlsh;
	}

	@Column(name = "createId", nullable = false)
	public Integer getCreateId() {
		return this.createId;
	}
	
	public void setCreateId(Integer createId) {
		this.createId = createId;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 23)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createName", nullable = false, length = 20)
	public String getCreateName() {
		return createName;
	}
	
	public void setCreateName(String createName) {
		this.createName = createName;
	}

	@Column(name = "khbh", length = 8)
	public String getKhbh() {
		return khbh;
	}

	public void setKhbh(String khbh) {
		this.khbh = khbh;
	}

	@Column(name = "khmc", length = 100)
	public String getKhmc() {
		return khmc;
	}

	public void setKhmc(String khmc) {
		this.khmc = khmc;
	}

	@Column(name = "yc", length = 20)
	public String getYc() {
		return yc;
	}

	public void setYc(String yc) {
		this.yc = yc;
	}

	@Column(name = "lxbm", length = 20)
	public String getLxbm() {
		return lxbm;
	}

	public void setLxbm(String lxbm) {
		this.lxbm = lxbm;
	}

	@Column(name = "lxr", length = 20)
	public String getLxr() {
		return lxr;
	}

	public void setLxr(String lxr) {
		this.lxr = lxr;
	}

	@Column(name = "zw", length = 20)
	public String getZw() {
		return zw;
	}

	public void setZw(String zw) {
		this.zw = zw;
	}

	@Column(name = "dh", length = 20)
	public String getDh() {
		return dh;
	}

	public void setDh(String dh) {
		this.dh = dh;
	}

	@Column(name = "bmbh", nullable = false, length = 2)
	public String getBmbh() {
		return this.bmbh;
	}

	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}

	@Column(name = "bmmc", nullable = false, length = 20)
	public String getBmmc() {
		return bmmc;
	}

	public void setBmmc(String bmmc) {
		this.bmmc = bmmc;
	}

	@Column(name = "gysbh", nullable = false, length = 8)
	public String getGysbh() {
		return gysbh;
	}

	public void setGysbh(String gysbh) {
		this.gysbh = gysbh;
	}

	@Column(name = "gysmc", nullable = false, length = 100)
	public String getGysmc() {
		return gysmc;
	}

	public void setGysmc(String gysmc) {
		this.gysmc = gysmc;
	}
	
	@Column(name = "zzlx", length = 20)
	public String getZzlx() {
		return zzlx;
	}

	public void setZzlx(String zzlx) {
		this.zzlx = zzlx;
	}

	@Column(name = "kslx", length = 20)
	public String getKslx() {
		return kslx;
	}

	public void setKslx(String kslx) {
		this.kslx = kslx;
	}

	@Column(name = "ksyy", length = 200)
	public String getKsyy() {
		return ksyy;
	}

	public void setKsyy(String ksyy) {
		this.ksyy = ksyy;
	}

	@Column(name = "jbr", length = 20)
	public String getJbr() {
		return jbr;
	}

	public void setJbr(String jbr) {
		this.jbr = jbr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "jbTime", nullable = false, length = 23)
	public Date getJbTime() {
		return jbTime;
	}

	public void setJbTime(Date jbTime) {
		this.jbTime = jbTime;
	}

	@Column(name = "xcjg", length = 200)
	public String getXcjg() {
		return xcjg;
	}

	public void setXcjg(String xcjg) {
		this.xcjg = xcjg;
	}

	@Column(name = "xcjbr", length = 20)
	public String getXcjbr() {
		return xcjbr;
	}

	public void setXcjbr(String xcjbr) {
		this.xcjbr = xcjbr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "xcTime", nullable = false, length = 23)
	public Date getXcTime() {
		return xcTime;
	}

	public void setXcTime(Date xcTime) {
		this.xcTime = xcTime;
	}

	@Column(name = "gysyj", length = 200)
	public String getGysyj() {
		return gysyj;
	}

	public void setGysyj(String gysyj) {
		this.gysyj = gysyj;
	}

	@Column(name = "gysjbr", length = 20)
	public String getGysjbr() {
		return gysjbr;
	}

	public void setGysjbr(String gysjbr) {
		this.gysjbr = gysjbr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "gysTime", nullable = false, length = 23)
	public Date getGysTime() {
		return gysTime;
	}

	public void setGysTime(Date gysTime) {
		this.gysTime = gysTime;
	}

	@Column(name = "cljg", length = 200)
	public String getCljg() {
		return cljg;
	}

	public void setCljg(String cljg) {
		this.cljg = cljg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "clTime", nullable = false, length = 23)
	public Date getClTime() {
		return clTime;
	}

	public void setClTime(Date clTime) {
		this.clTime = clTime;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "yclId")
	public Integer getYclId() {
		return yclId;
	}

	public void setYclId(Integer yclId) {
		this.yclId = yclId;
	}

	@Column(name = "yclName", length = 20)
	public String getYclName() {
		return yclName;
	}

	public void setYclName(String yclName) {
		this.yclName = yclName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "yclTime", nullable = false, length = 23)
	public Date getYclTime() {
		return yclTime;
	}

	public void setYclTime(Date yclTime) {
		this.yclTime = yclTime;
	}

	@Column(name = "hxId")
	public Integer getHxId() {
		return hxId;
	}

	public void setHxId(Integer hxId) {
		this.hxId = hxId;
	}

	@Column(name = "hxName", length = 20)
	public String getHxName() {
		return hxName;
	}

	public void setHxName(String hxName) {
		this.hxName = hxName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hxTime", nullable = false, length = 23)
	public Date getHxTime() {
		return hxTime;
	}

	public void setHxTime(Date hxTime) {
		this.hxTime = hxTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TKsd", cascade=CascadeType.ALL)
	public Set<TKsdDet> getTKsdDets() {
		return this.TKsdDets;
	}

	public void setTKsdDets(Set<TKsdDet> TKsdDets) {
		this.TKsdDets = TKsdDets;
	}

}
