package lnyswz.jxc.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TLsh generated by hbm2java
 */
@Entity
@Table(name = "t_lsh")
public class TLsh implements java.io.Serializable {

	private int id;
	private String lxbh;
	private String bmbh;
	private String lsh;

	public TLsh() {
	}

	public TLsh(int id, String lxbh, String bmbh, String lsh) {
		this.id = id;
		this.lxbh = lxbh;
		this.bmbh = bmbh;
		this.lsh = lsh;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "lxbh", nullable = false, length = 2)
	public String getLxbh() {
		return this.lxbh;
	}

	public void setLxbh(String lxbh) {
		this.lxbh = lxbh;
	}

	@Column(name = "bmbh", nullable = false, length = 2)
	public String getBmbh() {
		return this.bmbh;
	}

	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}

	@Column(name = "lsh", nullable = false, length = 12)
	public String getLsh() {
		return this.lsh;
	}

	public void setLsh(String lsh) {
		this.lsh = lsh;
	}

}
