package lnyswz.jxc.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * TMessage generated by hbm2java
 */
@Entity
@Table(name = "t_message")
public class TMessage implements java.io.Serializable {

	private int id;
	private int createId;
	private String createName;
	private Date createTime;
	private String subject;
	private String memo;
	private String isCancel;
	private Date cancelTime;

	public TMessage() {
	}

	public TMessage(int id, int createId, String createName, Date createTime,  
			String subject, String memo, String isCancel, Date cancelTime) {
		this.id = id;
		this.createId = createId;
		this.createName = createName;
		this.createTime = createTime;
		this.subject = subject;
		this.memo = memo;
		this.isCancel = isCancel;
		this.cancelTime = cancelTime;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "createId", nullable = false)
	public int getCreateId() {
		return this.createId;
	}
	
	public void setCreateId(int createId) {
		this.createId = createId;
	}

	@Column(name = "createName", nullable = false, length = 50)
	public String getCreateName() {
		return this.createName;
	}
	
	public void setCreateName(String createName) {
		this.createName = createName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 23)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}



	@Column(name = "subject", nullable = false, length = 100)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "memo", nullable = false, length = 500)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}
		
	@Column(name = "isCancel", nullable = false, length = 1)
	public String getIsCancel() {
		return this.isCancel;
	}

	public void setIsCancel(String isCancel) {
		this.isCancel = isCancel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cancelTime", length = 23)
	public Date getCancelTime() {
		return this.cancelTime;
	}

	public void setCancelTime(Date cancelTime) {
		this.cancelTime = cancelTime;
	}
}
