package lnyswz.jxc.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * TMessageRec generated by hbm2java
 */
@Entity
@Table(name = "t_message_rec")
public class TMessageRec implements java.io.Serializable {

	private int id;
	private int messageId;
	private int receiverId;
	private Date readTime;
	private String isCancel;
	private Date cancelTime;

	public TMessageRec() {
	}

	public TMessageRec(int id, int messageId, int receiverId, Date readTime,  
			String isCancel, Date cancelTime) {
		this.id = id;
		this.messageId = messageId;
		this.receiverId = receiverId;
		this.readTime = readTime;
		this.isCancel = isCancel;
		this.cancelTime = cancelTime;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "messageId", nullable = false)
	public int getMessageId() {
		return this.messageId;
	}
	
	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}
	
	@Column(name = "receiverId", nullable = false)
	public int getReceiverId() {
		return this.receiverId;
	}
	
	public void setReceiverId(int receiverId) {
		this.receiverId = receiverId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "readTime", length = 23)
	public Date getReadTime() {
		return this.readTime;
	}

	public void setReadTime(Date readTime) {
		this.readTime = readTime;
	}
		
	@Column(name = "isCancel", nullable = false, length = 1)
	public String getIsCancel() {
		return this.isCancel;
	}

	public void setIsCancel(String isCancel) {
		this.isCancel = isCancel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cancelTime", length = 23)
	public Date getCancelTime() {
		return this.cancelTime;
	}

	public void setCancelTime(Date cancelTime) {
		this.cancelTime = cancelTime;
	}
}
