package lnyswz.jxc.model;

import javax.persistence.*;
import java.util.Date;


/**
 * TPaper generated by hbm2java
 */
@Entity
@Table(name = "t_paper")
public class TPaper implements java.io.Serializable {

	private int id;
	private String filename;
	private String filepath;
	private String type;
	private TMessage TMessage;


	public TPaper() {
	}

	public TPaper(int id, String filename, String filepath, String type, TMessage TMessage) {
		this.id = id;
		this.filename = filename;
		this.filepath = filepath;
		this.type = type;
		this.TMessage = TMessage;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "filename", nullable = true, length = 200)
	public String getFilename() {
		return this.filename;
	}
	
	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "filepath", nullable = false, length = 200)
	public String getFilepath() {
		return this.filepath;
	}

	public void setFilepath(String filepath) {
		this.filepath = filepath;
	}

	@Column(name = "type", nullable = false, length = 20)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "messageId")
	public lnyswz.jxc.model.TMessage getTMessage() {
		return TMessage;
	}

	public void setTMessage(lnyswz.jxc.model.TMessage TMessage) {
		this.TMessage = TMessage;
	}
}
