package lnyswz.jxc.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TPdlx generated by hbm2java
 */
@Entity
@Table(name = "t_pdlx")
public class TPdlx implements java.io.Serializable {

	private String id;
	private String pdlxmc;

	public TPdlx() {
	}

	public TPdlx(String id) {
		this.id = id;
	}

	public TPdlx(String id, String pdlxmc) {
		this.id = id;
		this.pdlxmc = pdlxmc;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 2)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "pdlxmc", unique = true, length = 20)
	public String getPdlxmc() {
		return this.pdlxmc;
	}

	public void setPdlxmc(String pdlxmc) {
		this.pdlxmc = pdlxmc;
	}

}
