package lnyswz.jxc.model;

import javax.persistence.*;
import java.util.Date;

/**
 * TYwsh generated by hbm2java
 */
@Entity
@Table(name = "t_print")
public class TPrint implements java.io.Serializable {

	private int id;
	private String lsh;
	private Date printTime;
	private int printId;
	private String printName;
	private int bgyId;
	private String type;

	public TPrint() {
	}
	
	public TPrint(int id, String lsh, Date printTime, int printId, String printName, int bgyId, String type) {
		this.id = id;
		this.lsh = lsh;
		this.printTime = printTime;
		this.printId = printId;
		this.printName = printName;
		this.bgyId = bgyId;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "lsh", nullable = false, length = 12)
	public String getLsh() {
		return lsh;
	}

	public void setLsh(String lsh) {
		this.lsh = lsh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "printTime", nullable = false, length = 23)
	public Date getPrintTime() {
		return printTime;
	}

	public void setPrintTime(Date printTime) {
		this.printTime = printTime;
	}

	@Column(name = "printId", nullable = false)
	public int getPrintId() {
		return printId;
	}

	public void setPrintId(int printId) {
		this.printId = printId;
	}

	@Column(name = "printName", nullable = false, length = 20)
	public String getPrintName() {
		return printName;
	}

	public void setPrintName(String printName) {
		this.printName = printName;
	}

	@Column(name = "bgyId", nullable = false)
	public int getBgyId() {
		return bgyId;
	}

	public void setBgyId(int bgyId) {
		this.bgyId = bgyId;
	}

	@Column(name = "type", nullable = false, length = 2)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
}
