package lnyswz.jxc.model;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * TRkfk generated by hbm2java
 */
@Entity
@Table(name = "t_rkfk")
public class TRkfk implements java.io.Serializable {
	private String rkfklsh;
	private Date createTime;
	private int createId;
	private String createName;
	private String bmbh;
	private String bmmc;
	private String gysbh;
	private String gysmc;
	private BigDecimal fkje;
	private BigDecimal yfje;
	private Date payTime;
	private String isYf;
	private String isCancel;
	private Integer cancelId;
	private String cancelName;
	private Date cancelTime;
	private String cancelRkfklsh;
//	private Set<TFkRk> TFkRks = new HashSet<TFkRk>(0);

	@Id
	@Column(name = "rkfklsh", unique = true, nullable = false, length = 12)
	public String getRkfklsh() {
		return this.rkfklsh;
	}

	public void setRkfklsh(String rkfklsh) {
		this.rkfklsh = rkfklsh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 23)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createId", nullable = false)
	public int getCreateId() {
		return this.createId;
	}

	public void setCreateId(int createId) {
		this.createId = createId;
	}

	@Column(name = "createName", nullable = false, length = 50)
	public String getCreateName() {
		return this.createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	@Column(name = "bmbh", nullable = false, length = 2)
	public String getBmbh() {
		return this.bmbh;
	}

	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}

	@Column(name = "bmmc", nullable = false, length = 20)
	public String getBmmc() {
		return this.bmmc;
	}

	public void setBmmc(String bmmc) {
		this.bmmc = bmmc;
	}

	@Column(name = "gysbh", nullable = false, length = 8)
	public String getGysbh() {
		return this.gysbh;
	}

	public void setGysbh(String gysbh) {
		this.gysbh = gysbh;
	}

	@Column(name = "gysmc", nullable = false, length = 50)
	public String getGysmc() {
		return this.gysmc;
	}

	public void setGysmc(String gysmc) {
		this.gysmc = gysmc;
	}

	@Column(name = "fkje", nullable = false, precision = 18, scale = 2)
	public BigDecimal getFkje() {
		return fkje;
	}

	public void setFkje(BigDecimal fkje) {
		this.fkje = fkje;
	}
	
	@Column(name = "yfje", nullable = false, precision = 18, scale = 4)
	public BigDecimal getYfje() {
		return yfje;
	}

	public void setYfje(BigDecimal yfje) {
		this.yfje = yfje;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "payTime", nullable = false, length = 23)
	public Date getPayTime() {
		return payTime;
	}
	
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}
	
	@Column(name = "isYf", nullable = false, length = 1)
	public String getIsYf() {
		return this.isYf;
	}

	public void setIsYf(String isYf) {
		this.isYf = isYf;
	}
	
	@Column(name = "isCancel", nullable = false, length = 1)
	public String getIsCancel() {
		return this.isCancel;
	}

	public void setIsCancel(String isCancel) {
		this.isCancel = isCancel;
	}

	@Column(name = "cancelId")
	public Integer getCancelId() {
		return this.cancelId;
	}

	public void setCancelId(Integer cancelId) {
		this.cancelId = cancelId;
	}

	@Column(name = "cancelName", length = 20)
	public String getCancelName() {
		return this.cancelName;
	}

	public void setCancelName(String cancelName) {
		this.cancelName = cancelName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cancelTime", length = 23)
	public Date getCancelTime() {
		return this.cancelTime;
	}

	public void setCancelTime(Date cancelTime) {
		this.cancelTime = cancelTime;
	}

	@Column(name = "cancelRkfklsh", length = 12)
	public String getCancelRkfklsh() {
		return this.cancelRkfklsh;
	}

	public void setCancelRkfklsh(String cancelRkfklsh) {
		this.cancelRkfklsh = cancelRkfklsh;
	}

//	@OneToMany(cascade = CascadeType.PERSIST, fetch = FetchType.LAZY, mappedBy = "TRkfk")
//	public Set<TFkRk> getTFkRks() {
//		return this.TFkRks;
//	}
//
//	public void setTFkRks(Set<TFkRk> TFkRks) {
//		this.TFkRks = TFkRks;
//	}
	
}
