package lnyswz.jxc.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TRklx generated by hbm2java
 */
@Entity
@Table(name = "t_rklx")
public class TRklx implements java.io.Serializable {

	private String id;
	private String rklxmc;

	public TRklx() {
	}

	public TRklx(String id) {
		this.id = id;
	}

	public TRklx(String id, String rklxmc) {
		this.id = id;
		this.rklxmc = rklxmc;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 2)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "rklxmc", unique = true, length = 50)
	public String getRklxmc() {
		return this.rklxmc;
	}

	public void setRklxmc(String rklxmc) {
		this.rklxmc = rklxmc;
	}

}
