package lnyswz.jxc.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TRylx generated by hbm2java
 */
@Entity
@Table(name = "t_rylx")
public class TRylx implements java.io.Serializable {

	private String id;
	private String rylxmc;

	public TRylx() {
	}

	public TRylx(String id) {
		this.id = id;
	}

	public TRylx(String id, String rylxmc) {
		this.id = id;
		this.rylxmc = rylxmc;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 2)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "rylxmc", unique = true, length = 50)
	public String getRylxmc() {
		return this.rylxmc;
	}

	public void setRylxmc(String rylxmc) {
		this.rylxmc = rylxmc;
	}

}
