package lnyswz.jxc.model;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

	/**
	 * TShdz generated by hbm2java
	 */
	@Entity
	@Table(name = "t_shdz")
	public class TShdz implements java.io.Serializable {

		private int id;
		private String khmc;
		private String khdz;
		private String lxr; 
		private String phone;
		public TShdz() {
		}

		public TShdz(int id,String khmc,String khdz,String lxr,String phone){
			this.id = id;
			this.khmc = khmc;
			this.khdz=khdz;
			this.phone=phone;
			this.lxr=lxr;
		}
		@Id
		@GeneratedValue(strategy=GenerationType.IDENTITY)
		@Column(name = "id", unique = true, nullable = false)
		public int getId() {
			return this.id;
		}

		public void setId(int id) {
			this.id = id;
		}
		
		
		
		@Column(name = "khmc", nullable = true, length = 36)
		public String getKhmc() {
			return this.khmc;
		}

		public void setKhmc(String khmc) {
			this.khmc = khmc;
		}

		
		@Column(name = "khdz", nullable = true, length = 50)
		public String getKhdz() {
			return this.khdz;
		}

		public void setKhdz(String khdz) {
			this.khdz = khdz;
		}
		
		@Column(name = "phone", nullable = true, length = 100)
		public String getphone() {
			return this.phone;
		}

		public void setPhone(String phone) {
			this.phone = phone;
		}
		@Column(name = "lxr", nullable = true, length = 50)
		public String getLxr() {
			return this.lxr;
		}

		public void setLxr(String lxr) {
			this.lxr = lxr;
		}
	}


