package lnyswz.jxc.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TSpdl generated by hbm2java
 */
@Entity
@Table(name = "t_spdl")
public class TSpdl implements java.io.Serializable {

	private String id;
	private String spdlmc;
	private Set<TSplb> TSplbs = new HashSet<TSplb>(0);
	private Set<TDepartment> TDepartments = new HashSet<TDepartment>(0);

	public TSpdl() {
	}

	public TSpdl(String id, String spdlmc, Set<TSplb> TSplbs, Set<TDepartment> TDepartments) {
		this.id = id;
		this.spdlmc = spdlmc;
		this.TSplbs = TSplbs;
		this.TDepartments = TDepartments;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 1)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "spdlmc", unique = true, nullable = false, length = 50)
	public String getSpdlmc() {
		return this.spdlmc;
	}

	public void setSpdlmc(String spdlmc) {
		this.spdlmc = spdlmc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSpdl")
	public Set<TSplb> getTSplbs() {
		return this.TSplbs;
	}

	public void setTSplbs(Set<TSplb> TSplbs) {
		this.TSplbs = TSplbs;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_bm_spdl", joinColumns = { @JoinColumn(name = "spdlId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "depId", nullable = false, updatable = false) })
	public Set<TDepartment> getTDepartments() {
		return TDepartments;
	}

	public void setTDepartments(Set<TDepartment> tDepartments) {
		TDepartments = tDepartments;
	}

}
