package lnyswz.jxc.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TSplb generated by hbm2java
 */
@Entity
@Table(name = "t_spdw")
public class TSpdw implements java.io.Serializable {

	private String id;
	private TSplb TSplb;
	private String spdwmc;
	private Set<TSp> TSps = new HashSet<TSp>(0);

	public TSpdw() {
	}

	public TSpdw(String id, TSplb TSplb, String spdwmc) {
		this.id = id;
		this.TSplb = TSplb;
		this.spdwmc = spdwmc;
	}

	public TSpdw(String id, TSplb TSplb, String spdwmc, Set<TSp> TSps) {
		this.id = id;
		this.TSplb = TSplb;
		this.spdwmc = spdwmc;
		this.TSps = TSps;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "splbId", nullable = false)
	public TSplb getTSplb() {
		return this.TSplb;
	}

	public void setTSplb(TSplb TSplb) {
		this.TSplb = TSplb;
	}

	@Column(name = "spdwmc", nullable = false, length = 50)
	public String getSpdwmc() {
		return this.spdwmc;
	}

	public void setSpdwmc(String spdwmc) {
		this.spdwmc = spdwmc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSpdw")
	public Set<TSp> getTSps() {
		return this.TSps;
	}

	public void setTSps(Set<TSp> TSps) {
		this.TSps = TSps;
	}

}
