package lnyswz.jxc.model;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

/**
 * TThCar generated by hbm2java
 */
@Entity
@Table(name = "t_th_car")
public class TThCar implements java.io.Serializable {

	private int id;
	private String lsh;
	private int carId;
	private int createId;
	private String createName;
	private Date createTime;

	public TThCar() {
	}

	public TThCar(int id, String lsh, int carId, int createId, String createName, Date createTime) {
		this.id = id;
		this.lsh = lsh;
		this.carId = carId;
		this.createId = createId;
		this.createName = createName;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}


	@Column(name = "lsh", nullable = false, length = 12)
	public String getLsh() {
		return this.lsh;
	}

	public void setLsh(String lsh) {
		this.lsh = lsh;
	}

	@Column(name = "carId", nullable = false)
	public int getCarId() {
		return carId;
	}

	public void setCarId(int carId) {
		this.carId = carId;
	}

	@Column(name = "createId", nullable = false)
	public int getCreateId() {
		return createId;
	}

	public void setCreateId(int createId) {
		this.createId = createId;
	}

	@Column(name = "createName", nullable = false, length = 20)
	public String getCreateName() {
		return createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 23)
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}
