package lnyswz.jxc.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * TXskp generated by hbm2java
 */
@Entity
@Table(name = "t_xskp")
public class TXskp implements java.io.Serializable {

	private String xskplsh;
	private Date createTime;
	private int createId;
	private String createName;
	private String bmbh;
	private String bmmc;
	private String khbh;
	private String khmc;
	private String dzdh;
	private String khh;
	private String sh;
	private String ckId;
	private String ckmc;
	private String fhId;
	private String fhmc;
	private String jsfsId;
	private String jsfsmc;
	private String fplxId;
	private String fplxmc;
	private String xslxId;
	private String xslxmc;
	private String bookmc;
	private String fyr;
	private String thfs;
	private String shdz;
	private String thr;
	private String ch;
	private int ywyId;
	private String ywymc;
	private BigDecimal hjje;
	private BigDecimal hjse;
	private BigDecimal hkje;
	private BigDecimal yfje;
	private String bz;
	private String fromTh;
	private String isZs;
	private String isSx;
	private String isCj;
	private Integer cjId;
	private String cjName;
	private Date cjTime;
	private String cjXskplsh;
	private String isTh;
	private Date thTime;
	private String xsthlsh;
	private String isHk;
	private Date hkTime;
	private String needAudit;
	private String isAudit;
	private Set<TXskpDet> TXskpDets = new HashSet<TXskpDet>(0);
	private Set<TXsthDet> TXsths = new HashSet<TXsthDet>(0);
//	private Set<TXsth> TXsths = new HashSet<TXsth>(0);
	private TYwrk TYwrk;
//	private Set<TXshk> TXshks;

	public TXskp() {
	}

	public TXskp(String xskplsh, Date createTime, int createId, String createName, String bmbh, String bmmc, String khbh,
			String khmc, String dzdh, String khh, String sh, String ckId, String ckmc, String fhId, String fhmc, String jsfsId,
			String jsfsmc, String fplxId, String fplxmc, String xslxId, String xslxmc, String bookmc,	String fyr, String thfs, String shdz, String thr, String ch, int ywyId, String ywymc, BigDecimal hjje,
			BigDecimal hjse, BigDecimal hkje, BigDecimal yfje, String bz, String fromTh, String isZs, String isSx, String isCj, Integer cjId,	String cjName, Date cjTime, String cjXskplsh, 
			String isTh, Date thTime, String xsthlsh, String isHk, Date hkTime, String needAudit, String isAudit, 
			Set<TXskpDet> TXskpDets, Set<TXsthDet> TXsths, TYwrk TYwrk) {
		this.xskplsh = xskplsh;
		this.createTime = createTime;
		this.createId = createId;
		this.createName = createName;
		this.bmbh = bmbh;
		this.bmmc = bmmc;
		this.khbh = khbh;
		this.khmc = khmc;
		this.dzdh = dzdh;
		this.khh = khh;
		this.sh = sh;
		this.ckId = ckId;
		this.ckmc = ckmc;
		this.fhId = fhId;
		this.fhmc = fhmc;
		this.jsfsId = jsfsId;
		this.jsfsmc = jsfsmc;
		this.fplxId = fplxId;
		this.fplxmc = fplxmc;
		this.xslxId = xslxId;
		this.xslxmc = xslxmc;
		this.bookmc = bookmc;
		this.fyr = fyr;
		this.thfs = thfs;
		this.shdz = shdz;
		this.thr = thr;
		this.ch = ch;
		this.ywyId = ywyId;
		this.ywymc = ywymc;
		this.hjje = hjje;
		this.hjse = hjse;
		this.hkje = hkje;
		this.yfje = yfje;
		this.bz = bz;
		this.fromTh = fromTh;
		this.isZs = isZs;
		this.isSx = isSx;
		this.isCj = isCj;
		this.cjId = cjId;
		this.cjName = cjName;
		this.cjTime = cjTime;
		this.cjXskplsh = cjXskplsh;
		this.isTh = isTh;
		this.thTime = thTime;
		this.xsthlsh = xsthlsh;
		this.isHk = isHk;
		this.hkTime = hkTime;
		this.needAudit = needAudit;
		this.isAudit = isAudit;
		this.TXskpDets = TXskpDets;
		this.TXsths = TXsths;
		this.TYwrk = TYwrk;
//		this.TXshks = TXshks;
	}

	@Id
	@Column(name = "xskplsh", unique = true, nullable = false, length = 12)
	public String getXskplsh() {
		return this.xskplsh;
	}

	public void setXskplsh(String xskplsh) {
		this.xskplsh = xskplsh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 23)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createId", nullable = false)
	public int getCreateId() {
		return this.createId;
	}

	public void setCreateId(int createId) {
		this.createId = createId;
	}

	@Column(name = "createName", nullable = false, length = 50)
	public String getCreateName() {
		return this.createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	@Column(name = "bmbh", nullable = false, length = 2)
	public String getBmbh() {
		return this.bmbh;
	}

	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}

	@Column(name = "bmmc", nullable = false, length = 20)
	public String getBmmc() {
		return this.bmmc;
	}

	public void setBmmc(String bmmc) {
		this.bmmc = bmmc;
	}

	@Column(name = "khbh", nullable = false, length = 8)
	public String getKhbh() {
		return this.khbh;
	}

	public void setKhbh(String khbh) {
		this.khbh = khbh;
	}

	@Column(name = "khmc", nullable = false, length = 50)
	public String getKhmc() {
		return this.khmc;
	}

	public void setKhmc(String khmc) {
		this.khmc = khmc;
	}

	@Column(name = "dzdh", length = 100)
	public String getDzdh() {
		return this.dzdh;
	}

	public void setDzdh(String dzdh) {
		this.dzdh = dzdh;
	}

	@Column(name = "khh", length = 100)
	public String getKhh() {
		return this.khh;
	}

	public void setKhh(String khh) {
		this.khh = khh;
	}

	@Column(name = "sh", length = 15)
	public String getSh() {
		return this.sh;
	}

	public void setSh(String sh) {
		this.sh = sh;
	}

	@Column(name = "ckId", nullable = false, length = 2)
	public String getCkId() {
		return this.ckId;
	}

	public void setCkId(String ckId) {
		this.ckId = ckId;
	}

	@Column(name = "ckmc", nullable = false, length = 20)
	public String getCkmc() {
		return this.ckmc;
	}

	public void setCkmc(String ckmc) {
		this.ckmc = ckmc;
	}

	@Column(name = "fhId", length = 2)
	public String getFhId() {
		return this.fhId;
	}

	public void setFhId(String fhId) {
		this.fhId = fhId;
	}

	@Column(name = "fhmc", length = 20)
	public String getFhmc() {
		return this.fhmc;
	}

	public void setFhmc(String fhmc) {
		this.fhmc = fhmc;
	}

	@Column(name = "jsfsId", nullable = false, length = 2)
	public String getJsfsId() {
		return this.jsfsId;
	}

	public void setJsfsId(String jsfsId) {
		this.jsfsId = jsfsId;
	}

	@Column(name = "jsfsmc", nullable = false, length = 20)
	public String getJsfsmc() {
		return this.jsfsmc;
	}

	public void setJsfsmc(String jsfsmc) {
		this.jsfsmc = jsfsmc;
	}

	@Column(name = "fplxId", nullable = false, length = 1)
	public String getFplxId() {
		return this.fplxId;
	}

	public void setFplxId(String fplxId) {
		this.fplxId = fplxId;
	}

	@Column(name = "fplxmc", length = 20)
	public String getFplxmc() {
		return this.fplxmc;
	}

	public void setFplxmc(String fplxmc) {
		this.fplxmc = fplxmc;
	}
	
	@Column(name = "xslxId", nullable = false, length = 2)
	public String getXslxId() {
		return this.xslxId;
	}

	public void setXslxId(String xslxId) {
		this.xslxId = xslxId;
	}

	@Column(name = "xslxmc", nullable = false, length = 20)
	public String getXslxmc() {
		return xslxmc;
	}

	public void setXslxmc(String xslxmc) {
		this.xslxmc = xslxmc;
	}

	@Column(name = "bookmc", length = 100)
	public String getBookmc() {
		return this.bookmc;
	}

	public void setBookmc(String bookmc) {
		this.bookmc = bookmc;
	}

	@Column(name = "fyr", length = 20)
	public String getFyr() {
		return this.fyr;
	}

	public void setFyr(String fyr) {
		this.fyr = fyr;
	}
	
	@Column(name = "thfs", nullable = false, length = 1)
	public String getThfs() {
		return thfs;
	}

	public void setThfs(String thfs) {
		this.thfs = thfs;
	}

	@Column(name = "shdz", length = 100)
	public String getShdz() {
		return shdz;
	}

	public void setShdz(String shdz) {
		this.shdz = shdz;
	}

	@Column(name = "thr", length = 20)
	public String getThr() {
		return thr;
	}
	
	public void setThr(String thr) {
		this.thr = thr;
	}
	
	@Column(name = "ch", length = 20)
	public String getCh() {
		return ch;
	}

	public void setCh(String ch) {
		this.ch = ch;
	}

	@Column(name = "ywyId", nullable = false)
	public int getYwyId() {
		return this.ywyId;
	}

	public void setYwyId(int ywyId) {
		this.ywyId = ywyId;
	}

	@Column(name = "ywymc", nullable = false, length = 20)
	public String getYwymc() {
		return this.ywymc;
	}

	public void setYwymc(String ywymc) {
		this.ywymc = ywymc;
	}

	@Column(name = "hjje", nullable = false, precision = 18, scale = 4)
	public BigDecimal getHjje() {
		return hjje;
	}

	public void setHjje(BigDecimal hjje) {
		this.hjje = hjje;
	}

	@Column(name = "hjse", nullable = false, precision = 18, scale = 4)
	public BigDecimal getHjse() {
		return hjse;
	}

	public void setHjse(BigDecimal hjse) {
		this.hjse = hjse;
	}

	@Column(name = "hkje", nullable = false, precision = 18, scale = 4)
	public BigDecimal getHkje() {
		return hkje;
	}

	public void setHkje(BigDecimal hkje) {
		this.hkje = hkje;
	}

	@Column(name = "yfje", nullable = false, precision = 18, scale = 4)
	public BigDecimal getYfje() {
		return yfje;
	}

	public void setYfje(BigDecimal yfje) {
		this.yfje = yfje;
	}

	@Column(name = "bz", length = 100)
	public String getBz() {
		return bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	@Column(name = "fromTh", nullable = false, length = 1)
	public String getFromTh() {
		return fromTh;
	}

	public void setFromTh(String fromTh) {
		this.fromTh = fromTh;
	}

	@Column(name = "isZs", nullable = false, length = 1)
	public String getIsZs() {
		return isZs;
	}

	public void setIsZs(String isZs) {
		this.isZs = isZs;
	}

	@Column(name = "isSx", nullable = false, length = 1)
	public String getIsSx() {
		return isSx;
	}

	public void setIsSx(String isSx) {
		this.isSx = isSx;
	}

	@Column(name = "isCj", nullable = false, length = 1)
	public String getIsCj() {
		return this.isCj;
	}

	public void setIsCj(String isCj) {
		this.isCj = isCj;
	}

	@Column(name = "cjId")
	public Integer getCjId() {
		return this.cjId;
	}

	public void setCjId(Integer cjId) {
		this.cjId = cjId;
	}

	@Column(name = "cjName", length = 20)
	public String getCjName() {
		return this.cjName;
	}

	public void setCjName(String cjName) {
		this.cjName = cjName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cjTime", length = 23)
	public Date getCjTime() {
		return this.cjTime;
	}

	public void setCjTime(Date cjTime) {
		this.cjTime = cjTime;
	}

	@Column(name = "cjXskplsh", length = 12)
	public String getCjXskplsh() {
		return this.cjXskplsh;
	}

	public void setCjXskplsh(String cjXskplsh) {
		this.cjXskplsh = cjXskplsh;
	}

	@Column(name = "isTh", nullable = false, length = 1)
	public String getIsTh() {
		return this.isTh;
	}

	public void setIsTh(String isTh) {
		this.isTh = isTh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "thTime", length = 23)
	public Date getThTime() {
		return this.thTime;
	}

	public void setThTime(Date thTime) {
		this.thTime = thTime;
	}

	@Column(name = "xsthlsh", length = 12)
	public String getXsthlsh() {
		return this.xsthlsh;
	}

	public void setXsthlsh(String xsthlsh) {
		this.xsthlsh = xsthlsh;
	}

	@Column(name = "isHk", nullable = false, length = 1)
	public String getIsHk() {
		return this.isHk;
	}

	public void setIsHk(String isHk) {
		this.isHk = isHk;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hkTime", length = 23)
	public Date getHkTime() {
		return this.hkTime;
	}

	public void setHkTime(Date hkTime) {
		this.hkTime = hkTime;
	}
	
	@Column(name = "needAudit", nullable = false, length = 1)
	public String getNeedAudit() {
		return this.needAudit;
	}

	public void setNeedAudit(String needAudit) {
		this.needAudit = needAudit;
	}

	@Column(name = "isAudit", nullable = false, length = 1)
	public String getIsAudit() {
		return this.isAudit;
	}

	public void setIsAudit(String isAudit) {
		this.isAudit = isAudit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TXskp", cascade=CascadeType.ALL)
	public Set<TXskpDet> getTXskpDets() {
		return this.TXskpDets;
	}

	public void setTXskpDets(Set<TXskpDet> TXskpDets) {
		this.TXskpDets = TXskpDets;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_xsth_xskp", joinColumns = { @JoinColumn(name = "xskplsh", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "xsthdetId", nullable = false, updatable = false) })
	public Set<TXsthDet> getTXsths() {
		return this.TXsths;
	}
	
	public void setTXsths(Set<TXsthDet> TXsths) {
		this.TXsths = TXsths;
	}
	
	@OneToOne//表示一对一的关系
	@JoinColumn(name="ywrklsh")
	public TYwrk getTYwrk() {
		return TYwrk;
	}

	public void setTYwrk(TYwrk tYwrk) {
		TYwrk = tYwrk;
	}
	
//	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TXskps")
//	public Set<TXshk> getTXshks() {
//		return this.TXshks;
//	}
//	
//	public void setTXshks(Set<TXshk> TXshks) {
//		this.TXshks = TXshks;
//	}
}
