package lnyswz.jxc.model;

import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;
import java.math.BigDecimal;

/**
 * TYwzz generated by hbm2java
 */
@Entity
@Table(name = "t_yfzz")
@DynamicUpdate(true)
public class TYfzz implements java.io.Serializable {

	private int id;
	private String bmbh;
	private String bmmc;
	private String gysbh;
	private String gysmc;
	private BigDecimal qcje;
	private BigDecimal rkje;
	private BigDecimal fkje;
	private String jzsj;

	public TYfzz() {
	}

	public TYfzz(int id, String bmbh, String bmmc, String gysbh, String gysmc, BigDecimal qcje, BigDecimal rkje, BigDecimal fkje, String jzsj) {
		this.id = id;
		this.bmbh = bmbh;
		this.bmmc = bmmc;
		this.gysbh = gysbh;
		this.gysmc = gysmc;
		this.qcje = qcje;
		this.rkje = rkje;
		this.fkje = fkje;
		this.jzsj = jzsj;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "bmbh", nullable = false, length = 2)
	public String getBmbh() {
		return this.bmbh;
	}

	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}
	
	@Column(name = "bmmc", nullable = false, length = 100)
	public String getBmmc() {
		return this.bmmc;
	}
	
	public void setBmmc(String bmmc) {
		this.bmmc = bmmc;
	}
	
	@Column(name = "gysbh", nullable = false, length = 8)
	public String getGysbh() {
		return this.gysbh;
	}
	
	public void setGysbh(String gysbh) {
		this.gysbh = gysbh;
	}
	
	@Column(name = "gysmc", nullable = false, length = 50)
	public String getGysmc() {
		return this.gysmc;
	}
	
	public void setGysmc(String gysmc) {
		this.gysmc = gysmc;
	}

	@Column(name = "qcje", precision = 18, scale = 4)
	public BigDecimal getQcje() {
		return qcje;
	}

	public void setQcje(BigDecimal qcje) {
		this.qcje = qcje;
	}
	
	@Column(name = "rkje", precision = 18, scale = 4)
	public BigDecimal getRkje() {
		return rkje;
	}

	public void setRkje(BigDecimal rkje) {
		this.rkje = rkje;
	}
	
	@Column(name = "fkje", precision = 18, scale = 4)
	public BigDecimal getFkje() {
		return fkje;
	}
	
	public void setFkje(BigDecimal fkje) {
		this.fkje = fkje;
	}

	@Column(name = "jzsj", nullable = false, length = 10)
	public String getJzsj() {
		return jzsj;
	}

	public void setJzsj(String jzsj) {
		this.jzsj = jzsj;
	}
	
}
