package lnyswz.jxc.model;

import org.hibernate.annotations.DynamicUpdate;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TYwzz generated by hbm2java
 */
@Entity
@Table(name = "t_yszz")
@DynamicUpdate(true)
public class TYszz implements java.io.Serializable {

	private int id;
	private String bmbh;
	private String bmmc;
	private String khbh;
	private String khmc;
	private int ywyId;
	private String ywymc;
	private BigDecimal lsje;
	private BigDecimal qcje;
	private BigDecimal qcthje;
	private BigDecimal kpje;
	private BigDecimal thje;
	private BigDecimal hkje;
	private String jzsj;

	public TYszz() {
	}

	public TYszz(int id, String bmbh, String bmmc, String khbh, String khmc, int ywyId, String ywymc,
			BigDecimal qcje, BigDecimal qcthje, BigDecimal kpje, BigDecimal thje, BigDecimal hkje, String jzsj) {
		this.id = id;
		this.bmbh = bmbh;
		this.bmmc = bmmc;
		this.khbh = khbh;
		this.khmc = khmc;
		this.ywyId = ywyId;
		this.ywymc = ywymc;
		this.qcje = qcje;
		this.qcthje = qcthje;
		this.kpje = kpje;
		this.thje = thje;
		this.hkje = hkje;
		this.jzsj = jzsj;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "bmbh", nullable = false, length = 2)
	public String getBmbh() {
		return this.bmbh;
	}

	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}
	
	@Column(name = "bmmc", nullable = false, length = 100)
	public String getBmmc() {
		return this.bmmc;
	}
	
	public void setBmmc(String bmmc) {
		this.bmmc = bmmc;
	}
	
	@Column(name = "khbh", nullable = false, length = 8)
	public String getKhbh() {
		return this.khbh;
	}
	
	public void setKhbh(String khbh) {
		this.khbh = khbh;
	}
	
	@Column(name = "khmc", nullable = false, length = 100)
	public String getKhmc() {
		return this.khmc;
	}
	
	public void setKhmc(String khmc) {
		this.khmc = khmc;
	}

	@Column(name = "ywyId")
	public int getYwyId() {
		return ywyId;
	}

	public void setYwyId(int ywyId) {
		this.ywyId = ywyId;
	}
	
	@Column(name = "ywymc", length = 20)
	public String getYwymc() {
		return ywymc;
	}

	public void setYwymc(String ywymc) {
		this.ywymc = ywymc;
	}

	@Column(name = "lsje", precision = 18, scale = 4)
	public BigDecimal getLsje() {
		return lsje;
	}

	public void setLsje(BigDecimal lsje) {
		this.lsje = lsje;
	}

	@Column(name = "qcje", precision = 18, scale = 4)
	public BigDecimal getQcje() {
		return qcje;
	}

	public void setQcje(BigDecimal qcje) {
		this.qcje = qcje;
	}
	
	@Column(name = "qcthje", precision = 18, scale = 4)
	public BigDecimal getQcthje() {
		return qcthje;
	}
	
	public void setQcthje(BigDecimal qcthje) {
		this.qcthje = qcthje;
	}

	@Column(name = "kpje", precision = 18, scale = 4)
	public BigDecimal getKpje() {
		return kpje;
	}

	public void setKpje(BigDecimal kpje) {
		this.kpje = kpje;
	}
	
	@Column(name = "thje", precision = 18, scale = 4)
	public BigDecimal getThje() {
		return thje;
	}
	
	public void setThje(BigDecimal thje) {
		this.thje = thje;
	}

	@Column(name = "hkje", precision = 18, scale = 4)
	public BigDecimal getHkje() {
		return hkje;
	}
	
	public void setHkje(BigDecimal hkje) {
		this.hkje = hkje;
	}

	@Column(name = "jzsj", nullable = false, length = 10)
	public String getJzsj() {
		return jzsj;
	}

	public void setJzsj(String jzsj) {
		this.jzsj = jzsj;
	}
	
}
