package lnyswz.jxc.model;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TYwbtDet generated by hbm2java
 */
@Entity
@Table(name = "t_ywbt_det")
public class TYwbtDet implements java.io.Serializable {

	private int id;
	private TYwbt TYwbt;
	private String spbh;
	private String spmc;
	private String spcd;
	private String sppp;
	private String spbz;
	private String zjldwId;
	private String zjldwmc;
	private BigDecimal spje;
	private BigDecimal qdwcb;
	private BigDecimal dwcb;

	public TYwbtDet() {
	}

	public TYwbtDet(int id, TYwbt TYwbt, String spbh, String spmc, String spcd, String sppp, 
			String spbz, String zjldwId, String zjldwmc, BigDecimal spje, BigDecimal qdwcb, BigDecimal dwcb) {
		this.id = id;
		this.TYwbt = TYwbt;
		this.spbh = spbh;
		this.spmc = spmc;
		this.spcd = spcd;
		this.sppp = sppp;
		this.spbz = spbz;
		this.zjldwId = zjldwId;
		this.zjldwmc = zjldwmc;
		this.spje = spje;
		this.qdwcb = qdwcb;
		this.dwcb = dwcb;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ywbtlsh")
	public TYwbt getTYwbt() {
		return this.TYwbt;
	}

	public void setTYwbt(TYwbt TYwbt) {
		this.TYwbt = TYwbt;
	}

	@Column(name = "spbh", nullable = false, length = 7)
	public String getSpbh() {
		return spbh;
	}

	public void setSpbh(String spbh) {
		this.spbh = spbh;
	}

	@Column(name = "spmc", nullable = false, length = 100)
	public String getSpmc() {
		return spmc;
	}

	public void setSpmc(String spmc) {
		this.spmc = spmc;
	}

	@Column(name = "spcd", nullable = false, length = 20)
	public String getSpcd() {
		return spcd;
	}

	public void setSpcd(String spcd) {
		this.spcd = spcd;
	}

	@Column(name = "sppp", length = 20)
	public String getSppp() {
		return sppp;
	}

	public void setSppp(String sppp) {
		this.sppp = sppp;
	}

	@Column(name = "spbz", length = 20)
	public String getSpbz() {
		return spbz;
	}

	public void setSpbz(String spbz) {
		this.spbz = spbz;
	}

	@Column(name = "zjldwId", nullable = false, length = 2)
	public String getZjldwId() {
		return zjldwId;
	}

	public void setZjldwId(String zjldwId) {
		this.zjldwId = zjldwId;
	}

	@Column(name = "zjldwmc", nullable = false, length = 20)
	public String getZjldwmc() {
		return zjldwmc;
	}

	public void setZjldwmc(String zjldwmc) {
		this.zjldwmc = zjldwmc;
	}

	@Column(name = "spje", nullable = false, precision = 18, scale = 4)
	public BigDecimal getSpje() {
		return this.spje;
	}

	public void setSpje(BigDecimal spje) {
		this.spje = spje;
	}
	
	@Column(name = "qdwcb", nullable = false, precision = 18, scale = 4)
	public BigDecimal getQdwcb() {
		return this.qdwcb;
	}
	
	public void setQdwcb(BigDecimal qdwcb) {
		this.qdwcb = qdwcb;
	}
	
	@Column(name = "dwcb", nullable = false, precision = 18, scale = 4)
	public BigDecimal getDwcb() {
		return this.dwcb;
	}
	
	public void setDwcb(BigDecimal dwcb) {
		this.dwcb = dwcb;
	}

}
