package lnyswz.jxc.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TYwdb generated by hbm2java
 */
@Entity
@Table(name = "t_ywdb")
public class TYwdb implements java.io.Serializable {

	private String ywdblsh;
	private Date createTime;
	private int createId;
	private String createName;
	private String bmbh;
	private String bmmc;
	private String ckIdF;
	private String ckmcF;
	private String ckIdT;
	private String ckmcT;
	private String bz;
	private String cjYwdblsh;
	private String isCj;
	private Date cjTime;
	private Integer cjId;
	private String cjName;
	private String cgxqlsh;
	
	private Set<TYwdbDet> TYwdbDets = new HashSet<TYwdbDet>(0);
	
	public TYwdb() {
	}

	public TYwdb(String ywdblsh, Date createTime, int createId, String createName, String bmbh, String bmmc, String ckIdF, String ckmcF, 
			String ckIdT, String ckmcT, String bz, String cjYwdblsh, String isCj, Date cjTime, Integer cjId, String cjName,	String cgxqlsh, 
			Set<TYwdbDet> TYwdbDets) {
		this.ywdblsh = ywdblsh;
		this.createTime = createTime;
		this.createId = createId;
		this.createName = createName;
		this.bmbh = bmbh;
		this.bmmc = bmmc;
		this.ckIdF = ckIdF;
		this.ckmcF = ckmcF;
		this.ckIdT = ckIdT;
		this.ckmcT = ckmcT;
		this.bz = bz;
		this.cjYwdblsh = cjYwdblsh;
		this.isCj = isCj;
		this.cjTime = cjTime;
		this.cjId = cjId;
		this.cjName = cjName;
		this.cgxqlsh = cgxqlsh;
		this.TYwdbDets = TYwdbDets;
	}

	@Id
	@Column(name = "ywdblsh", unique = true, nullable = false, length = 12)
	public String getYwdblsh() {
		return this.ywdblsh;
	}

	public void setYwdblsh(String ywdblsh) {
		this.ywdblsh = ywdblsh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 23)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createId", nullable = false)
	public int getCreateId() {
		return this.createId;
	}

	public void setCreateId(int createId) {
		this.createId = createId;
	}

	@Column(name = "createName", nullable = false, length = 20)
	public String getCreateName() {
		return createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	@Column(name = "bmbh", nullable = false, length = 2)
	public String getBmbh() {
		return this.bmbh;
	}

	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}

	@Column(name = "bmmc", nullable = false, length = 20)
	public String getBmmc() {
		return bmmc;
	}

	public void setBmmc(String bmmc) {
		this.bmmc = bmmc;
	}

	@Column(name = "ckIdF", nullable = false, length = 2)
	public String getCkIdF() {
		return ckIdF;
	}

	public void setCkIdF(String ckIdF) {
		this.ckIdF = ckIdF;
	}

	@Column(name = "ckmcF", nullable = false, length = 20)
	public String getCkmcF() {
		return ckmcF;
	}

	public void setCkmcF(String ckmcF) {
		this.ckmcF = ckmcF;
	}
	
	@Column(name = "ckIdT", nullable = false, length = 2)
	public String getCkIdT() {
		return ckIdT;
	}

	public void setCkIdT(String ckIdT) {
		this.ckIdT = ckIdT;
	}

	@Column(name = "ckmcT", nullable = false, length = 20)
	public String getCkmcT() {
		return ckmcT;
	}

	public void setCkmcT(String ckmcT) {
		this.ckmcT = ckmcT;
	}
	
	@Column(name = "bz", length = 50)
	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	@Column(name = "cjYwdblsh", nullable = true, length = 12)
	public String getCjYwdblsh() {
		return cjYwdblsh;
	}

	public void setCjYwdblsh(String cjYwdblsh) {
		this.cjYwdblsh = cjYwdblsh;
	}

	@Column(name = "isCj", length = 1)
	public String getIsCj() {
		return this.isCj;
	}

	public void setIsCj(String isCj) {
		this.isCj = isCj;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cjTime", length = 23)
	public Date getCjTime() {
		return this.cjTime;
	}

	public void setCjTime(Date cjTime) {
		this.cjTime = cjTime;
	}

	@Column(name = "cjId")
	public Integer getCjId() {
		return this.cjId;
	}

	public void setCjId(Integer cjId) {
		this.cjId = cjId;
	}

	@Column(name = "cjName", length = 20)
	public String getCjName() {
		return cjName;
	}

	public void setCjName(String cjName) {
		this.cjName = cjName;
	}

	@Column(name = "cgxqlsh", length = 12)
	public String getCgxqlsh() {
		return cgxqlsh;
	}

	public void setCgxqlsh(String cgxqlsh) {
		this.cgxqlsh = cgxqlsh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TYwdb", cascade=CascadeType.ALL)
	public Set<TYwdbDet> getTYwdbDets() {
		return this.TYwdbDets;
	}

	public void setTYwdbDets(Set<TYwdbDet> TYwdbDets) {
		this.TYwdbDets = TYwdbDets;
	}
	
}
