package lnyswz.jxc.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TYwhs generated by hbm2java
 */
@Entity
@Table(name = "t_ywhs")
public class TYwhs implements java.io.Serializable {

	private String ywhslsh;
	private int createId;
	private Date createTime;
	private String createName;
	private String bmbh;
	private String bmmc;
	private String ckId;
	private String ckmc;
	private String fhId;
	private String fhmc;
	private BigDecimal hjje;
	private String bz;
	private String cjYwhslsh;
	private String isCj;
	private Integer cjId;
	private Date cjTime;
	private String cjName;
	private Set<TYwhsDet> TYwhsDets = new HashSet<TYwhsDet>(0);
	
	private TKfhs TKfhs;
	
	public TYwhs() {
	}

	public TYwhs(String ywhslsh, int createId, Date createTime,  String createName, String bmbh, String bmmc,
			String ckId, String ckmc, String fhId, String fhmc, BigDecimal hjje, String bz,
			String isCj, Date cjTime, Integer cjId, String cjName, Set<TYwhsDet> TYwhsDets, TKfhs TKfhs) {
		this.ywhslsh = ywhslsh;
		this.createTime = createTime;
		this.createId = createId;
		this.createName = createName;
		this.bmbh = bmbh;
		this.bmmc = bmmc;
		this.ckId = ckId;
		this.ckmc = ckmc;
		this.hjje = hjje;
		this.bz = bz;
		this.isCj = isCj;
		this.cjId = cjId;
		this.cjTime = cjTime;
		this.cjName = cjName;
		this.TYwhsDets = TYwhsDets;
		this.TKfhs = TKfhs;
	}

	@Id
	@Column(name = "ywhslsh", unique = true, nullable = false, length = 12)
	public String getYwhslsh() {
		return this.ywhslsh;
	}

	public void setYwhslsh(String ywhslsh) {
		this.ywhslsh = ywhslsh;
	}

	@Column(name = "createId", nullable = false)
	public int getCreateId() {
		return this.createId;
	}
	
	public void setCreateId(int createId) {
		this.createId = createId;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 23)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createName", nullable = false, length = 20)
	public String getCreateName() {
		return createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	@Column(name = "bmbh", nullable = false, length = 2)
	public String getBmbh() {
		return this.bmbh;
	}

	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}

	@Column(name = "bmmc", nullable = false, length = 20)
	public String getBmmc() {
		return bmmc;
	}

	public void setBmmc(String bmmc) {
		this.bmmc = bmmc;
	}

	@Column(name = "ckId", nullable = false, length = 2)
	public String getCkId() {
		return ckId;
	}

	public void setCkId(String ckId) {
		this.ckId = ckId;
	}

	@Column(name = "ckmc", nullable = false, length = 20)
	public String getCkmc() {
		return ckmc;
	}

	public void setCkmc(String ckmc) {
		this.ckmc = ckmc;
	}
	
	@Column(name = "fhId", length = 2)
	public String getFhId() {
		return fhId;
	}

	public void setFhId(String fhId) {
		this.fhId = fhId;
	}

	@Column(name = "fhmc", length = 20)
	public String getFhmc() {
		return fhmc;
	}

	public void setFhmc(String fhmc) {
		this.fhmc = fhmc;
	}


	@Column(name = "hjje", precision = 18, scale = 4)
	public BigDecimal getHjje() {
		return this.hjje;
	}

	public void setHjje(BigDecimal hjje) {
		this.hjje = hjje;
	}

	@Column(name = "bz", length = 100)
	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	@Column(name = "cjYwhslsh", length = 12)
	public String getCjYwhslsh() {
		return cjYwhslsh;
	}

	public void setCjYwhslsh(String cjYwhslsh) {
		this.cjYwhslsh = cjYwhslsh;
	}

	@Column(name = "isCj", nullable = false, length = 1)
	public String getIsCj() {
		return this.isCj;
	}

	public void setIsCj(String isCj) {
		this.isCj = isCj;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cjTime", length = 23)
	public Date getCjTime() {
		return this.cjTime;
	}

	public void setCjTime(Date cjTime) {
		this.cjTime = cjTime;
	}

	@Column(name = "cjName", length = 20)
	public String getCjName() {
		return cjName;
	}

	public void setCjName(String cjName) {
		this.cjName = cjName;
	}

	@Column(name = "cjId")
	public Integer getCjId() {
		return this.cjId;
	}

	public void setCjId(Integer cjId) {
		this.cjId = cjId;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TYwhs", cascade=CascadeType.ALL)
	public Set<TYwhsDet> getTYwhsDets() {
		return this.TYwhsDets;
	}

	public void setTYwhsDets(Set<TYwhsDet> TYwhsDets) {
		this.TYwhsDets = TYwhsDets;
	}

	@OneToOne//表示一对一的关系
	@JoinColumn(name="kfhslsh")
	public TKfhs getTKfhs() {
		return TKfhs;
	}

	public void setTKfhs(TKfhs tKfhs) {
		TKfhs = tKfhs;
	}

}
