package lnyswz.jxc.model;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TYwhsDet generated by hbm2java
 */
@Entity
@Table(name = "t_ywhs_det")
public class TYwhsDet implements java.io.Serializable {

	private int id;
	private TYwhs TYwhs;
	private String zspbh;
	private String zspmc;
	private String zspcd;
	private String zsppp;
	private String zspbz;
	private String zzjldwId;
	private String zzjldwmc;
	private String zcjldwId;
	private String zcjldwmc;
	private BigDecimal zzhxs;
	private BigDecimal zzdwsl;
	private BigDecimal zcdwsl;
	private BigDecimal zzdwdj;
	private BigDecimal zspje;
	private BigDecimal zqdwcb;
	private BigDecimal zdwcb;
	private String zisZs;
	private String jspbh;
	private String jspmc;
	private String jspcd;
	private String jsppp;
	private String jspbz;
	private String jzjldwId;
	private String jzjldwmc;
	private String jcjldwId;
	private String jcjldwmc;
	private BigDecimal jzhxs;
	private BigDecimal jzdwsl;
	private BigDecimal jcdwsl;
	private BigDecimal jzdwdj;
	private BigDecimal jspje;
	private BigDecimal jqdwcb;
	private BigDecimal jdwcb;
	private String jisZs;

	public TYwhsDet() {
	}

	public TYwhsDet(int id, TYwhs TYwhs, 
			String zspbh, String zspmc, String zspcd, String zsppp, String zspbz, String zzjldwId, String zzjldwmc, 
			String zcjldwId, String zcjldwmc, BigDecimal zzhxs, BigDecimal zzdwsl, BigDecimal zcdwsl, BigDecimal zzdwdj, 
			BigDecimal zspje, BigDecimal zqdwcb, BigDecimal zdwcb, String zisZs, String jspbh, String jspmc, String jspcd, 
			String jsppp, String jspbz, String jzjldwId, String jzjldwmc, String jcjldwId, String jcjldwmc, BigDecimal jzhxs,
			BigDecimal jzdwsl, BigDecimal jcdwsl, BigDecimal jzdwdj, BigDecimal jspje, BigDecimal jqdwcb, BigDecimal jdwcb, 
			String jisZs) {
		this.id = id;
		this.TYwhs = TYwhs;
		this.zspbh = zspbh;
		this.zspmc = zspmc;
		this.zspcd = zspcd;
		this.zsppp = zsppp;
		this.zspbz = zspbz;
		this.zzjldwId = zzjldwId;
		this.zzjldwmc = zzjldwmc;
		this.zcjldwId = zcjldwId;
		this.zcjldwmc = zcjldwmc;
		this.zzhxs = zzhxs;
		this.zzdwsl = zzdwsl;
		this.zcdwsl = zcdwsl;
		this.zzdwdj = zzdwdj;
		this.zspje = zspje;
		this.zqdwcb = zqdwcb;
		this.zdwcb = zdwcb;
		this.zisZs = zisZs;
		this.jspbh = jspbh;
		this.jspmc = jspmc;
		this.jspcd = jspcd;
		this.jsppp = jsppp;
		this.jspbz = jspbz;
		this.jzjldwId = jzjldwId;
		this.jzjldwmc = jzjldwmc;
		this.jcjldwId = jcjldwId;
		this.jcjldwmc = jcjldwmc;
		this.jzhxs = jzhxs;
		this.jzdwsl = jzdwsl;
		this.jzdwdj = jzdwdj;
		this.jspje = jspje;
		this.jqdwcb = jqdwcb;
		this.jdwcb = jdwcb;
		this.jisZs = jisZs;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ywhslsh")
	public TYwhs getTYwhs() {
		return this.TYwhs;
	}

	public void setTYwhs(TYwhs TYwhs) {
		this.TYwhs = TYwhs;
	}

	@Column(name = "zspbh", nullable = false, length = 7)
	public String getZspbh() {
		return zspbh;
	}

	public void setZspbh(String zspbh) {
		this.zspbh = zspbh;
	}

	@Column(name = "zspmc", nullable = false, length = 100)
	public String getZspmc() {
		return zspmc;
	}

	public void setZspmc(String zspmc) {
		this.zspmc = zspmc;
	}

	@Column(name = "zspcd", nullable = false, length = 20)
	public String getZspcd() {
		return zspcd;
	}

	public void setZspcd(String zspcd) {
		this.zspcd = zspcd;
	}

	@Column(name = "zsppp", length = 20)
	public String getZsppp() {
		return zsppp;
	}

	public void setZsppp(String zsppp) {
		this.zsppp = zsppp;
	}

	@Column(name = "zspbz", length = 20)
	public String getZspbz() {
		return zspbz;
	}

	public void setZspbz(String zspbz) {
		this.zspbz = zspbz;
	}

	@Column(name = "zzjldwId", nullable = false, length = 2)
	public String getZzjldwId() {
		return zzjldwId;
	}

	public void setZzjldwId(String zzjldwId) {
		this.zzjldwId = zzjldwId;
	}

	@Column(name = "zzjldwmc", nullable = false, length = 20)
	public String getZzjldwmc() {
		return zzjldwmc;
	}

	public void setZzjldwmc(String zzjldwmc) {
		this.zzjldwmc = zzjldwmc;
	}

	@Column(name = "zcjldwId", nullable = false, length = 2)
	public String getZcjldwId() {
		return zcjldwId;
	}

	public void setZcjldwId(String zcjldwId) {
		this.zcjldwId = zcjldwId;
	}

	@Column(name = "zcjldwmc", nullable = false, length = 20)
	public String getZcjldwmc() {
		return zcjldwmc;
	}

	public void setZcjldwmc(String zcjldwmc) {
		this.zcjldwmc = zcjldwmc;
	}

	@Column(name = "zzhxs", nullable = false, precision = 18, scale = 3)
	public BigDecimal getZzhxs() {
		return zzhxs;
	}

	public void setZzhxs(BigDecimal zzhxs) {
		this.zzhxs = zzhxs;
	}

	@Column(name = "zzdwsl", nullable = false, precision = 18, scale = 3)
	public BigDecimal getZzdwsl() {
		return this.zzdwsl;
	}

	public void setZzdwsl(BigDecimal zzdwsl) {
		this.zzdwsl = zzdwsl;
	}

	@Column(name = "zcdwsl", nullable = false, precision = 18, scale = 3)
	public BigDecimal getZcdwsl() {
		return zcdwsl;
	}

	public void setZcdwsl(BigDecimal zcdwsl) {
		this.zcdwsl = zcdwsl;
	}

	@Column(name = "zzdwdj", nullable = false, precision = 18, scale = 4)
	public BigDecimal getZzdwdj() {
		return this.zzdwdj;
	}

	public void setZzdwdj(BigDecimal zzdwdj) {
		this.zzdwdj = zzdwdj;
	}

	@Column(name = "zspje", nullable = false, precision = 18, scale = 4)
	public BigDecimal getZspje() {
		return this.zspje;
	}

	public void setZspje(BigDecimal zspje) {
		this.zspje = zspje;
	}
	
	@Column(name = "zqdwcb", nullable = false, precision = 18, scale = 4)
	public BigDecimal getZqdwcb() {
		return this.zqdwcb;
	}
	
	public void setZqdwcb(BigDecimal zqdwcb) {
		this.zqdwcb = zqdwcb;
	}
	
	@Column(name = "zdwcb", nullable = false, precision = 18, scale = 4)
	public BigDecimal getZdwcb() {
		return this.zdwcb;
	}
	
	public void setZdwcb(BigDecimal zdwcb) {
		this.zdwcb = zdwcb;
	}
	
	@Column(name = "zisZs", nullable = false, length = 1)
	public String getZisZs() {
		return zisZs;
	}

	public void setZisZs(String zisZs) {
		this.zisZs = zisZs;
	}

	@Column(name = "jspbh", nullable = false, length = 7)
	public String getJspbh() {
		return jspbh;
	}
	
	public void setJspbh(String jspbh) {
		this.jspbh = jspbh;
	}
	
	@Column(name = "jspmc", nullable = false, length = 100)
	public String getJspmc() {
		return jspmc;
	}
	
	public void setJspmc(String jspmc) {
		this.jspmc = jspmc;
	}
	
	@Column(name = "jspcd", nullable = false, length = 20)
	public String getJspcd() {
		return jspcd;
	}
	
	public void setJspcd(String jspcd) {
		this.jspcd = jspcd;
	}
	
	@Column(name = "jsppp", length = 20)
	public String getJsppp() {
		return jsppp;
	}
	
	public void setJsppp(String jsppp) {
		this.jsppp = jsppp;
	}
	
	@Column(name = "jspbz", length = 20)
	public String getJspbz() {
		return jspbz;
	}
	
	public void setJspbz(String jspbz) {
		this.jspbz = jspbz;
	}
	
	@Column(name = "jzjldwId", nullable = false, length = 2)
	public String getJzjldwId() {
		return jzjldwId;
	}
	
	public void setJzjldwId(String jzjldwId) {
		this.jzjldwId = jzjldwId;
	}
	
	@Column(name = "jzjldwmc", nullable = false, length = 20)
	public String getJzjldwmc() {
		return jzjldwmc;
	}
	
	public void setJzjldwmc(String jzjldwmc) {
		this.jzjldwmc = jzjldwmc;
	}
	
	@Column(name = "jcjldwId", nullable = false, length = 2)
	public String getJcjldwId() {
		return jcjldwId;
	}

	public void setJcjldwId(String jcjldwId) {
		this.jcjldwId = jcjldwId;
	}

	@Column(name = "jcjldwmc", nullable = false, length = 20)
	public String getJcjldwmc() {
		return jcjldwmc;
	}

	public void setJcjldwmc(String jcjldwmc) {
		this.jcjldwmc = jcjldwmc;
	}

	@Column(name = "jzhxs", nullable = false, precision = 18, scale = 3)
	public BigDecimal getJzhxs() {
		return jzhxs;
	}

	public void setJzhxs(BigDecimal jzhxs) {
		this.jzhxs = jzhxs;
	}

	@Column(name = "jzdwsl", nullable = false, precision = 18, scale = 3)
	public BigDecimal getJzdwsl() {
		return this.jzdwsl;
	}
	
	public void setJzdwsl(BigDecimal jzdwsl) {
		this.jzdwsl = jzdwsl;
	}
	
	@Column(name = "jcdwsl", nullable = false, precision = 18, scale = 3)
	public BigDecimal getJcdwsl() {
		return jcdwsl;
	}

	public void setJcdwsl(BigDecimal jcdwsl) {
		this.jcdwsl = jcdwsl;
	}

	@Column(name = "jzdwdj", nullable = false, precision = 18, scale = 4)
	public BigDecimal getJzdwdj() {
		return this.jzdwdj;
	}
	
	public void setJzdwdj(BigDecimal jzdwdj) {
		this.jzdwdj = jzdwdj;
	}
	
	@Column(name = "jspje", nullable = false, precision = 18, scale = 4)
	public BigDecimal getJspje() {
		return this.jspje;
	}
	
	public void setJspje(BigDecimal jspje) {
		this.jspje = jspje;
	}
	
	@Column(name = "jqdwcb", nullable = false, precision = 18, scale = 4)
	public BigDecimal getJqdwcb() {
		return this.jqdwcb;
	}
	
	public void setJqdwcb(BigDecimal jqdwcb) {
		this.jqdwcb = jqdwcb;
	}
	
	@Column(name = "jdwcb", nullable = false, precision = 18, scale = 4)
	public BigDecimal getJdwcb() {
		return this.jdwcb;
	}
	
	public void setJdwcb(BigDecimal jdwcb) {
		this.jdwcb = jdwcb;
	}

	@Column(name = "jisZs", nullable = false, length = 1)
	public String getJisZs() {
		return jisZs;
	}

	public void setJisZs(String jisZs) {
		this.jisZs = jisZs;
	}

}
