package lnyswz.jxc.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * TYwpd generated by hbm2java
 */
@Entity
@Table(name = "t_ywpd")
public class TYwpd implements java.io.Serializable {

	private String ywpdlsh;
	private Date createTime;
	private int createId;
	private String createName;
	private String bmbh;
	private String bmmc;
	private String pdlxId;
	private String pdlxmc;
	private String ckId;
	private String ckmc;
	private String mc;
	private BigDecimal hjje;
	private String bz;
	private String cjYwpdlsh;
	private String isCj;
	private Date cjTime;
	private Integer cjId;
	private String cjName;
	private Set<TYwpdDet> TYwpdDets = new HashSet<TYwpdDet>(0);
	
	private TKfpd TKfpd;
	
	public TYwpd() {
	}

	public TYwpd(String ywpdlsh, int createId, Date createTime,  String createName, String bmbh, String bmmc,
			String mc, String pdlxId, String pdlxmc, String ckId, String ckmc, BigDecimal hjje, String bz,
			String isCj, Date cjTime, Integer cjId, String cjName, Set<TYwpdDet> TYwpdDets, TKfpd TKfpd) {
		this.ywpdlsh = ywpdlsh;
		this.createTime = createTime;
		this.createId = createId;
		this.createName = createName;
		this.bmbh = bmbh;
		this.bmmc = bmmc;
		this.pdlxId = pdlxId;
		this.pdlxmc = pdlxmc;
		this.ckId = ckId;
		this.ckmc = ckmc;
		this.mc = mc;
		this.hjje = hjje;
		this.bz = bz;
		this.isCj = isCj;
		this.cjId = cjId;
		this.cjTime = cjTime;
		this.cjName = cjName;
		this.TYwpdDets = TYwpdDets;
		this.TKfpd = TKfpd;
	}

	@Id
	@Column(name = "ywpdlsh", unique = true, nullable = false, length = 12)
	public String getYwpdlsh() {
		return this.ywpdlsh;
	}

	public void setYwpdlsh(String ywpdlsh) {
		this.ywpdlsh = ywpdlsh;
	}

	@Column(name = "createId", nullable = false)
	public int getCreateId() {
		return this.createId;
	}
	
	public void setCreateId(int createId) {
		this.createId = createId;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 23)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createName", nullable = false, length = 20)
	public String getCreateName() {
		return createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	@Column(name = "bmbh", nullable = false, length = 2)
	public String getBmbh() {
		return this.bmbh;
	}

	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}

	@Column(name = "bmmc", nullable = false, length = 20)
	public String getBmmc() {
		return bmmc;
	}

	public void setBmmc(String bmmc) {
		this.bmmc = bmmc;
	}

	@Column(name = "mc", nullable = false, length = 100)
	public String getMc() {
		return mc;
	}

	public void setMc(String mc) {
		this.mc = mc;
	}

	@Column(name = "pdlxId", nullable = false, length = 2)
	public String getPdlxId() {
		return this.pdlxId;
	}

	public void setPdlxId(String pdlxId) {
		this.pdlxId = pdlxId;
	}

	@Column(name = "pdlxmc", nullable = false, length = 20)
	public String getPdlxmc() {
		return pdlxmc;
	}

	public void setPdlxmc(String pdlxmc) {
		this.pdlxmc = pdlxmc;
	}

	@Column(name = "ckId", nullable = false, length = 2)
	public String getCkId() {
		return ckId;
	}

	public void setCkId(String ckId) {
		this.ckId = ckId;
	}

	@Column(name = "ckmc", nullable = false, length = 20)
	public String getCkmc() {
		return ckmc;
	}

	public void setCkmc(String ckmc) {
		this.ckmc = ckmc;
	}

	@Column(name = "hjje", precision = 18, scale = 4)
	public BigDecimal getHjje() {
		return this.hjje;
	}

	public void setHjje(BigDecimal hjje) {
		this.hjje = hjje;
	}

	@Column(name = "bz", length = 100)
	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	@Column(name = "cjYwpdlsh", length = 12)
	public String getCjYwpdlsh() {
		return cjYwpdlsh;
	}

	public void setCjYwpdlsh(String cjYwpdlsh) {
		this.cjYwpdlsh = cjYwpdlsh;
	}

	@Column(name = "isCj", nullable = false, length = 1)
	public String getIsCj() {
		return this.isCj;
	}

	public void setIsCj(String isCj) {
		this.isCj = isCj;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cjTime", length = 23)
	public Date getCjTime() {
		return this.cjTime;
	}

	public void setCjTime(Date cjTime) {
		this.cjTime = cjTime;
	}

	@Column(name = "cjName", length = 20)
	public String getCjName() {
		return cjName;
	}

	public void setCjName(String cjName) {
		this.cjName = cjName;
	}

	@Column(name = "cjId")
	public Integer getCjId() {
		return this.cjId;
	}

	public void setCjId(Integer cjId) {
		this.cjId = cjId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TYwpd", cascade=CascadeType.ALL)
	public Set<TYwpdDet> getTYwpdDets() {
		return this.TYwpdDets;
	}

	public void setTYwpdDets(Set<TYwpdDet> TYwpdDets) {
		this.TYwpdDets = TYwpdDets;
	}

	@OneToOne//表示一对一的关系
	@JoinColumn(name="kfpdlsh")
	public TKfpd getTKfpd() {
		return TKfpd;
	}

	public void setTKfpd(TKfpd tKfpd) {
		TKfpd = tKfpd;
	}
	
}
