package lnyswz.jxc.model;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TYwrkGys generated by hbm2java
 */
@Entity
@Table(name = "t_ywrk_gys")
public class TYwrkGys implements java.io.Serializable {

	private long id;
	private String ywrklsh;
	private String gysbh;
	private String gysmc;
	private BigDecimal hjje;
	private BigDecimal fkje;
	private BigDecimal yfje;
	private String bz;

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "ywrklsh", nullable = false, length = 12)
	public String getYwrklsh() {
		return this.ywrklsh;
	}

	public void setYwrklsh(String ywrklsh) {
		this.ywrklsh = ywrklsh;
	}

	@Column(name = "gysbh", nullable = false, length = 8)
	public String getGysbh() {
		return gysbh;
	}

	public void setGysbh(String gysbh) {
		this.gysbh = gysbh;
	}

	@Column(name = "gysmc", nullable = false, length = 100)
	public String getGysmc() {
		return gysmc;
	}

	public void setGysmc(String gysmc) {
		this.gysmc = gysmc;
	}

	@Column(name = "hjje", precision = 18, scale = 4)
	public BigDecimal getHjje() {
		return this.hjje;
	}

	public void setHjje(BigDecimal hjje) {
		this.hjje = hjje;
	}

	@Column(name = "fkje", precision = 18, scale = 2)
	public BigDecimal getFkje() {
		return fkje;
	}

	public void setFkje(BigDecimal fkje) {
		this.fkje = fkje;
	}

	@Column(name = "yfje", precision = 18, scale = 2)
	public BigDecimal getYfje() {
		return yfje;
	}

	public void setYfje(BigDecimal yfje) {
		this.yfje = yfje;
	}

	@Column(name = "bz", length = 100)
	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}
}
