package lnyswz.jxc.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * TYwrk generated by hbm2java
 */
@Entity
@Table(name = "t_ywrk")
public class TYwrk implements java.io.Serializable {

	private String ywrklsh;
	private int createId;
	private Date createTime;
	private String createName;
	private String bmbh;
	private String bmmc;
	private String gysbh;
	private String gysmc;
	private String rklxId;
	private String rklxmc;
	private String ckId;
	private String ckmc;
	private BigDecimal hjje;
	private BigDecimal fkje;
	private String bz;
	private String cjYwrklsh;
	private String isCj;
	private Integer cjId;
	private Date cjTime;
	private String cjName;
	private String isZs;
	private String shdz;
	private String isDep;
	private String depId;
	private String depName;
	private String beYwrklsh;
	private Date fpDate;
	private Set<TYwrkDet> TYwrkDets = new HashSet<TYwrkDet>(0);
	private Set<TKfrk> TKfrks = new HashSet<TKfrk>(0);
	
	private Set<TCgjhDet> TCgjhs = new HashSet<TCgjhDet>(0);
	
	private TYwbt TYwbt;
	private TXskp TXskp;
	
	public TYwrk() {
	}

	public TYwrk(String ywrklsh, int createId, Date createTime,  String createName, String bmbh, String bmmc,
			String gysbh, String gysmc, String rklxId, String rklxmc, String ckId, String ckmc, BigDecimal hjje, BigDecimal fkje, String bz,
			String isCj, Date cjTime, Integer cjId, String cjName, String isZs, String isDep, String depId, String depName,
			String beYwrklsh, Date fpDate, Set<TYwrkDet> TYwrkDets, Set<TKfrk> TKfrks, Set<TCgjhDet> TCgjhs, TYwbt TYwbt, TXskp TXskp) {
		this.ywrklsh = ywrklsh;
		this.createTime = createTime;
		this.createId = createId;
		this.createName = createName;
		this.bmbh = bmbh;
		this.bmmc = bmmc;
		this.gysbh = gysbh;
		this.gysmc = gysmc;
		this.rklxId = rklxId;
		this.rklxmc = rklxmc;
		this.ckId = ckId;
		this.ckmc = ckmc;
		this.hjje = hjje;
		this.fkje = fkje;
		this.bz = bz;
		this.isCj = isCj;
		this.cjId = cjId;
		this.cjTime = cjTime;
		this.cjName = cjName;
		this.isZs = isZs;
		this.isDep = isDep;
		this.depId = depId;
		this.depName = depName;
		this.beYwrklsh = beYwrklsh;
		this.fpDate = fpDate;
		this.TYwrkDets = TYwrkDets;
		this.TKfrks = TKfrks;
		this.TCgjhs = TCgjhs;
		this.TYwbt = TYwbt;
		this.TXskp = TXskp;
	}

	@Id
	@Column(name = "ywrklsh", unique = true, nullable = false, length = 12)
	public String getYwrklsh() {
		return this.ywrklsh;
	}

	public void setYwrklsh(String ywrklsh) {
		this.ywrklsh = ywrklsh;
	}

	@Column(name = "createId", nullable = false)
	public int getCreateId() {
		return this.createId;
	}
	
	public void setCreateId(int createId) {
		this.createId = createId;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 23)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createName", nullable = false, length = 20)
	public String getCreateName() {
		return createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	@Column(name = "bmbh", nullable = false, length = 2)
	public String getBmbh() {
		return this.bmbh;
	}

	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}

	@Column(name = "bmmc", nullable = false, length = 20)
	public String getBmmc() {
		return bmmc;
	}

	public void setBmmc(String bmmc) {
		this.bmmc = bmmc;
	}

	@Column(name = "gysbh", nullable = false, length = 8)
	public String getGysbh() {
		return gysbh;
	}

	public void setGysbh(String gysbh) {
		this.gysbh = gysbh;
	}

	@Column(name = "gysmc", nullable = false, length = 100)
	public String getGysmc() {
		return gysmc;
	}

	public void setGysmc(String gysmc) {
		this.gysmc = gysmc;
	}

	@Column(name = "rklxId", nullable = false, length = 2)
	public String getRklxId() {
		return this.rklxId;
	}

	public void setRklxId(String rklxId) {
		this.rklxId = rklxId;
	}

	@Column(name = "rklxmc", nullable = false, length = 20)
	public String getRklxmc() {
		return rklxmc;
	}

	public void setRklxmc(String rklxmc) {
		this.rklxmc = rklxmc;
	}

	@Column(name = "ckId", nullable = false, length = 2)
	public String getCkId() {
		return ckId;
	}

	public void setCkId(String ckId) {
		this.ckId = ckId;
	}

	@Column(name = "ckmc", nullable = false, length = 20)
	public String getCkmc() {
		return ckmc;
	}

	public void setCkmc(String ckmc) {
		this.ckmc = ckmc;
	}

	@Column(name = "hjje", precision = 18, scale = 4)
	public BigDecimal getHjje() {
		return this.hjje;
	}

	public void setHjje(BigDecimal hjje) {
		this.hjje = hjje;
	}

	@Column(name = "fkje", precision = 18, scale = 4)
	public BigDecimal getFkje() {
		return fkje;
	}

	public void setFkje(BigDecimal fkje) {
		this.fkje = fkje;
	}

	@Column(name = "bz", length = 100)
	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	@Column(name = "cjYwrklsh", length = 12)
	public String getCjYwrklsh() {
		return cjYwrklsh;
	}

	public void setCjYwrklsh(String cjYwrklsh) {
		this.cjYwrklsh = cjYwrklsh;
	}

	@Column(name = "isCj", nullable = false, length = 1)
	public String getIsCj() {
		return this.isCj;
	}

	public void setIsCj(String isCj) {
		this.isCj = isCj;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cjTime", length = 23)
	public Date getCjTime() {
		return this.cjTime;
	}

	public void setCjTime(Date cjTime) {
		this.cjTime = cjTime;
	}

	@Column(name = "cjName", length = 20)
	public String getCjName() {
		return cjName;
	}

	public void setCjName(String cjName) {
		this.cjName = cjName;
	}

	@Column(name = "cjId")
	public Integer getCjId() {
		return this.cjId;
	}

	public void setCjId(Integer cjId) {
		this.cjId = cjId;
	}
	
	@Column(name = "isZs", nullable = false, length = 1)
	public String getIsZs() {
		return isZs;
	}

	public void setIsZs(String isZs) {
		this.isZs = isZs;
	}

	public String getShdz() {
		return shdz;
	}

	public void setShdz(String shdz) {
		this.shdz = shdz;
	}

	@Column(name = "isDep", nullable = false, length = 1)
	public String getIsDep() {
		return isDep;
	}

	public void setIsDep(String isDep) {
		this.isDep = isDep;
	}

	@Column(name = "depId", length = 2)
	public String getDepId() {
		return depId;
	}

	public void setDepId(String depId) {
		this.depId = depId;
	}

	@Column(name = "depName", length = 20)
	public String getDepName() {
		return depName;
	}

	public void setDepName(String depName) {
		this.depName = depName;
	}

	@Column(name = "beYwrklsh", length = 12)
	public String getBeYwrklsh() {
		return beYwrklsh;
	}

	public void setBeYwrklsh(String beYwrklsh) {
		this.beYwrklsh = beYwrklsh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fpDate", length = 23)
	public Date getFpDate() {
		return fpDate;
	}

	public void setFpDate(Date fpDate) {
		this.fpDate = fpDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TYwrk", cascade=CascadeType.ALL)
	public Set<TYwrkDet> getTYwrkDets() {
		return this.TYwrkDets;
	}

	public void setTYwrkDets(Set<TYwrkDet> TYwrkDets) {
		this.TYwrkDets = TYwrkDets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TYwrk")
	public Set<TKfrk> getTKfrks() {
		return TKfrks;
	}

	public void setTKfrks(Set<TKfrk> tKfrks) {
		TKfrks = tKfrks;
	}
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_cgjh_ywrk", joinColumns = { @JoinColumn(name = "ywrklsh", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "cgjhdetId", nullable = false, updatable = false) })
	public Set<TCgjhDet> getTCgjhs() {
		return this.TCgjhs;
	}

	public void setTCgjhs(Set<TCgjhDet> TCgjhs) {
		this.TCgjhs = TCgjhs;
	}

	@OneToOne//表示一对一的关系
	@JoinColumn(name="ywbtlsh")
	public TYwbt getTYwbt() {
		return TYwbt;
	}

	public void setTYwbt(TYwbt tYwbt) {
		TYwbt = tYwbt;
	}

	@OneToOne(mappedBy="TYwrk", fetch = FetchType.LAZY)
	@Fetch(FetchMode.JOIN)
	public TXskp getTXskp() {
		return TXskp;
	}

	public void setTXskp(TXskp tXskp) {
		TXskp = tXskp;
	}
	
}
