package lnyswz.jxc.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TYwsh generated by hbm2java
 */
@Entity
@Table(name = "t_ywsh")
public class TYwsh implements java.io.Serializable {

	private long id;
	private String lsh;
	private Date createTime;
	private int createId;
	private String createName;
	private String auditLevel;
	private String isAudit;
	private String bz;
	
	public TYwsh() {
	}
	
	public TYwsh(long id, String lsh, Date createTime, int createId,
			String createName, String auditLevel, String isAudit, String bz) {
		super();
		this.id = id;
		this.lsh = lsh;
		this.createTime = createTime;
		this.createId = createId;
		this.createName = createName;
		this.auditLevel = auditLevel;
		this.isAudit = isAudit;
		this.bz = bz;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "lsh", nullable = false, length = 12)
	public String getLsh() {
		return lsh;
	}

	public void setLsh(String lsh) {
		this.lsh = lsh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 23)
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createId", nullable = false)
	public int getCreateId() {
		return createId;
	}

	public void setCreateId(int createId) {
		this.createId = createId;
	}

	@Column(name = "createName", nullable = false, length = 20)
	public String getCreateName() {
		return createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	@Column(name = "auditLevel", nullable = false, length = 1)
	public String getAuditLevel() {
		return auditLevel;
	}

	public void setAuditLevel(String auditLevel) {
		this.auditLevel = auditLevel;
	}

	@Column(name = "isAudit", nullable = false, length = 1)
	public String getIsAudit() {
		return isAudit;
	}

	public void setIsAudit(String isAudit) {
		this.isAudit = isAudit;
	}

	@Column(name = "bz", length = 200)
	public String getBz() {
		return bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}
	
}
