package lnyswz.jxc.model;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TYwzz generated by hbm2java
 */
@Entity
@Table(name = "t_ywzz")
public class TYwzz implements java.io.Serializable {

	private int id;
	private String jzsj;
	private String bmbh;
	private String bmmc;
	private String ckId;
	private String ckmc;
	private String spbh;
	private String spmc;
	private String spcd;
	private String sppp;
	private String spbz;
	private String zjldwId;
	private String zjldwmc;
	private String cjldwId;
	private String cjldwmc;
	private BigDecimal zhxs;
	private BigDecimal qcsl;
	private BigDecimal qcje;
	private BigDecimal dwcb;
	private BigDecimal rksl;
	private BigDecimal rkje;
	private BigDecimal xssl;
	private BigDecimal xsje;
	private BigDecimal xsse;
	private BigDecimal xscb;

	public TYwzz() {
	}

	public TYwzz(int id, String jzsj, String bmbh, String bmmc, String ckId, String ckmc,
			String spbh, String spmc, String spcd, String sppp,	String spbz, String zjldwId,
			String zjldwmc, String cjldwId, String cjldwmc,	BigDecimal zhxs, BigDecimal qcsl,
			BigDecimal qcje, BigDecimal dwcb, BigDecimal rksl, BigDecimal rkje, BigDecimal xssl,
			BigDecimal xsje, BigDecimal xsse, BigDecimal xscb) {
		this.id = id;
		this.jzsj = jzsj;
		this.bmbh = bmbh;
		this.bmmc = bmmc;
		this.ckId = ckId;
		this.ckmc = ckmc;
		this.spbh = spbh;
		this.spmc = spmc;
		this.spcd = spcd;
		this.sppp = sppp;
		this.spbz = spbz;
		this.zjldwId = zjldwId;
		this.zjldwmc = zjldwmc;
		this.cjldwId = cjldwId;
		this.cjldwmc = cjldwmc;
		this.zhxs = zhxs;
		this.qcsl = qcsl;
		this.qcje = qcje;
		this.dwcb = dwcb;
		this.rksl = rksl;
		this.rkje = rkje;
		this.xssl = xssl;
		this.xsje = xsje;
		this.xscb = xscb;
		this.xsse = xsse;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "jzsj", nullable = false, length = 6)
	public String getJzsj() {
		return this.jzsj;
	}
	
	public void setJzsj(String jzsj) {
		this.jzsj = jzsj;
	}


	@Column(name = "bmbh", nullable = false, length = 2)
	public String getBmbh() {
		return this.bmbh;
	}
	
	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}
	
	@Column(name = "bmmc", nullable = false, length = 20)
	public String getBmmc() {
		return this.bmmc;
	}
	
	public void setBmmc(String bmmc) {
		this.bmmc = bmmc;
	}
	
	@Column(name = "ckId", length = 2)
	public String getCkId() {
		return ckId;
	}
	
	public void setCkId(String ckId) {
		this.ckId = ckId;
	}
	
	@Column(name = "ckmc", length = 20)
	public String getCkmc() {
		return ckmc;
	}
	
	public void setCkmc(String ckmc) {
		this.ckmc = ckmc;
	}
	
	@Column(name = "spbh", nullable = false, length = 7)
	public String getSpbh() {
		return spbh;
	}

	public void setSpbh(String spbh) {
		this.spbh = spbh;
	}

	@Column(name = "spmc", nullable = false, length = 100)
	public String getSpmc() {
		return spmc;
	}

	public void setSpmc(String spmc) {
		this.spmc = spmc;
	}

	@Column(name = "spcd", nullable = false, length = 20)
	public String getSpcd() {
		return spcd;
	}

	public void setSpcd(String spcd) {
		this.spcd = spcd;
	}

	@Column(name = "sppp", length = 20)
	public String getSppp() {
		return sppp;
	}

	public void setSppp(String sppp) {
		this.sppp = sppp;
	}

	@Column(name = "spbz", length = 20)
	public String getSpbz() {
		return spbz;
	}

	public void setSpbz(String spbz) {
		this.spbz = spbz;
	}

	@Column(name = "zjldwId", nullable = false, length = 2)
	public String getZjldwId() {
		return zjldwId;
	}

	public void setZjldwId(String zjldwId) {
		this.zjldwId = zjldwId;
	}

	@Column(name = "zjldwmc", nullable = false, length = 20)
	public String getZjldwmc() {
		return zjldwmc;
	}

	public void setZjldwmc(String zjldwmc) {
		this.zjldwmc = zjldwmc;
	}

	@Column(name = "cjldwId", length = 2)
	public String getCjldwId() {
		return cjldwId;
	}

	public void setCjldwId(String cjldwId) {
		this.cjldwId = cjldwId;
	}

	@Column(name = "cjldwmc", length = 20)
	public String getCjldwmc() {
		return cjldwmc;
	}

	public void setCjldwmc(String cjldwmc) {
		this.cjldwmc = cjldwmc;
	}

	@Column(name = "zhxs", nullable = false, precision = 18, scale = 3)
	public BigDecimal getZhxs() {
		return zhxs;
	}

	public void setZhxs(BigDecimal zhxs) {
		this.zhxs = zhxs;
	}

	@Column(name = "qcsl", nullable = false, precision = 18, scale = 3)
	public BigDecimal getQcsl() {
		return this.qcsl;
	}

	public void setQcsl(BigDecimal qcsl) {
		this.qcsl = qcsl;
	}

	@Column(name = "qcje", nullable = false, precision = 18, scale = 4)
	public BigDecimal getQcje() {
		return qcje;
	}

	public void setQcje(BigDecimal qcje) {
		this.qcje = qcje;
	}

	@Column(name = "dwcb", nullable = false, precision = 18, scale = 4)
	public BigDecimal getDwcb() {
		return dwcb;
	}

	public void setDwcb(BigDecimal dwcb) {
		this.dwcb = dwcb;
	}

	@Column(name = "rksl", nullable = false, precision = 18, scale = 3)
	public BigDecimal getRksl() {
		return this.rksl;
	}

	public void setRksl(BigDecimal rksl) {
		this.rksl = rksl;
	}

	@Column(name = "rkje", nullable = false, precision = 18, scale = 4)
	public BigDecimal getRkje() {
		return rkje;
	}

	public void setRkje(BigDecimal rkje) {
		this.rkje = rkje;
	}

	@Column(name = "xssl", nullable = false, precision = 18, scale = 3)
	public BigDecimal getXssl() {
		return xssl;
	}

	public void setXssl(BigDecimal xssl) {
		this.xssl = xssl;
	}

	@Column(name = "xsje", nullable = false, precision = 18, scale = 4)
	public BigDecimal getXsje() {
		return xsje;
	}

	public void setXsje(BigDecimal xsje) {
		this.xsje = xsje;
	}

	@Column(name = "xsse", nullable = false, precision = 18, scale = 4)
	public BigDecimal getXsse() {
		return xsse;
	}

	public void setXsse(BigDecimal xsse) {
		this.xsse = xsse;
	}

	@Column(name = "xscb", nullable = false, precision = 18, scale = 4)
	public BigDecimal getXscb() {
		return xscb;
	}

	public void setXscb(BigDecimal xscb) {
		this.xscb = xscb;
	}
}
