package lnyswz.jxc.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * TZsqr generated by hbm2java
 */
@Entity
@Table(name = "t_zsqr")
public class TZsqr implements java.io.Serializable {

	private int id;
	private String xsthlsh;
	private String spbh;
	private BigDecimal qrsl;
	private int createId;
	private String createName;
	private Date createTime;
	
	public TZsqr() {
	}

	public TZsqr(int id, String xsthlsh, String spbh, BigDecimal qrsl, int createId, String createName, Date createTime) {
		this.id = id;
		this.xsthlsh = xsthlsh;
		this.spbh = spbh;
		this.qrsl = qrsl;
		this.createId = createId;
		this.createName = createName;
		this.createTime = createTime;
		
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "xsthlsh", nullable = false, length = 12)
	public String getXsthlsh() {
		return this.xsthlsh;
	}

	public void setXsthlsh(String xsthlsh) {
		this.xsthlsh = xsthlsh;
	}
	
	@Column(name = "spbh", nullable = false, length = 7)
	public String getSpbh() {
		return spbh;
	}

	public void setSpbh(String spbh) {
		this.spbh = spbh;
	}

	@Column(name = "qrsl", nullable = false, precision = 18, scale = 3)
	public BigDecimal getQrsl() {
		return qrsl;
	}

	public void setQrsl(BigDecimal qrsl) {
		this.qrsl = qrsl;
	}

	@Column(name = "createId", nullable = false)
	public int getCreateId() {
		return this.createId;
	}
	
	public void setCreateId(int createId) {
		this.createId = createId;
	}
	
	@Column(name = "createName", nullable = false, length = 50)
	public String getCreateName() {
		return this.createName;
	}
	
	public void setCreateName(String createName) {
		this.createName = createName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 23)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}
