package lnyswz.jxc.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VCgxq generated by hbm2java
 */
@Entity
@Table(name = "v_cgxq")
public class VCgxq implements java.io.Serializable {

	private String id;
	private BigDecimal zdwsl;
	private BigDecimal cdwsl;
	private BigDecimal zdwdj;
	private BigDecimal cdwdj;
	private BigDecimal spje;
	private Integer yxq;
	private BigDecimal zhxs;
	private String cjldwId;
	private String zjldwId;
	private String spbz;
	private String spbh;
	private String spdwId;
	private String spcd;
	private String sppp;
	private String cgxqlsh;
	private Date createTime;
	private Integer createId;
	private String bmbh;
	private Integer ywyId;
	private String gysbh;
	private String dhfs;
	private String shdz;
	private Date dhsj;
	private Integer xqsj;
	private String fkfs;
	private BigDecimal hjje;
	private String bz;
	private Character isCancel;
	private Date cancelTime;
	private Integer cancelId;
	private Character isCompleted;
	private Date completeTime;
	private String cgjhlsh;
	private Integer completeId;
	private String gysmc;
	private String dzdh;
	private String khh;
	private String sh;
	private String fr;

	public VCgxq() {
	}

	

	public VCgxq(String id, BigDecimal zdwsl, BigDecimal cdwsl,
			BigDecimal zdwdj, BigDecimal cdwdj, BigDecimal spje, Integer yxq,
			BigDecimal zhxs, String cjldwId, String zjldwId, String spbz,
			String spbh, String spdwId, String spcd, String sppp,
			String cgxqlsh, Date createTime, Integer createId, String bmbh,
			Integer ywyId, String gysbh, String dhfs, String shdz, Date dhsj,
			Integer xqsj, String fkfs, BigDecimal hjje, String bz,
			Character isCancel, Date cancelTime, Integer cancelId,
			Character isCompleted, Date completeTime, String cgjhlsh,
			Integer completeId, String gysmc, String dzdh, String khh,
			String sh, String fr) {
		this.id = id;
		this.zdwsl = zdwsl;
		this.cdwsl = cdwsl;
		this.zdwdj = zdwdj;
		this.cdwdj = cdwdj;
		this.spje = spje;
		this.yxq = yxq;
		this.zhxs = zhxs;
		this.cjldwId = cjldwId;
		this.zjldwId = zjldwId;
		this.spbz = spbz;
		this.spbh = spbh;
		this.spdwId = spdwId;
		this.spcd = spcd;
		this.sppp = sppp;
		this.cgxqlsh = cgxqlsh;
		this.createTime = createTime;
		this.createId = createId;
		this.bmbh = bmbh;
		this.ywyId = ywyId;
		this.gysbh = gysbh;
		this.dhfs = dhfs;
		this.shdz = shdz;
		this.dhsj = dhsj;
		this.xqsj = xqsj;
		this.fkfs = fkfs;
		this.hjje = hjje;
		this.bz = bz;
		this.isCancel = isCancel;
		this.cancelTime = cancelTime;
		this.cancelId = cancelId;
		this.isCompleted = isCompleted;
		this.completeTime = completeTime;
		this.cgjhlsh = cgjhlsh;
		this.completeId = completeId;
		this.gysmc = gysmc;
		this.dzdh = dzdh;
		this.khh = khh;
		this.sh = sh;
		this.fr = fr;
	}

	@Id
	@Column(name = "id", nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "zdwsl", precision = 18, scale = 3)
	public BigDecimal getZdwsl() {
		return this.zdwsl;
	}

	public void setZdwsl(BigDecimal zdwsl) {
		this.zdwsl = zdwsl;
	}

	@Column(name = "cdwsl", precision = 18, scale = 3)
	public BigDecimal getCdwsl() {
		return this.cdwsl;
	}

	public void setCdwsl(BigDecimal cdwsl) {
		this.cdwsl = cdwsl;
	}

	@Column(name = "zdwdj", precision = 18, scale = 3)
	public BigDecimal getZdwdj() {
		return this.zdwdj;
	}

	public void setZdwdj(BigDecimal zdwdj) {
		this.zdwdj = zdwdj;
	}

	@Column(name = "cdwdj", precision = 18, scale = 3)
	public BigDecimal getCdwdj() {
		return this.cdwdj;
	}

	public void setCdwdj(BigDecimal cdwdj) {
		this.cdwdj = cdwdj;
	}

	@Column(name = "spje", precision = 18, scale = 6)
	public BigDecimal getSpje() {
		return this.spje;
	}

	public void setSpje(BigDecimal spje) {
		this.spje = spje;
	}

	@Column(name = "yxq")
	public Integer getYxq() {
		return this.yxq;
	}

	public void setYxq(Integer yxq) {
		this.yxq = yxq;
	}

	@Column(name = "zhxs", precision = 18, scale = 3)
	public BigDecimal getZhxs() {
		return this.zhxs;
	}

	public void setZhxs(BigDecimal zhxs) {
		this.zhxs = zhxs;
	}

	@Column(name = "cjldwId", length = 2)
	public String getCjldwId() {
		return this.cjldwId;
	}

	public void setCjldwId(String cjldwId) {
		this.cjldwId = cjldwId;
	}

	@Column(name = "zjldwId", nullable = false, length = 2)
	public String getZjldwId() {
		return this.zjldwId;
	}

	public void setZjldwId(String zjldwId) {
		this.zjldwId = zjldwId;
	}

	@Column(name = "spbz", length = 50)
	public String getSpbz() {
		return this.spbz;
	}

	public void setSpbz(String spbz) {
		this.spbz = spbz;
	}

	@Column(name = "spbh", nullable = false, length = 7)
	public String getSpbh() {
		return this.spbh;
	}

	public void setSpbh(String spbh) {
		this.spbh = spbh;
	}

	@Column(name = "spdwId", nullable = false, length = 5)
	public String getSpdwId() {
		return this.spdwId;
	}

	public void setSpdwId(String spdwId) {
		this.spdwId = spdwId;
	}

	@Column(name = "spcd", nullable = false, length = 50)
	public String getSpcd() {
		return this.spcd;
	}

	public void setSpcd(String spcd) {
		this.spcd = spcd;
	}

	@Column(name = "sppp", length = 50)
	public String getSppp() {
		return this.sppp;
	}

	public void setSppp(String sppp) {
		this.sppp = sppp;
	}

	@Column(name = "cgxqlsh", nullable = false, length = 12)
	public String getCgxqlsh() {
		return this.cgxqlsh;
	}

	public void setCgxqlsh(String cgxqlsh) {
		this.cgxqlsh = cgxqlsh;
	}

	@Column(name = "createTime", nullable = false, length = 23)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createId")
	public Integer getCreateId() {
		return this.createId;
	}

	public void setCreateId(Integer createId) {
		this.createId = createId;
	}

	@Column(name = "bmbh", length = 2)
	public String getBmbh() {
		return this.bmbh;
	}

	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}

	@Column(name = "ywyId")
	public Integer getYwyId() {
		return this.ywyId;
	}

	public void setYwyId(Integer ywyId) {
		this.ywyId = ywyId;
	}

	@Column(name = "gysbh", length = 8)
	public String getGysbh() {
		return this.gysbh;
	}

	public void setGysbh(String gysbh) {
		this.gysbh = gysbh;
	}

	@Column(name = "dhfs", length = 50)
	public String getDhfs() {
		return this.dhfs;
	}

	public void setDhfs(String dhfs) {
		this.dhfs = dhfs;
	}

	@Column(name = "shdz", length = 50)
	public String getShdz() {
		return this.shdz;
	}

	public void setShdz(String shdz) {
		this.shdz = shdz;
	}

	@Column(name = "dhsj", length = 23)
	public Date getDhsj() {
		return this.dhsj;
	}

	public void setDhsj(Date dhsj) {
		this.dhsj = dhsj;
	}

	@Column(name = "xqsj")
	public Integer getXqsj() {
		return this.xqsj;
	}

	public void setXqsj(Integer xqsj) {
		this.xqsj = xqsj;
	}

	@Column(name = "fkfs", length = 50)
	public String getFkfs() {
		return this.fkfs;
	}

	public void setFkfs(String fkfs) {
		this.fkfs = fkfs;
	}

	@Column(name = "hjje", precision = 18, scale = 6)
	public BigDecimal getHjje() {
		return this.hjje;
	}

	public void setHjje(BigDecimal hjje) {
		this.hjje = hjje;
	}

	@Column(name = "bz", length = 100)
	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	@Column(name = "isCancel", length = 1)
	public Character getIsCancel() {
		return this.isCancel;
	}

	public void setIsCancel(Character isCancel) {
		this.isCancel = isCancel;
	}

	@Column(name = "cancelTime", length = 23)
	public Date getCancelTime() {
		return this.cancelTime;
	}

	public void setCancelTime(Date cancelTime) {
		this.cancelTime = cancelTime;
	}

	@Column(name = "cancelId")
	public Integer getCancelId() {
		return this.cancelId;
	}

	public void setCancelId(Integer cancelId) {
		this.cancelId = cancelId;
	}

	@Column(name = "isCompleted", length = 1)
	public Character getIsCompleted() {
		return this.isCompleted;
	}

	public void setIsCompleted(Character isCompleted) {
		this.isCompleted = isCompleted;
	}

	@Column(name = "completeTime", length = 23)
	public Date getCompleteTime() {
		return this.completeTime;
	}

	public void setCompleteTime(Date completeTime) {
		this.completeTime = completeTime;
	}

	@Column(name = "cgjhlsh", length = 12)
	public String getCgjhlsh() {
		return this.cgjhlsh;
	}

	public void setCgjhlsh(String cgjhlsh) {
		this.cgjhlsh = cgjhlsh;
	}

	@Column(name = "completeId")
	public Integer getCompleteId() {
		return this.completeId;
	}

	public void setCompleteId(Integer completeId) {
		this.completeId = completeId;
	}

	@Column(name = "gysmc", nullable = false, length = 100)
	public String getGysmc() {
		return this.gysmc;
	}

	public void setGysmc(String gysmc) {
		this.gysmc = gysmc;
	}

	@Column(name = "dzdh", length = 200)
	public String getDzdh() {
		return this.dzdh;
	}

	public void setDzdh(String dzdh) {
		this.dzdh = dzdh;
	}

	@Column(name = "khh", length = 200)
	public String getKhh() {
		return this.khh;
	}

	public void setKhh(String khh) {
		this.khh = khh;
	}

	@Column(name = "sh", length = 15)
	public String getSh() {
		return this.sh;
	}

	public void setSh(String sh) {
		this.sh = sh;
	}

	@Column(name = "fr", length = 20)
	public String getFr() {
		return this.fr;
	}

	public void setFr(String fr) {
		this.fr = fr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VCgxq))
			return false;
		VCgxq castOther = (VCgxq) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getZdwsl() == castOther.getZdwsl()) || (this
						.getZdwsl() != null && castOther.getZdwsl() != null && this
						.getZdwsl().equals(castOther.getZdwsl())))
				&& ((this.getCdwsl() == castOther.getCdwsl()) || (this
						.getCdwsl() != null && castOther.getCdwsl() != null && this
						.getCdwsl().equals(castOther.getCdwsl())))
				&& ((this.getZdwdj() == castOther.getZdwdj()) || (this
						.getZdwdj() != null && castOther.getZdwdj() != null && this
						.getZdwdj().equals(castOther.getZdwdj())))
				&& ((this.getCdwdj() == castOther.getCdwdj()) || (this
						.getCdwdj() != null && castOther.getCdwdj() != null && this
						.getCdwdj().equals(castOther.getCdwdj())))
				&& ((this.getSpje() == castOther.getSpje()) || (this.getSpje() != null
						&& castOther.getSpje() != null && this.getSpje()
						.equals(castOther.getSpje())))
				&& ((this.getYxq() == castOther.getYxq()) || (this.getYxq() != null
						&& castOther.getYxq() != null && this.getYxq().equals(
						castOther.getYxq())))
				&& ((this.getZhxs() == castOther.getZhxs()) || (this.getZhxs() != null
						&& castOther.getZhxs() != null && this.getZhxs()
						.equals(castOther.getZhxs())))
				&& ((this.getCjldwId() == castOther.getCjldwId()) || (this
						.getCjldwId() != null && castOther.getCjldwId() != null && this
						.getCjldwId().equals(castOther.getCjldwId())))
				&& ((this.getZjldwId() == castOther.getZjldwId()) || (this
						.getZjldwId() != null && castOther.getZjldwId() != null && this
						.getZjldwId().equals(castOther.getZjldwId())))
				&& ((this.getSpbz() == castOther.getSpbz()) || (this.getSpbz() != null
						&& castOther.getSpbz() != null && this.getSpbz()
						.equals(castOther.getSpbz())))
				&& ((this.getSpbh() == castOther.getSpbh()) || (this
						.getSpbh() != null && castOther.getSpbh() != null && this
						.getSpbh().equals(castOther.getSpbh())))
				&& ((this.getSpdwId() == castOther.getSpdwId()) || (this
						.getSpdwId() != null && castOther.getSpdwId() != null && this
						.getSpdwId().equals(castOther.getSpdwId())))
				&& ((this.getSpcd() == castOther.getSpcd()) || (this.getSpcd() != null
						&& castOther.getSpcd() != null && this.getSpcd()
						.equals(castOther.getSpcd())))
				&& ((this.getSppp() == castOther.getSppp()) || (this.getSppp() != null
						&& castOther.getSppp() != null && this.getSppp()
						.equals(castOther.getSppp())))
				&& ((this.getCgxqlsh() == castOther.getCgxqlsh()) || (this
						.getCgxqlsh() != null && castOther.getCgxqlsh() != null && this
						.getCgxqlsh().equals(castOther.getCgxqlsh())))
				&& ((this.getCreateTime() == castOther.getCreateTime()) || (this
						.getCreateTime() != null
						&& castOther.getCreateTime() != null && this
						.getCreateTime().equals(castOther.getCreateTime())))
				&& ((this.getCreateId() == castOther.getCreateId()) || (this
						.getCreateId() != null
						&& castOther.getCreateId() != null && this
						.getCreateId().equals(castOther.getCreateId())))
				&& ((this.getBmbh() == castOther.getBmbh()) || (this.getBmbh() != null
						&& castOther.getBmbh() != null && this.getBmbh()
						.equals(castOther.getBmbh())))
				&& ((this.getYwyId() == castOther.getYwyId()) || (this
						.getYwyId() != null && castOther.getYwyId() != null && this
						.getYwyId().equals(castOther.getYwyId())))
				&& ((this.getGysbh() == castOther.getGysbh()) || (this
						.getGysbh() != null && castOther.getGysbh() != null && this
						.getGysbh().equals(castOther.getGysbh())))
				&& ((this.getDhfs() == castOther.getDhfs()) || (this.getDhfs() != null
						&& castOther.getDhfs() != null && this.getDhfs()
						.equals(castOther.getDhfs())))
				&& ((this.getShdz() == castOther.getShdz()) || (this.getShdz() != null
						&& castOther.getShdz() != null && this.getShdz()
						.equals(castOther.getShdz())))
				&& ((this.getDhsj() == castOther.getDhsj()) || (this.getDhsj() != null
						&& castOther.getDhsj() != null && this.getDhsj()
						.equals(castOther.getDhsj())))
				&& ((this.getXqsj() == castOther.getXqsj()) || (this.getXqsj() != null
						&& castOther.getXqsj() != null && this.getXqsj()
						.equals(castOther.getXqsj())))
				&& ((this.getFkfs() == castOther.getFkfs()) || (this.getFkfs() != null
						&& castOther.getFkfs() != null && this.getFkfs()
						.equals(castOther.getFkfs())))
				&& ((this.getHjje() == castOther.getHjje()) || (this.getHjje() != null
						&& castOther.getHjje() != null && this.getHjje()
						.equals(castOther.getHjje())))
				&& ((this.getBz() == castOther.getBz()) || (this.getBz() != null
						&& castOther.getBz() != null && this.getBz().equals(
						castOther.getBz())))
				&& ((this.getIsCancel() == castOther.getIsCancel()) || (this
						.getIsCancel() != null
						&& castOther.getIsCancel() != null && this
						.getIsCancel().equals(castOther.getIsCancel())))
				&& ((this.getCancelTime() == castOther.getCancelTime()) || (this
						.getCancelTime() != null
						&& castOther.getCancelTime() != null && this
						.getCancelTime().equals(castOther.getCancelTime())))
				&& ((this.getCancelId() == castOther.getCancelId()) || (this
						.getCancelId() != null
						&& castOther.getCancelId() != null && this
						.getCancelId().equals(castOther.getCancelId())))
				&& ((this.getIsCompleted() == castOther.getIsCompleted()) || (this
						.getIsCompleted() != null
						&& castOther.getIsCompleted() != null && this
						.getIsCompleted().equals(castOther.getIsCompleted())))
				&& ((this.getCompleteTime() == castOther.getCompleteTime()) || (this
						.getCompleteTime() != null
						&& castOther.getCompleteTime() != null && this
						.getCompleteTime().equals(castOther.getCompleteTime())))
				&& ((this.getCgjhlsh() == castOther.getCgjhlsh()) || (this
						.getCgjhlsh() != null && castOther.getCgjhlsh() != null && this
						.getCgjhlsh().equals(castOther.getCgjhlsh())))
				&& ((this.getCompleteId() == castOther.getCompleteId()) || (this
						.getCompleteId() != null
						&& castOther.getCompleteId() != null && this
						.getCompleteId().equals(castOther.getCompleteId())))
				&& ((this.getGysmc() == castOther.getGysmc()) || (this
						.getGysmc() != null && castOther.getGysmc() != null && this
						.getGysmc().equals(castOther.getGysmc())))
				&& ((this.getDzdh() == castOther.getDzdh()) || (this.getDzdh() != null
						&& castOther.getDzdh() != null && this.getDzdh()
						.equals(castOther.getDzdh())))
				&& ((this.getKhh() == castOther.getKhh()) || (this.getKhh() != null
						&& castOther.getKhh() != null && this.getKhh().equals(
						castOther.getKhh())))
				&& ((this.getSh() == castOther.getSh()) || (this.getSh() != null
						&& castOther.getSh() != null && this.getSh().equals(
						castOther.getSh())))
				&& ((this.getFr() == castOther.getFr()) || (this.getFr() != null
						&& castOther.getFr() != null && this.getFr().equals(
						castOther.getFr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getZdwsl() == null ? 0 : this.getZdwsl().hashCode());
		result = 37 * result
				+ (getCdwsl() == null ? 0 : this.getCdwsl().hashCode());
		result = 37 * result
				+ (getZdwdj() == null ? 0 : this.getZdwdj().hashCode());
		result = 37 * result
				+ (getCdwdj() == null ? 0 : this.getCdwdj().hashCode());
		result = 37 * result
				+ (getSpje() == null ? 0 : this.getSpje().hashCode());
		result = 37 * result
				+ (getYxq() == null ? 0 : this.getYxq().hashCode());
		result = 37 * result
				+ (getZhxs() == null ? 0 : this.getZhxs().hashCode());
		result = 37 * result
				+ (getCjldwId() == null ? 0 : this.getCjldwId().hashCode());
		result = 37 * result
				+ (getZjldwId() == null ? 0 : this.getZjldwId().hashCode());
		result = 37 * result
				+ (getSpbz() == null ? 0 : this.getSpbz().hashCode());
		result = 37 * result
				+ (getSpbh() == null ? 0 : this.getSpbh().hashCode());
		result = 37 * result
				+ (getSpdwId() == null ? 0 : this.getSpdwId().hashCode());
		result = 37 * result
				+ (getSpcd() == null ? 0 : this.getSpcd().hashCode());
		result = 37 * result
				+ (getSppp() == null ? 0 : this.getSppp().hashCode());
		result = 37 * result
				+ (getCgxqlsh() == null ? 0 : this.getCgxqlsh().hashCode());
		result = 37
				* result
				+ (getCreateTime() == null ? 0 : this.getCreateTime()
						.hashCode());
		result = 37 * result
				+ (getCreateId() == null ? 0 : this.getCreateId().hashCode());
		result = 37 * result
				+ (getBmbh() == null ? 0 : this.getBmbh().hashCode());
		result = 37 * result
				+ (getYwyId() == null ? 0 : this.getYwyId().hashCode());
		result = 37 * result
				+ (getGysbh() == null ? 0 : this.getGysbh().hashCode());
		result = 37 * result
				+ (getDhfs() == null ? 0 : this.getDhfs().hashCode());
		result = 37 * result
				+ (getShdz() == null ? 0 : this.getShdz().hashCode());
		result = 37 * result
				+ (getDhsj() == null ? 0 : this.getDhsj().hashCode());
		result = 37 * result
				+ (getXqsj() == null ? 0 : this.getXqsj().hashCode());
		result = 37 * result
				+ (getFkfs() == null ? 0 : this.getFkfs().hashCode());
		result = 37 * result
				+ (getHjje() == null ? 0 : this.getHjje().hashCode());
		result = 37 * result + (getBz() == null ? 0 : this.getBz().hashCode());
		result = 37 * result
				+ (getIsCancel() == null ? 0 : this.getIsCancel().hashCode());
		result = 37
				* result
				+ (getCancelTime() == null ? 0 : this.getCancelTime()
						.hashCode());
		result = 37 * result
				+ (getCancelId() == null ? 0 : this.getCancelId().hashCode());
		result = 37
				* result
				+ (getIsCompleted() == null ? 0 : this.getIsCompleted()
						.hashCode());
		result = 37
				* result
				+ (getCompleteTime() == null ? 0 : this.getCompleteTime()
						.hashCode());
		result = 37 * result
				+ (getCgjhlsh() == null ? 0 : this.getCgjhlsh().hashCode());
		result = 37
				* result
				+ (getCompleteId() == null ? 0 : this.getCompleteId()
						.hashCode());
		result = 37 * result
				+ (getGysmc() == null ? 0 : this.getGysmc().hashCode());
		result = 37 * result
				+ (getDzdh() == null ? 0 : this.getDzdh().hashCode());
		result = 37 * result
				+ (getKhh() == null ? 0 : this.getKhh().hashCode());
		result = 37 * result + (getSh() == null ? 0 : this.getSh().hashCode());
		result = 37 * result + (getFr() == null ? 0 : this.getFr().hashCode());
		return result;
	}

}
