
package lnyswz.jxc.wllgs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Pr2lg", targetNamespace = "http://wllgs")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Pr2Lg {


    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "wsCargoReturn", partName = "wsCargoReturn")
    public String wsCargo(
        @WebParam(name = "Xml", partName = "Xml")
        String xml);

}
