
package lnyswz.jxc.wllgs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * ������Ϣwww.yunyin.com�������ʹ�˾���ݽӿ�WebService.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Pr2lgService", targetNamespace = "http://wllgs", wsdlLocation = "http://172.28.10.25:828/wllgs/pr2lg.cfc?wsdl")
public class Pr2LgService
    extends Service
{

    private final static URL PR2LGSERVICE_WSDL_LOCATION;
    private final static WebServiceException PR2LGSERVICE_EXCEPTION;
    private final static QName PR2LGSERVICE_QNAME = new QName("http://wllgs", "Pr2lgService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.28.10.25:828/wllgs/pr2lg.cfc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PR2LGSERVICE_WSDL_LOCATION = url;
        PR2LGSERVICE_EXCEPTION = e;
    }

    public Pr2LgService() {
        super(__getWsdlLocation(), PR2LGSERVICE_QNAME);
    }

    /*public Pr2LgService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PR2LGSERVICE_QNAME, features);
    }

    public Pr2LgService(URL wsdlLocation) {
        super(wsdlLocation, PR2LGSERVICE_QNAME);
    }

    public Pr2LgService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PR2LGSERVICE_QNAME, features);
    }

    public Pr2LgService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Pr2LgService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }*/

    /**
     * 
     * @return
     *     returns Pr2Lg
     */
    @WebEndpoint(name = "pr2lg.cfc")
    public Pr2Lg getPr2LgCfc() {
        return super.getPort(new QName("http://wllgs", "pr2lg.cfc"), Pr2Lg.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Pr2Lg
     */
    @WebEndpoint(name = "pr2lg.cfc")
    public Pr2Lg getPr2LgCfc(WebServiceFeature... features) {
        return super.getPort(new QName("http://wllgs", "pr2lg.cfc"), Pr2Lg.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PR2LGSERVICE_EXCEPTION!= null) {
            throw PR2LGSERVICE_EXCEPTION;
        }
        return PR2LGSERVICE_WSDL_LOCATION;
    }

}
